### ISSUE TITLE
enhancement request: Support for Oracle RDS

### ISSUE THREAD

**Issue by jandroav** [localstack/localstack#10074]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Enhancement description

I would like to be able to create Oracle RDS local instances.

Currently `localstack` can create relational database engines like:

- MySQL
- PostgreSQL
- MariaDB
- Microsoft SQL Server

Simulating local Oracle RDS instances for testing purposes can be more cost-effective than relying on actual cloud-based instances. It enables us to control costs associated with testing while still providing a robust testing environment.

**Comment by jandroav** [comment]
Why this was closed?

**Comment by shylaharild** [comment]
This is still required for many projects using Oracle RDS. @bentsku @localstack-bot, please reopen this issue

**Comment by HarshCasper** [comment]
Due to the forthcoming changes in our distribution and development model ([read more](https://blog.localstack.cloud/the-road-ahead-for-localstack/)), this issue tracker is no longer being maintained. We've migrated this issue to our internal tracker and will continue to work on it there. If you'd like to follow up on the status or expedite this, feel free to reach out through one of our support channels:

-   💬 [GitHub Discussions](https://github.com/orgs/localstack/discussions)
-   📖 [Help & Support](https://docs.localstack.cloud/aws/getting-started/help-support/)
