### ISSUE TITLE
bug: Lambda function "Cannot list external agents" and containers keep spawning.

### ISSUE THREAD

**Issue by generalpy101** [localstack/localstack#10081]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hey,
I was trying to use localstack to run my AWS code locally (I'm new to AWS too but everything working file so far using docs). For that I created lambda which will add some message to a custom Rabbitmq queue. Code can be found here: https://github.com/generalpy101/vetube

Everytime I upload file to s3(event on which lambda is supposed to invoke), a container for lambda spawns but insite it I get an error:

```
time="2024-01-17T06:00:36Z" level=warning msg="Cannot list external agents" func=go.amzn.com/lambda/agents.ListExternalAgentPaths file="/home/runner/work/lambda-runtime-init/lambda-runtime-init/lambda/agents/agent.go:24" error="open /opt/extensions: no such file or directory"
```

And then after some time localstack spawns another container and after some time timeout is shown on localstack logs and this cycle continues.

Error in localstack logs

```
 Failed invocation MyHTTPConnectionPool(host='172.17.0.5', port=9563): Max retries exceeded with url: /invoke (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f703e2b8190>, 'Connection to 172.17.0.5 timed out. (connect timeout=None)'))
```

### Expected Behavior

Lambda function should execute without any proble.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker-compose down --volumes --remove-orphans && docker-compose up --build

There is a setup script which executes in a separate container defined in docker compose. 

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    aws --endpoint-url=http://localhost:4566 s3 cp test.txt s3://vetube/

Copying sample file to invoke lambda function.

### Environment

```markdown
- OS: Ubuntu 22.04.3 LTS on Windows 10 x86_64
- LocalStack: Latest Docker Image.
```

### Anything else?

[This ](https://github.com/localstack/localstack/issues/8432) issue is somewhat related to mine but I tried these solutions but they didn't work.

PS: I am noob in AWS and Localstack so there might be problems in code that stackoverflow cannot explain.

**Comment by generalpy101** [comment]
Using version `1.4` for now as it seems to work.
Unblocked here.

**Comment by joe4dev** [comment]
Hi @generalpy101 

Thank you for sharing a reproducer sample 👍  .

> Everytime I upload file to s3(event on which lambda is supposed to invoke), a container for lambda spawns but insite it I get an error:
> time="2024-01-17T06:00:36Z" level=warning msg="Cannot list external agents" func=go.amzn.com/lambda/agents.ListExternalAgentPaths file="/home/runner/work/lambda-runtime-init/lambda-runtime-init/lambda/agents/agent.go:24" error="open /opt/extensions: no such file or directory"

That is an expected warning log message from the [lambda-runtime-init](https://github.com/localstack/lambda-runtime-init/blob/28d666181b3686b093a360ea929ccb4c6f009617/lambda/agents/agent.go#L29) because `/opt/extensions` exists but is empty.

> And then after some time localstack spawns another container and after some time timeout is shown on localstack logs and this cycle continues.

Last year, the [infinite error loop has been resolved](https://github.com/localstack/localstack/issues/8878#issuecomment-1750171148) in major Lambda improvements https://github.com/localstack/localstack/pull/8970.
Please upgrade your LocalStack version and this error should be resolved.

> Error in localstack logs
>  Failed invocation MyHTTPConnectionPool(host='172.17.0.5', port=9563): Max retries exceeded with url: /invoke (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f703e2b8190>, 'Connection to 172.17.0.5 timed out. (connect timeout=None)'))

This looks like a networking issue. LocalStack v3 comes with a lot of networking improvements. Please checkout our blog post [How we are making connecting to LocalStack easier](https://blog.localstack.cloud/2024-03-04-making-connecting-to-localstack-easier/). The new DNS-based solution could make your scenario much easier without requiring dedicated code changes for LocalStack 🚀
