### ISSUE TITLE
Support MediaConvert AWS service

### ISSUE THREAD

**Issue by holyoaks** [localstack/localstack#10232]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Enhancement description

I plan on using MediaConvert to convert video files to a standard file format, as well as to get a screenshot of one or more frames from the video. I use Localstack for S3, DynamoDB, RDS, and other AWS services. The only service I use that is NOT in localstack is MediaConvert. It would be really nice to do ALL of my development locally, instead of having to write code and deploy to an AWS instance to test the MediaConvert code.

**Comment by pencil** [comment]
Also interested in this. It would likely require adding a dependency to `ffmpeg` to run the transcoding – not sure what the best way to do that would be so as to not unreasonably blow up the size of localstac's Docker image.

**Comment by simonrw** [comment]
Hi @holyoaks, sorry for not responding sooner but since version 3.8.0 we have a mock implementation of some Mediaconvert functionality around 
* queues
* jobs
* eventbridge integration
We don't yet implement transcoding itself. I will close this issue and create a new feature request for transcoding support to capture @pencil 's request. Please feel free to upvote that.

If this is not ok, please feel free to re-open this request.
