### ISSUE TITLE
bug: FIFO SQS Consumer is not executed after inactivity

### ISSUE THREAD

**Issue by laas29** [localstack/localstack#10290]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If this message is shown in the terminal, the consumer is not longer executed
<img width="1220" alt="image" src="https://github.com/localstack/localstack/assets/6174109/8c5cea0a-272c-4f43-8006-9d325ac407c8">

No further message/error shown after that, so I have to deploy everything from scratch to make the lambda work again.

### Expected Behavior

The consumer lambda have to be executed once is called regardless of inactivity.

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

Docker compose:
<img width="670" alt="image" src="https://github.com/localstack/localstack/assets/6174109/ef5c0052-70df-4356-9314-992a19cc3a2b">

My serverless template:
<img width="807" alt="image" src="https://github.com/localstack/localstack/assets/6174109/f1fe650a-36ff-4d70-a2b1-3d0bcb0fb339">

### Environment

```markdown
- OS: macOS Ventura 13.5.2
- LocalStack: 3.1.0
- serverless: 3.33.0
```

### Anything else?

It works if the lambda does not get inactive, once inactive, the consumer is not longer executed.

The same configuration works as expected in an AWS env.

**Comment by jtich** [comment]
+1

**Comment by mercadoalex** [comment]
+1

**Comment by david-customed** [comment]
+1

**Comment by joe4dev** [comment]
Hi everyone 👋 

Thank you for sharing this issue 🙏 . We are actively working on improving Lambda Event Source Mapping 📈, also based on your feedback 🙇  

@laas29 Does our new `LAMBDA_EVENT_SOURCE_MAPPING=v2` implementation resolve this issue?

We just released LocalStack 3.7.0 🚀 today with a new implementation for Lambda Event Source Mappings: https://blog.localstack.cloud/2024-08-29-localstack-release-v-3-7-0/#new-lambda-event-source-mapping-implementation

LocalStack now supports a new implementation for [Lambda Event Source Mapping](https://docs.aws.amazon.com/lambda/latest/dg/invocation-eventsourcemapping.html) (ESM) with improved reliability, performance, and AWS parity.
You can use the `LAMBDA_EVENT_SOURCE_MAPPING=v2` configuration variable to use the new ESM implementation.
The ESM v2 implementation is also compatible with the Java-based event pattern rule engine (`EVENT_RULE_ENGINE=java`).
However, the new ESM implementation is still in **preview** and may not support all features.

The improvements over ESM v1 include:

- Improved reliability through internal retries and separation of concern such that single exceptions or timeouts don't affect other event source mappings.
- Improved performance by enabling concurrent event source mappings rather than having a single thread handling everything.
- Improved AWS parity, for example, related to filtering and SQS polling.

The limitations compared to ESM v1 include:

- Lambda Failure Destinations do not yet support FIFO SQS queues and SNS topics.
- Lambda Failure Destination Messages do not yet match the AWS structure, using a `context` similar to EventBridge Pipes instead of `requestContext` and `responseContext`.
- Partial Batch Responses using `FunctionResponseTypes` are not yet fully supported.
- Managed Streaming for Apache Kafka (MSK) event source is not yet supported.
- ESM Lifecycle State Updates only provide basic support for state updates, such as no failure states, and `LastProcessingResult` is not consistently updated.
- Persistence is not yet supported.

The limitations compared to AWS include:
- Lambda Success Destinations are not supported.
- Only very basic validations are performed upon creating and updating ESM.
- Streaming Pollers for Kinesis and DynamoDB do not implement features like:
  - `BisectBatchOnFunctionError`
  - `MaximumBatchingWindowInSeconds`
  - `ParallelizationFactor`
  - `ScalingConfig`
  - `TumblingWindowInSeconds`.

**Comment by joe4dev** [comment]
@laas29  Do you know whether the inactivity issue only happens with an event source mapping?

The inactivity timeout is [configurable](https://docs.localstack.cloud/references/configuration/#lambda) using `LAMBDA_KEEPALIVE_MS` 600000 (default 10min): 
> Time in milliseconds until lambda shuts down the execution environment after the last invocation has been processed. Set to 0 to immediately shut down the execution environment after an invocation.

The `LAMBDA_RUNTIME_ENVIRONMENT_TIMEOUT` is related to the startup time (shouldn't affect inactivity):
> How many seconds Lambda will wait for the runtime environment to start up. Increase this timeout if I/O is slow or your Lambda deployments are large or contain many files.

**Comment by joe4dev** [comment]
Check out our new Lambda event source mapping (ESM) implementation in [LocalStack v4](https://blog.localstack.cloud/announcing-localstack-40-general-availability/) offering better functional and non-functional support for ESM 🚀 . The behavioral coverage documentation provides more details for your use case https://docs.localstack.cloud/user-guide/aws/lambda/#lambda-event-source-mappings

Feel free to open another issue or share your feedback if you experience any challenges👂
