### ISSUE TITLE
bug: LocalStack fails with Internal Error on S3 SelectObjectContent API

### ISSUE THREAD

**Issue by anna-mazhar** [localstack/localstack#10329]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

- Localstack fails with an "InternalError" when calling the [select_object_content](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3/client/select_object_content.html) S3 API on an empty object.
- The specific error message is: "An error occurred (InternalError) when calling the SelectObjectContent operation (reached max retries: 4): exception while calling s3.SelectObjectContent: 'Variable' object is not iterable".

### Expected Behavior

- The same request when routed to the cloud, returns with a success code (Localstack should have parity with the cloud). Note that the states at the cloud and emulator are the same.
- It appears that LocalStack lacks certain exception handling. 

### How are you starting LocalStack?

With a `docker run` command

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    s3_client = boto3.client('s3', endpoint_url='http://localhost:4566')
    response = s3_client.select_object_content(
        Bucket='test_bucket',
        Key='key',
        ExpressionType='SQL',
        Expression="select * from s3object",
        InputSerialization='CSV': {
                    'FileHeaderInfo': 'USE',
                    'RecordDelimiter': '\n',
                    'FieldDelimiter': ','
        },
        OutputSerialization={'CSV': {}},
    )

 An empty object was already uploaded to the specified bucket.

### Environment

```markdown
- OS: Ubuntu 22.04.2 LTS
- LocalStack: 2.1.0
- boto3: 1.28.6
```

**Comment by bentsku** [comment]
Hello @anna-mazhar, this issue should now be fixed when calling `SelectObjectContent` on an empty file. 

I just wanted to note that the `SelectObjectContent` is part of our Pro offering (in the `localstack/localstack-pro` image). During a small moment, we've had a very basic implementation of it in the community version, due to an upstream library implementing it, but our implementation is more advanced and was there before, so we've had to remove it because we could not provide support for it. Thanks for your comprehension.

**Comment by anna-mazhar** [comment]
I understand. Thanks @bentsku!
Closing the issue.
