### ISSUE TITLE
docker build from repo clone error

### ISSUE THREAD

**Issue by jrm2k6** [localstack/localstack#1046]
After cloning the repo and running: `docker build -t localstack:latest .`
I can see the following errors:

```
Starting mock Lambda service (http port 4574)...
ERROR: Error forwarding request: HTTPConnectionPool(host='127.0.0.1', port=4564): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4c7b4e7c10>: Failed to establish a new connection: [Errno 111] Connection refused',)) Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 216, in forward
    headers=forward_headers, stream=True)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/sessions.py", line 524, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/sessions.py", line 637, in send
    r = adapter.send(request, **kwargs)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=4564): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4c7b4e7c10>: Failed to establish a new connection: [Errno 111] Connection refused',))
```

I see the same thing when running `localstack start --docker` which is what I originally tried as I would like to use localstack for development purposes in an existing stack.

MacOS Mojave 10.14
Docker for Mac: 18.06.1-ce-mac73 (26764)

**Comment by oravecz** [comment]
I get the same when using docker-compose. Since this has gone unanswered for a couple weeks, I suppose it is either very specific to my setup, or this happens all the time and it is too common a problem to bother answering again and again. ;)

MacOS Mojave 10.14.1
docker-compose version 1.23.2, build 1110ad01
Docker version 18.09.0, build 4d60db4
localstack/localstack   latest              2fc065aa7dd2        34 hours ago        1.01GB

The first few times I execute the docker image, I get the exact error (after Lambda init) as OP. 

In subsequent runs, I have seen DynamoDB local start successfully, and even ElasticSearch boot up. But still the same error as OP is shown, and the dashboard at localhost:8080 does not show any content (just a menu on the left side).

**Comment by whummer** [comment]
Thanks for reporting @jrm2k6 @oravecz . Looks like this is not a real error, but a timing issue when starting up the infrastructure, as we're sending probe requests until the service becomes available. As long as you can see the `Ready.` line on stdout, things should be fine.

PR #1072 contains a change that should fix the error output, though. Can you please give it a try with the latest version, and report back if you can reproduce the issue? Thanks
