### ISSUE TITLE
Enhancement Request: Support for ECS Task Metadata Endpoint

### ISSUE THREAD

**Issue by MarcelStranak** [localstack/localstack#10645]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Enhancement description

We have received a request from a user to add support for the ECS Task Metadata Endpoint V2 for ECS (Fargate) containers in LocalStack.

### 🧑‍💻 Implementation

Implement Task Metadata Endpoint V2, V3, V4.

### Anything else?

Information on the Task Metadata Endpoint for ECS can be found in the AWS documentation: [Task Metadata Endpoint V2](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-metadata-endpoint-v2.html#task-metadata-endpoint-v2-enable)

**Comment by wederribas** [comment]
Hi folks! Is there any interest from LocalStack or even enough customer demand to revive this request?

I am implementing a full-fledged OpenTelemetry pipeline in LocalStack, using AWS ECS as the compute engine. I cannot utilize the OTel resource detection for AWS ECS as the metadata endpoint is unavailable. This is the error I get from the collector:

```
failed to create "awsecscontainermetrics" receiver for data type "metrics": unable to detect task metadata endpoint: no valid endpoint for environment variable ECS_CONTAINER_METADATA_URI_V4: endpoint is empty
```

I'd be happy to contribute to the code base, but since AWS ECS is a LocalStack Pro service, I believe it's a closed-source code, so, not sure if I can help.
