### ISSUE TITLE
bug: S3 "folder" key has no ending slash

### ISSUE THREAD

**Issue by spring1915** [localstack/localstack#10714]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The results of listing S3 bucket objects don't contain a forward slash for "folder" objects. For instance, if a bucket contains "folders" abc, and def, then the result is
```
/abc/def
/abc/def/config.json
```

### Expected Behavior

The ending slash for `def`.

```
/abc/def/
/abc/def/config.json

```

### How are you starting LocalStack?

Custom (please describe below)

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

  Start localstack with docker or localstack cli.

```
s3 = boto3.client('s3',
              endpoint_url="<http://localhost.localstack.cloud:4566>",
                region_name='us-east-1',
                aws_access_key_id="test",
                aws_secret_access_key="test",)
  paginator = s3.get_paginator('list_objects_v2')
  operation_parameters = {'Bucket': bucket_name, 'Prefix': prefix}

  for page in paginator.paginate(**operation_parameters):
      for obj in page['Contents']:
          key = obj['Key']
```

### Environment

```markdown
- OS: Mac
- LocalStack: 3.3.0
```

**Comment by bentsku** [comment]
Hello @spring1915 and thanks for your report!

It's not clear what the issue is here. "Folder" objects are technically defined by yourself or the SDK, you would have to create them yourself.

Could you please share the commands done to create those particular folder keys? We should have pretty good parity with keys finishing with `/` or not. 

I believe that if you create a key named `/abc/def/`, then the call to `ListObjectsV2` should return `/abc/def/`. 
The report does not share how those keys are created.

Thanks!

**Comment by spring1915** [comment]
Thanks @bentsku . I used the "Create Folder" button of Localstack Desktop to create a new folder.
