### ISSUE TITLE
Lambda Kinesis EventSourceMapping filters match if any record in the batch matches 

### ISSUE THREAD

**Issue by freddieforsythfs** [localstack/localstack#10716]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When the lambda kinesis event source mapping has a filter pattern applied, all records in the batch are delivered to the Lambda if a single message from the batch matches the filter condition.

Note this is a bug here (it should be `filteredRecords`)
https://github.com/localstack/localstack/blob/2cd0ef6510ca8ef565ab652888f84f51eb1b8776/localstack/services/lambda_/event_source_listeners/stream_event_source_listener.py#L242  

### Expected Behavior

Only filtered records from the batch are delivered to the lambda.

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

Start LocalStack
Create a Lambda
Create a Kinesis Stream
Create an Event Source Mapping between the Lambda and the Kinesis with a filter in the JSON path 
Publish 3 events, only one of which has the JSON path associated with the filter
All events are delivered to the Lambda

### Environment

```markdown
- OS:
- LocalStack:
```

**Comment by joe4dev** [comment]
Thank you for sharing this issue including a concrete pointer to the bug 🐛 

We are actively working on improving Lambda Event Source Mapping 📈, also based on your feedback 🙇  

@freddieforsythfs Does our new `LAMBDA_EVENT_SOURCE_MAPPING=v2` implementation resolve this issue?

We just released LocalStack 3.7.0 🚀 today with a new implementation for Lambda Event Source Mappings: https://blog.localstack.cloud/2024-08-29-localstack-release-v-3-7-0/#new-lambda-event-source-mapping-implementation

LocalStack now supports a new implementation for [Lambda Event Source Mapping](https://docs.aws.amazon.com/lambda/latest/dg/invocation-eventsourcemapping.html) (ESM) with improved reliability, performance, and AWS parity.
You can use the `LAMBDA_EVENT_SOURCE_MAPPING=v2` configuration variable to use the new ESM implementation.
The ESM v2 implementation is also compatible with the Java-based event pattern rule engine (`EVENT_RULE_ENGINE=java`).
However, the new ESM implementation is still in **preview** and may not support all features.

The improvements over ESM v1 include:

- Improved reliability through internal retries and separation of concern such that single exceptions or timeouts don't affect other event source mappings.
- Improved performance by enabling concurrent event source mappings rather than having a single thread handling everything.
- Improved AWS parity, for example, related to filtering and SQS polling.

The limitations compared to ESM v1 include:

- Lambda Failure Destinations do not yet support FIFO SQS queues and SNS topics.
- Lambda Failure Destination Messages do not yet match the AWS structure, using a `context` similar to EventBridge Pipes instead of `requestContext` and `responseContext`.
- Partial Batch Responses using `FunctionResponseTypes` are not yet fully supported.
- Managed Streaming for Apache Kafka (MSK) event source is not yet supported.
- ESM Lifecycle State Updates only provide basic support for state updates, such as no failure states, and `LastProcessingResult` is not consistently updated.
- Persistence is not yet supported.

The limitations compared to AWS include:
- Lambda Success Destinations are not supported.
- Only very basic validations are performed upon creating and updating ESM.
- Streaming Pollers for Kinesis and DynamoDB do not implement features like:
  - `BisectBatchOnFunctionError`
  - `MaximumBatchingWindowInSeconds`
  - `ParallelizationFactor`
  - `ScalingConfig`
  - `TumblingWindowInSeconds`.
