### ISSUE TITLE
enhancement request: Lambda container can join multiple docker networks

### ISSUE THREAD

**Issue by abhinav-enboarder** [localstack/localstack#10727]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Enhancement description

When creating a lambda function one should be able to specify multiple docker networks to join.

**Comment by dfangl** [comment]
Hi @abhinav-enboarder !
You can already specify multiple networks using the `LAMBDA_DOCKER_NETWORK` variable. Please use the following format: `LAMBDA_DOCKER_NETWORK=network1,network2`. The networks are comma separated without spaces.

Please note that the LocalStack network absolutely has to be part of the list, otherwise lambda will not work anymore, ideally put as first network in the list.

I hope this can resolve your issue!

**Comment by abhinav-enboarder** [comment]
Thanks for your response. It wasn't clear from the docs that this var is a list and not a string. This helped me!
