### ISSUE TITLE
feature request: Adds the ability to accept SQS requests using the AWS JSON protocol within LocalStack.

### ISSUE THREAD

**Issue by intptr-t** [localstack/localstack#10821]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

Adds the ability to accept SQS requests using the AWS JSON protocol within LocalStack.

### Current issues

We get a protocol error when I make API requests to SQS on LocalStack using the latest AWS SDK for JavaScript v3 or boto3.
According to the [Amazon SQS AWS JSON protocol FAQs](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-json-faqs.html) in Notes, it can be reproduced using boto3 >=1.28.82, botocore>=1.31.82, and >=v3.447.0 in JavaScript v3.

## Example for JavaScript

**Example Node.js code**

```javascript
const { SQSClient, ListQueuesCommand } = require("@aws-sdk/client-sqs");

const sqs = new SQSClient({endpoint: "http://localhost:4566", credentials: { accessKeyId: "foo", secretAccessKey: "bar", }, region: "us-east-1" });
sqs.send(new ListQueuesCommand())
  .then((res) => { console.log (res)})
  .catch((err) => { console.log (err)});
```

**package.json**

```json
{
  "name": "node",
  "dependencies": {
    "@aws-sdk/client-sqs": "^3.576.0",
  }
}
```

**error output**

```
SyntaxError: Unexpected token '<', "<?xml vers"... is not valid JSON
  Deserialization error: to see the raw response, inspect the hidden field {error}.$response on this object.
    at JSON.parse (<anonymous>)
    at /Users/tomono/tmp/__tmp/node/node_modules/@aws-sdk/core/dist-cjs/submodules/protocols/index.js:112:19
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async parseJsonErrorBody (/Users/tomono/tmp/__tmp/node/node_modules/@aws-sdk/core/dist-cjs/submodules/protocols/index.js:125:17)
    at async de_CommandError (/Users/tomono/tmp/__tmp/node/node_modules/@aws-sdk/client-sqs/dist-cjs/index.js:1192:11)
    at async /Users/tomono/tmp/__tmp/node/node_modules/@smithy/middleware-serde/dist-cjs/index.js:35:20
    at async /Users/tomono/tmp/__tmp/node/node_modules/@smithy/core/dist-cjs/index.js:165:18
    at async /Users/tomono/tmp/__tmp/node/node_modules/@smithy/middleware-retry/dist-cjs/index.js:320:38
    at async /Users/tomono/tmp/__tmp/node/node_modules/@aws-sdk/middleware-logger/dist-cjs/index.js:34:22 {
  '$metadata': { attempts: 1, totalRetryDelay: 0 }
}
```

## Example Python

**Python code**

```python
import boto3

sqs = boto3.client(
    'sqs',
    region_name="us-east-1",
    endpoint_url="http://localhost:4566",
    aws_access_key_id="foo",
    aws_secret_access_key="bar",
)
sqs.list_queues()
```

**requirements.txt**

```txt
boto3==1.34.105
botocore==1.34.105
jmespath==1.0.1
python-dateutil==2.9.0.post0
s3transfer==0.10.1
six==1.16.0
urllib3==2.2.1
```

**error output**

```
Traceback (most recent call last):
  File "/Users/USERNAME/tmp/__tmp/python/test.py", line 10, in <module>
    sqs.list_queues()
  File "/Users/USERNAME/tmp/__tmp/python/venv/lib/python3.12/site-packages/botocore/client.py", line 565, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/USERNAME/tmp/__tmp/python/venv/lib/python3.12/site-packages/botocore/client.py", line 1021, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (500) when calling the ListQueues operation (reached max retries: 4): <?xml version='1.0' encoding='utf-8'?>
<ErrorResponse xmlns="http://queue.amazonaws.com/doc/2012-11-05/"><Error><Code>InternalError</Code><Message>exception while calling sqs with unknown operation: Operation detection failed. Missing Action in request for query-protocol service ServiceModel(sqs).</Message></Error><RequestId>4ad5e260-74e1-4cc1-9858-4dd9353ae37b</RequestId></ErrorResponse>
```

### Other Notes

**Amazon SQS AWS JSON protocol FAQs**

https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-json-faqs.html

**AWS JSON protocol is used by SQS by default**

If you check the `ListQueues` API reference, you will see that the `AWS JSON protocol` is the default (as of 2024-05-15).

https://docs.aws.amazon.com/ja_jp/AWSSimpleQueueService/latest/APIReference/API_ListQueues.html

**Comment by mbbush** [comment]
Without support for the AWS JSON protocol in localstack, I can't run my SQS tests using any AWS sdk version released after 
November 2023. As far as I can tell, the AWS SDK does not allow any configuration options to continue using the XML protocol, so my options are:
1. Don't upgrade the aws sdk, so I can't get bug fixes
2. Disable my localstack-based SQS tests, so I can't get fast, isolated feedback on bugs
3. Use different versions of the AWS SDK in my production and test code, so that the tests no longer give me confidence about what's happening in production

I really don't like any of those options.

**Comment by bentsku** [comment]
Hello and thanks for the report!

LocalStack should support the AWS JSON for SQS since version `3.1` (with #9710), with numerous improvements until today. 

Could you share which version of LocalSack are you using? Could you try with `3.6` and see if that solves your issue? If not, could you please share a snippet of the code that would fail against the current version? Thanks!

**Comment by alexrashed** [comment]
Hi @intptr-t and @mbbush!
Thanks, @intptr-t, for the great reproducer! Out of curiosity, I just used it to verify that this in fact just works as expected with the `latest` version of LocalStack:
```bash
$ node main.js
{
  '$metadata': {
    httpStatusCode: 200,
    requestId: 'e2702153-3aaa-404c-8c3e-e8e61c822e2e',
    extendedRequestId: undefined,
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0
  }
}
```
Just as @bentsku mentioned, the LocalStack supports content negotiation (JSON and XML) for SQS since `3.1.0`.
Are you sure you are using the latest version? Could you help us reproduce the issues you are having by sharing the configuration and the logs you are using when starting LocalStack?

**Comment by mbbush** [comment]
The cause of my issue was a stale cached image tagged as `latest` that I pulled down 11 months ago. Once I pulled the _actual_ latest image, JSON SQS requests worked without a problem, and with no additional configuration needed. Thanks for the quick response! As far as I'm concerned, this is resolved.

**Comment by intptr-t** [comment]
Thank you everyone for supporting us!
I solved this issue by pulling the latest image.
