### ISSUE TITLE
bug: S3 Presign URL returns incorrect URL (NoSuchBucket).

### ISSUE THREAD

**Issue by jacekgajek** [localstack/localstack#11000]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I create a bucket in `init.sh` with
```
aws --endpoint-url=http://localhost:4566 --region eu-central-1 s3api create-bucket --bucket xxx-tenant-resources-dev --create-bucket-configuration LocationConstraint=eu-central-1
```
In application code I create upload URL:
```
	suspend fun preparePresignedUploadUrl(key: String): String =
		s3Client.presignPutObject(PutObjectRequest {
			bucket = "xxx-tenant-resources-dev"
			this.key = key
		}, presignedUrlExpiration).url.toString()
```
This reponses with
```
url = http://xxx-tenant-resources-dev.localhost:4566/tenant-resources/workspace-it-20240611-123627/workspace/4fce6ebc-3208-4363-80e3-57acc21607ae/icon/icon?x-id=PutObject&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=awsSecretAccessKey%2F20240611%2Feu-central-1%2Fs3%2Faws4_request&X-Amz-Date=20240611T103630Z&X-Amz-Expires=360000&X-Amz-SignedHeaders=host&X-Amz-Signature=...
```
In my integration test, I send my file to this bucket
```
		val putResponse = client.put(url) {
			contentType(ContentType.Application.Json)
			setBody("""{ "my": "json" }""")
			authenticate()
		}
```
And got response:
```
<?xml version='1.0' encoding='utf-8'?>
<Error><Code>NoSuchBucket</Code><Message>The specified bucket does not exist</Message><RequestId>e06e7b3f-79a2-4e9c-a930-ddddae86e4c4</RequestId><BucketName>tenant-resources</BucketName></Error>
```

As you can see, it thinks that `tenant-resources` is a bucket name while it's part of a path, and a bucket name is in the url `http://xxx-tenant-resources-dev.localhost:4566`.

So, either fix the bucket API behavior to the same as AWS, which takes a bucket name from URL or modify Presign API so it returns an URL which works.

Currently it is incosistent.

### Expected Behavior

This should behave as AWS.

If a presignPutObject returns with an URL X, then PUT request to that url X uploads an item.

### How are you starting LocalStack?

With a `docker run` command

### Steps To Reproduce

I start localstack with maven,  `localstack/localstack:3.4`

I think presigning PutObject requests is not possible via AWS CLI so to reproduce you need API. See the kotlin code above which uses kotlin aws sdk. It works on real AWS.

### Environment

```markdown
- OS: Ubuntu 22.04
- LocalStack version: 3.4
```

### Anything else?

Similar, if not exactly the same as https://github.com/localstack/localstack/issues/7972 which was dissmissed with a response saying that it is a correct behavior, which is not true at all. The API is incosistent.

**Comment by bentsku** [comment]
Hello and thanks for your report,

Here is the documentation about path style and virtual hosted request: https://docs.localstack.cloud/user-guide/aws/s3/#path-style-and-virtual-hosted-style-requests

Regarding this report, I'm not sure I understand:
> So, either fix the bucket API behavior to the same as AWS, which takes a bucket name from URL or modify Presign API so it returns an URL which works.
>
> Currently it is incosistent.

Calling `s3Client.presignPutObject` is **purely a client side object**, your client does not send anything to LocalStack, and LocalStack does not return anything to you. Your client will automatically generate the presigned URL. The client simply takes the endpoint you've configured, and add the query string parameters needed for S3 to understand your request. LocalStack does not return any endpoint to you, which is why it doesn't understand your request, as it's not following the right format. 
You need to either configure your `s3Client` to use an endpoint compatible with the `virtual host styled request` or configure path style, like the documentation above specifies. 

From the other issue, I've linked this table: https://docs.aws.amazon.com/sdkref/latest/guide/feature-ss-endpoints.html#ss-endpoints-envar

And it seems Kotlin is compatible with the `AWS_ENDPOINT_URL`, which means you can modify the behavior of your tests without modifying the code. 

> aws.endpointUrl<ServiceName> - JVM system property: Java/Kotlin only

Which means you can have specific configuration for your tests (I believe you must configure the endpoint somehow to `localhost` currently already?) with `aws.endpointUrlS3` set to `s3.localhost.localstack.cloud:4566` so that when running hour tests against LocalStack, it would use the right endpoint to create your pre-signed URL.

To answer the question about LocalStack emulating AWS, sometimes we cannot control the behavior of the SDK, so some configuration is needed. We're trying to make it as easy as possible for you, and AWS is doing progress as well with their SDK to transparently configure them, like the above.

**Comment by jacekgajek** [comment]
Thank you for a promt and detailed response. After consulting the linked docs I managed to work around this with setting 

```
private val s3Client by lazy {
	S3Client {
		region = configuration[ConfigurationSpec.region]
		credentialsProvider = awsCredentialsProvider
		endpointUrl = awsEndpointUrl
		forcePathStyle = configuration[AwsSpec.S3Spec.forcePathStyle] // true
	}
}
```
The critical part here is setting 
```
forcePathStyle=true
```
 in the SDK client configuration.

**Comment by bentsku** [comment]
Great, I'm glad we could get it solved! I'm sorry about the need to change the configuration of the client, like you said, everything should be as transparent as possible. We're working on that, and are very appreciative of the changes from the AWS SDK team too to enable setting different endpoints. 

Thanks also for the explanation! We work to add a documentation page for Kotlin so that it would be easier to find. 

Thanks again for the feedback 🙏

**Comment by jacekgajek** [comment]
> We work to add a documentation page for Kotlin so that it would be easier to find.

kotlin uses equivalent SDK as Java, so it's rather a general issue with a JVM client.

Java:
AWS docs: https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/examples-s3.html
API docs: https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/s3/S3BaseClientBuilder.html

kotlin:
AWS docs: https://docs.aws.amazon.com/sdk-for-kotlin/latest/developer-guide/config-endpoint.html
API docs: https://sdk.amazonaws.com/kotlin/api/latest/s3/aws.sdk.kotlin.services.s3.endpoints/-s3-endpoint-parameters/index.html

**Comment by jacekgajek** [comment]
Also apparently javascript also has it

https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html
https://stackoverflow.com/questions/20305877/how-to-configure-aws-s3-sdk-for-node-js-to-be-used-with-localhost

So maybe it's a general option in many (if not all) SDKs.

**Comment by bentsku** [comment]
Nice, thanks a lot for the added context! Yes, `pathStyle` configuration should be global to almost every SDK, just in different format almost every time. We'll make sure to add a note for the JVM clients. 

Can we consider the issue closed?

**Comment by jacekgajek** [comment]
Yes, it worked. Thank you for your support.

**Comment by jacekgajek** [comment]
I've noticed that on the .NET guide:  https://docs.localstack.cloud/user-guide/integrations/sdks/dotnet/ 

you already suggest to set `ForcePathStyle` to true.
