### ISSUE TITLE
bug: invalid AWS region name for s3

### ISSUE THREAD

**Issue by afreisinger** [localstack/localstack#11151]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am using  tflocal with my localstack S3 instance but the console show me the follow error:

ValueError: 'aws-global' is not a valid AWS region name for s3
2024-07-07T20:50:05.506  INFO --- [et.reactor-1] localstack.request.aws     : AWS s3.HeadBucket => 500 (InternalError)

### How are you starting LocalStack?

With the `localstack` script

### Steps To Reproduce

localstack start -d
tflocal init
tflocal plan
tflocal apply

### Environment

```markdown
- OS:osx
- LocalStack:
  LocalStack version:3.5.0 Profile default
```

### Anything else?

provider.tf snnipet
```sh
provider "aws" {
  access_key                  = "test"
  secret_key                  = "test"
  skip_credentials_validation = true
  skip_metadata_api_check     = true
  alias                       = "main"
  region                      = "us-east-1"
  endpoints {
    acm                      = "http://localhost:4566"
    amplify                  = "http://localhost:4566"
    apigateway               = "http://localhost:4566"
    apigatewayv2             = "http://localhost:4566"
    appautoscaling           = "http://localhost:4566"
    appconfig                = "http://localhost:4566"
    appflow                  = "http://localhost:4566"
    appsync                  = "http://localhost:4566"
    athena                   = "http://localhost:4566"
    autoscaling              = "http://localhost:4566"
    s3                       = "http://s3.localhost.localstack.cloud:4566"
}
```
main.tf
```sh
resource "aws_s3_bucket" "website" {
  provider = aws.main
  bucket        = local.website_bucket_name
  force_destroy = var.website_bucket_force_destroy
  
  tags = merge({
    Name = "${var.name_prefix}-website"
  }, var.tags)
}
```

**Comment by lakkeger** [comment]
Hi @afreisinger,
Thanks for reaching out.
This is a known "bug" introduced by the Terraform `aws` provider `>5.55.0` and it seems it won't go away until `>6.0.0` as it's part of their aws-go-sdk-v2 migration to fall back on a pseudo region called `aws-global`.
As a temporary work around, please remove any `.` form your s3 bucket names and all should behave as expected.
You can find the comment addressing the issue here: https://github.com/localstack/terraform-local/pull/57#issuecomment-2188342525
