### ISSUE TITLE
Prospecting LocalStack before using - Question about Public URLS

### ISSUE THREAD

**Issue by mdere-unbound** [localstack/localstack#1117]
Hello! Can Localstack actually allow me to interface with a public url to the S3 objects I create? I.e in my case images.

If so does it by default follow the default paradigm aws follow?

{region}.namespace.{bucket}/{key} ?

Thanks in advance!

**Comment by whummer** [comment]
Hi @mdere-unbound . Just to clarify - you're planning to deploy LocalStack into an environment that is accessible via a public URL where you have control over the DNS setup, and hence you can enable the DNS settings to forward any requests to `{bucket}.{region}.namespace` (e.g., `mybucket.us-east-1.mydomain.com`) to the S3 service within LocalStack, right?

In theory, afaik that should work. However, since most users generally deploy LocalStack on `localhost`, we usually use the path style addressing that S3 supports: `localhost:{port}/{bucket}/{key}`. But it would definitely be worth a try to test a deployment like the one you're proposing - if there are any issues, they should be fairly easy to fix.
