### ISSUE TITLE
Trojan:win32 Bearfoos versão 3.6.0

### ISSUE THREAD

**Issue by lulukamagaiver** [localstack/localstack#11274]
Ao baixar a versão 3.6.0 o windows defender está detenctando o *.exe com virus. Segue imagem abaixo da mensagem e da versão do windows:
![TROJAN_LOCALSTACK](https://github.com/user-attachments/assets/c4547fe3-27bc-4575-bc80-ea97ad0f3cdd)
![TROJAN_LOCALSTACK_1](https://github.com/user-attachments/assets/679206a7-82ce-457e-b729-4794bcd8ef2b)

**Comment by MarcelStranak** [comment]
Hi @lulukamagaiver,

Thank you for the report.

The issue of false positives arises from the method used to package the binary CLI, as mentioned in [PyInstaller GitHub issue 5854](https://github.com/pyinstaller/pyinstaller/issues/5854).
In short, malware creators utilize the same packaging software for their malicious programs. These are reported, and antivirus software learns to recognize the signatures within the packaging software. Consequently, benign binaries are mistakenly identified as threats because they contain the same signatures.

We have already reported the false positive to [Microsoft Defender Antivirus](https://www.microsoft.com/en-us/wdsi/filesubmission).
