### ISSUE TITLE
bug: Terraform deployment for Event Source Mapping failing with ResourceNotFoundException

### ISSUE THREAD

**Issue by scuray** [localstack/localstack#11739]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After the last update (Version 3.8.2) All the lambdas called from a SQS returns this error "ResourceNotFoundException: Function not found: arn:aws:lambda:us-east-1:000000000000:function:event-source-mapping" 

### Expected Behavior

Create lambdas that can be called from an SQS

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)
compose file: 
services:
  localstack:
    container_name: '${LOCALSTACK_DOCKER_NAME:-localstack-main}'
    image: localstack/localstack-pro # required for Pro
    ports:
      - '4566:4566' # LocalStack Gateway
      - '4510-4559:4510-4559' # external services port range
      - '443:443' # LocalStack HTTPS Gateway (Pro)
      - '3306:3306' # LocalStack RDS
    environment:
      # Activate LocalStack Pro: https://docs.localstack.cloud/getting-started/auth-token/
      - LOCALSTACK_AUTH_TOKEN=${LOCALSTACK_AUTH_TOKEN:?} # required for Pro
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - DEBUG=${DEBUG:-1}
      - PERSISTENCE=${PERSISTENCE:-1}
      - GATEWAY_LISTEN=0.0.0.0:4566
      - EXTRA_CORS_ALLOWED_ORIGINS=*
      - DNS_SERVER=1.1.1.1
      - SKIP_SSL_CERT_DOWNLOAD=1
    volumes:
      - '${LOCALSTACK_VOLUME_DIR:-./localstack}:/var/lib/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

resource "aws_lambda_function" "lambda_function" {
  filename         = "${var.lambda_build_path}/${var.lambda_function_name}.zip"
  handler          = "index.handler"
  runtime          = "nodejs20.x"
  function_name    = var.lambda_function_name
  role             = aws_iam_role.iam_for_lambda_function.arn
  timeout          = 60
  source_code_hash = data.archive_file.lambda_function_zip.output_base64sha256
  memory_size      = var.memory_size
  depends_on = [
    data.archive_file.lambda_function_zip
  ]

  environment {
    variables = var.lambda_env_vars
  }
  tracing_config {
    mode = "Active" # Enable AWS X-Ray
  }
  # Enable Lambda Insights by referencing the layer ARN for your region
  layers = [var.lambda_insights_layer_arn]
}

resource "aws_lambda_event_source_mapping" "lambda_sqs_trigger" {
  event_source_arn = var.sqs_arn
  function_name    = aws_lambda_function.lambda_function.arn
  enabled          = true
  batch_size       = 10

  depends_on = [
    aws_lambda_function.lambda_function
  ]
}

### Environment

```markdown
- OS: MacOS Sonoma 14.7 (23H124) 
- LocalStack: 
  LocalStack version: 3.8.2
```

### Anything else?

As a workaround I'm using the image version 3.7.2

**Comment by joe4dev** [comment]
Hi @scuray 👋 

Thank you for reporting this regression  with our [new default implementation for Lambda Event Source Mapping](https://blog.localstack.cloud/localstack-release-v-3-8-0/#new-default-lambda-event-source-mapping-implementation). The issue is likely related to the new tagging support recently added to Lambda Event Source mappings (see https://aws.amazon.com/about-aws/whats-new/2024/09/aws-lambda-tagging-event-source-mappings-code-signing-config-resources/). It looks like the same issue reported in our Slack community #help channel [here](https://localstack-community.slack.com/archives/CMAFN2KSP/p1729667120000629?thread_ts=1729608989.133849&cid=CMAFN2KSP).

We are working on a solution and will let you know here once the fix is shipped 🚀 

/cc @gregfurman
