### ISSUE TITLE
Latest image is using all the memory in CI and hangs

### ISSUE THREAD

**Issue by brejnko** [localstack/localstack#1186]
I had to revert to localstack/localstack:0.9.0, the latest from Docker Hub is eating all of my RAM in CI and hangs.

Couldn't debug more, I have no access to CI logs, but as soon as I've changed from latest to 0.9.0 the CI pipeline is not hanging anymore.

Anyone else having the same problem?

**Comment by whummer** [comment]
Thanks for reporting @brejnko . This should be fixed in the latest version, which includes a couple of performance fixes.

Please always make sure to customize the `SERVICES` environment variable to start only the services you require. Especially Elasticsearch and a few other APIs are very memory hungry, and the performance can be optimized if this service is left out.
