### ISSUE TITLE
JUnit random port test issue.

### ISSUE THREAD

**Issue by twolak2003** [localstack/localstack#1198]
Hi, 
I am seeing the following issue.  I am running a test with the following annotation:
`@RunWith(LocalstackDockerTestRunner.class)
@LocalstackDockerProperties(randomizePorts = false, services = { "sqs:1120", "sns:232"})`
When the test start I am tailing the docker logs
`docker logs --tail all 67177a3832a2
...
Starting mock SQS (http port 1120)...
Starting mock SNS (http port 232)...
2019-03-15T20:30:34:WARNING:werkzeug:  * Debugger is active!
2019-03-15T20:30:34:INFO:werkzeug:  * Debugger PIN: 106-165-007
Waiting for all LocalStack services to be ready
Ready.
`
I am seeing the mock being started at the ports as as expected per the properties.  However the port forwarding does not account of for the ports of the services:
`PORTS                                                       
  4584-4593/tcp, 0.0.0.0:4567-4583->4567-4583/tcp, 8080/tcp `
So while the service starts at the specified port, the port biding  is not.

is this a bug?  Or is there a way to change the default port biding for selected services at run time?  No
Thanks

**Comment by akervern** [comment]
Hello!

On the same topics, it seems that random ports and new (?) services are not correctly taken into account by the Docker Junit Runner. The Docker container defines them right but seems not correctly bound in the Java code.

For instance, I figured out that in `cloud.localstack.docker.Container#LOCALSTACK_PORTS`, the port list is fixed and doesn't reflect the whole service list as it should be something like `4567-4593`, in order to expose the complete list of services. So, I'm wondering if it is on purpose.

As well, as the initialization of services ports in `cloud.localstack.docker.LocalstackDocker#loadServiceToPortMap` which read the file `/opt/code/localstack/.venv/lib/python2.7/site-packages/localstack_client/config.py` that doesn't seem to be templated and still contains default ports and not the ones configured with the `cloud.localstack.docker.annotation.LocalstackDockerProperties` annotation as @twolak2003 highlighted.

**Comment by whummer** [comment]
Thanks for reporting @twolak2003 @akervern . This should be fixed in #1843 - a test has been added to the pull request. This will be available in the next Maven release of the Java libs (happening soon). Thanks
