### ISSUE TITLE
Feature request: "ready" endpoint

### ISSUE THREAD

**Issue by austinbutler** [localstack/localstack#1256]
I see a lot of issues here on Github either definitely or very likely related to startup timing. For many use cases I think it may be useful to just have a single `/ready` endpoint that returns 200 only when all requested services are up and ready. Until then maybe it refuses connections or returns something like a 412 or other 4xx or 5xx code. Or it could even just return `{"ready": false}` and `{"ready": true}`.

The current status quo seems to be that you are supposed to either parse the logs for "Ready" or hit each port for each service you are waiting for and retry until it's up, but from what I've found if you start hitting the port too fast too early `localstack` itself will start returning 502 errors from the proxy, which makes it seem like there are startup issues even though it eventually works. Then even once the port is up, the _service_ might not actually be ready or usable yet (may take a second or two).

**Comment by adamdavis40208** [comment]
We've actually been discussing better approaches to this at work. This would be super useful

**Comment by evemorgen** [comment]
I'd be willing to work on this, is it still available?

**Comment by whummer** [comment]
Hi @evemorgen , yes please feel free to pick up this item. 🎉 I'd be happy to provide some guidance, if needed. Thanks!

**Comment by bhatsarthak** [comment]
Hi @evemorgen ,
Can I work on this issue? I have limited experience with this project. Appreciate any help here.

**Comment by evemorgen** [comment]
Sure thing @whummer, please take it away :) I gave it a try long time ago but hadn't had much time to finish. As far as I remember, a good entrypoint would be somewhere around `start_infra` function [here](https://github.com/localstack/localstack/blob/master/localstack/services/infra.py#L338). Good luck!

**Comment by bhatsarthak** [comment]
Thanks @evemorgen . I did spend some time on this package and need some inputs on the ask here. 
1. Can you tell me the URL path for this /ready API.  Should this be something like 
http://localhost/4586/ready (Cloudwatch endpoint)--> Curl on this URL should return READY if cloudwatch is ready. Or this should say ready only if all microservices are ready ?

2. When I run "make infra" I see there are bunch of microservices that get triggered. Is there a server for localstack which orchestrates the spin up of individual AWS services.

**Comment by evemorgen** [comment]
ad 1. I'm not associated with localstack by any means and it would be best for maintainers to decide on the URL scheme. However, I'd imagine it to be a top-level endpoint that would return HTTP code 200 only if *all* underlying AWS thingies were ready (so that `curl http://localhost:1234/ready` would return `HTTP 200 OK` if it's ready and `HTTP 503 Service Unavailable` if it's not) - as mentioned in the original issue. Right now, you can see that state [being logged here](https://github.com/localstack/localstack/blob/7170414144a20a8e09501fef008088596c6e6a3b/localstack/services/infra.py#L394), but nothing else happens when the stack is ready.

ad 2. As far as I can see, there's a `start_infra` method [here](https://github.com/localstack/localstack/blob/7170414144a20a8e09501fef008088596c6e6a3b/localstack/services/infra.py#L338) spinning all things up. There's also `web` container that can be explicitly run with `make web` command. This container provides a dashboard with an overview of deployed resources. So that would be a central place where all information about underlying resources is gathered (I might be completely wrong with that). There is also a disclaimer there saying it _is outdated and may be removed in a future version_.

**Comment by whummer** [comment]
Thanks again for chiming in @bhatsarthak @evemorgen . Can you please refer to the documentation of the `/health` endpoint that is now available: https://github.com/localstack/localstack#service-health-checks Closing this issue for now, but please report here or open a follow-up issue if the current functionality does not satisfy your use case. Thanks!

**Comment by DarylLyonsLF** [comment]
@whummer FYI this link is dead - https://github.com/localstack/localstack#service-health-checks. Is there any updated documentation for this?
