### ISSUE TITLE
use localstack to test AWS Organizations

### ISSUE THREAD

**Issue by Ghilteras** [localstack/localstack#1268]
Is it possible to use Localstack to test the AWS Ogranizations API?

https://docs.aws.amazon.com/cli/latest/reference/organizations/index.html

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-94) by [Unito](https://www.unito.io/learn-more)

**Comment by Ghilteras** [comment]
anybody?

**Comment by Ghilteras** [comment]
@whummer is this in your roadmap?

**Comment by Ghilteras** [comment]
Hi, is this being considered in Localstack Pro/Enterprise ?

**Comment by mdaniel** [comment]
> Is it possible to use Localstack to test the AWS Ogranizations API?
> 
> https://docs.aws.amazon.com/cli/latest/reference/organizations/index.html

Yes, it just requires starting a copy of [the moto server](https://github.com/spulec/moto/blob/1.3.14/moto/server.py) on [the organization port](https://github.com/localstack/localstack-python-client/blob/78cf752a6bef79fb2c52fb8ad3a07df74b1750a3/localstack_client/config.py#L66); the [`/docker-entrypoint-initaws.d` mechanism](https://github.com/localstack/localstack/blob/v0.11.3/bin/docker-entrypoint.sh#L27) makes that convenient to do without even modifying the published docker image:

```console
$ mkdir initaws.d
$ cat >initaws.d/start_orgs.sh<<"SH"
## this file is sourced, so no need to even monkey with its permissions or shebang
nohup $MAVEN_CONFIG/.venv/bin/moto_server --host 0.0.0.0 --port 4615 &
echo "pausing for moto to warm up ..." >&2
sleep 2
## and here you could do org creation, population, sample data, that kind of thing
SH
$ docker run -d --name lstack -v $PWD/initaws.d:/docker-entrypoint-initaws.d -p 4566:4566 localstack/localstack:0.11.3
$ sleep 10
## or you can also docker exec lstack awslocal organizations ...
## but doing it this way shows that it works from outside, too
$ AWS_ACCESS_KEY_ID=yup AWS_SECRET_ACCESS_KEY=for-sure \
    aws --endpoint=http://localhost:4566 organizations create-organization --feature-set ALL
```
the next trick toward answering your question is to examine how much of that API [is implemented by moto](https://github.com/spulec/moto/blob/1.3.14/moto/organizations/responses.py#L23) since localstack for the most part is just delegating to it.

However, even if you find that the installed moto isn't sufficient, you can fix the parts of moto you require, then install your patched moto into a separate virtualenv, and start **that** moto on the organization port, and you should once again be off to the races.

**Comment by timoguin** [comment]
@macnev2013 Is this feature actually available in the pro version? I've been going over the docs and can't find any mention of Organizations being supported. I see @mdaniel's helpful comment detailing how to do this manually with moto, but I'd prefer to avoid that extra setup if possible.

**Comment by thrau** [comment]
This feature is available in LocalStack pro. Should you have problems with the pro version, please let us know in Slack, thanks!

**Comment by estebane-frb** [comment]
@thrau should the features page be updated to indicate that Organizations is included in Pro? https://localstack.cloud/features/
