### ISSUE TITLE
Got permission denied while trying to connect to the Docker daemon socket in version > 0.9.1

### ISSUE THREAD

**Issue by blaart** [localstack/localstack#1306]
Hi, when I use the latest version I get an error when calling a Lambda. 

I get this error:
Lambda process returned error status code: 1. Output:
awssvc           | 2019-05-10T22:23:19.822966331Z Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.29/containers/create: dial unix /var/run/docker.sock: connect: permission denied
awssvc           | 2019-05-10T22:23:19.822969899Z must specify at least one container source

I'am using the Lambda in a docker. 

You can find my setup here: https://github.com/blaart/stream-my-changes
After forcing to use the 0.9.1 version all works fine again.

**Comment by g-io** [comment]
I had a very similar issue. The scenario is starting localstack as a docker container, and running a Lambda with docker executor (from inside the localstack container).
The localstack processes inside localstack container are run under user localstack. This user is trying to access the shared /var/run/docker.sock, which is usually possible to root and members of the group docker on the host.
In my case: 
```
    grep docker /etc/group
    docker:x:991:bamboo
```
The owner and group ids of shared volumes are the same on host and in the localstack container, so the docker socket is belonging to group 991, in my case. This group is not available in the container, let alone that localstack is a member.
I am in the comfortable situation that I'm starting localstack from a python script (with the help of the excellent [docker](https://docker-py.readthedocs.io/en/stable/index.html) module), so I wrote a quick workaround to make sure that the localstack container is started as a member of my host's docker group:
```python
        # container must run with docker group membership to be able
        # to access /var/run/docker.sock from inside container for DinD
        import grp
        try:
            docker_gid = grp.getgrnam("docker").gr_gid
        except KeyError:
            docker_run_args = {}
        else:
            docker_run_args = {"group_add": [docker_gid]}
```
The underlying issue is so basic however that it seems to me that localstack should solve it and not leave it to the user to come up with a hack.

**Comment by whummer** [comment]
Thanks for reporting @blaart @g-io - can you please check if the problem persists with the `latest` version of the Docker image?

**Comment by g-io** [comment]
Thanks @whummer for taking action so fast. I have not tested the container after the latest patch, but from the diff I'd say that it both fixes the issue and that this is a dangerous fix.
The docker.sock in the localstack container is mounted (identical to) the docker.sock on the host machine. The patch opens the socket to the world, making it possible for anyone with access to the host system to execute arbitrary commands with root permission.

**Comment by blaart** [comment]
Thanks @whummer, the solution in the latest version works indeed. Thanks! Please take a look at the comment of g-io.

**Comment by whummer** [comment]
Thanks for confirming @blaart . Agree with the concerns from @g-io - the [last PR](https://github.com/localstack/localstack/pull/1310) reverted the change and avoids modifying `docker.sock`. Closing this issue - please reopen if the problem persists. Thanks
