### ISSUE TITLE
LOCALSTACK_HOSTNAME - Use for Testing Only

### ISSUE THREAD

**Issue by kevinswarner** [localstack/localstack#1356]
I ran into the issue of accessing S3 from a Lambda running in Localstack. I understand that you need to use the read-only environment variable LOCALSTACK_HOSTNAME to build the endpoint to S3 from within your Lambda.

If I do that, then my Lambdas now depend on that environment variable, which means when I deploy to AWS for production or staging or whatever, I need to set that environment somehow for that context.

Is there a suggested approach that allows us not to have to reference or depend on that environment variable from within the Lambdas, while still being able to test locally using Localstack?

Thanks.

**Comment by whummer** [comment]
Hi @kevinswarner , I'm afraid there is no easy answer to that question. To make your Lambdas testable using LocalStack, the S3 SDK somehow needs to be instructed to talk to the local endpoints instead of AWS directly.

This configuration can be encapsulated in some central config file, but this very much depends on your project setup.

There may also be other methods to instrument or monkey-patch the SDK with the local endpoints, but this is out of scope for this projects at this point. I'd be curious to hear proposals from you and other community members, though, to work out a generic solution that can be reused across projects. 

Which language are you using for your Lambdas?

**Comment by kevinswarner** [comment]
Thanks @whummer. I am using Node. I actually have a more pressing issue with Localstack. Can you take a look at the issue https://github.com/localstack/localstack/issues/1359? Thank you!

**Comment by whummer** [comment]
Thanks @kevinswarner - continuing the discussion on this issue: #1359
