### ISSUE TITLE
Localstack docker returns 404 when S3 invokes lambda

### ISSUE THREAD

**Issue by PragyaU** [localstack/localstack#1393]
I am running local stack in docker using commnad:
docker-compose up

docker-compose.yml :
```
version: '3.2'
services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack_dev
    hostname: localstack
    ports:
      - '4563-4593:4563-4593'
      - '8055:8080'
    environment:
      - SERVICES=s3,lambda,secretsmanager,cloudwatch, cloudwatchlogs, iam
      - DEBUG=1
      - LAMBDA_EXECUTOR=docker
    volumes:
      - './.localstack:/tmp/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'
```
Response in docker logs:

As soon as S3 triggers a lambda function-

![image](https://user-images.githubusercontent.com/52142445/59984959-5c0a8000-95fc-11e9-845d-18c45eedbbef.png)

**Comment by whummer** [comment]
Thanks for reporting @PragyaU . This should have been fixed in the meantime. Can you please give it another try with the `latest` version of the Docker image? If the problem persists, then please help us reproduce it by providing a small, self-contained example with the exact sequence of API calls that causes this issue. Thanks!
