### ISSUE TITLE
Single-service in docker-compose an anti-pattern?

### ISSUE THREAD

**Issue by adieuadieu** [localstack/localstack#140]
Thank you for all the effort that's gone into this project!

Is there a reason for there being only a single service defined in the docker-compose.yml file, rather than one service for each AWS service simulated by/available in localstack?

What I'd like to be able to do is use a made-up AWS region, e.g. `local` and add an entry in my `hosts` file pointing `{service}.local.amazonaws.com` to the corresponding `{service}`'s docker container, each on port 80 or 443 as that's the port you'd find the APIs for each service in the production/real AWS API. The reason I want this is so that I can use [Serverless-framework](https://github.com/serverless/serverless) and tell it to use `--region local` when deploying.

The alternatives are:
1. create an additional docker-compose service which contains nginx that does the necessary proxying to each localstack service, or
2. Use something like [this plugin](https://github.com/temyers/serverless-localstack) for Serverless that does all the mapping for each service:port in localstack.

Both seem like the wrong place/hack-y. I can raise a PR (over on bitbucket..) if this is something the community thinks makes sense to do.

**Comment by whummer** [comment]
That's a great proposal, I generally like the idea of properly splitting up the services into separate containers. I have two observations at this point:

1) Currently there are still a few hard-wired (in-memory) calls that we would have to eliminate before separating the services. In some cases we can simply use the AWS APIs of the respective services, but in some cases we'd have to create new backdoor API methods for internal calls. Examples:
   * DynamoDB triggers a Lambda [using an in-memory call](https://github.com/atlassian/localstack/blob/master/localstack/mock/proxy/dynamodb_listener.py#L100-L108) when a table is updated. We can probably simply re-use the Lambda `Invoke` API method for that purpose (although we need to analyze if that could have undesired side-effects)
   * DynamoDB forwards events to DynamoDB Streams [using an in-memory call](https://github.com/atlassian/localstack/blob/master/localstack/mock/proxy/dynamodb_listener.py#L111-L112). In this case we would have to create a backdoor API method in DynamoDB Streams to forward the events (because the [public API](http://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_Operations_Amazon_DynamoDB_Streams.html) does not provide any such functionality)

2) When making the required changes for multi-container docker compose, we should ensure that starting LocalStack in a single Docker container is still fully supported (and runs out of the box, without any changes to the `hosts` file etc).

**Comment by whummer** [comment]
Closing this issue as outdated - for housekeeping reasons. The scenario described above can be achieved by defining a single container in docker-compose for each of the services, and defining the environment variable `SERVICES=<service_name>:80` for each individual service.

Also, note that support for Serverless has been improved - see here: https://github.com/localstack/serverless-localstack

Also, this issue is related to the discussion here: https://github.com/localstack/localstack/issues/1156
