### ISSUE TITLE
ARN patterns mismatch

### ISSUE THREAD

**Issue by tarastriska** [localstack/localstack#1414]
Hi guys,

I am now trying to use localstack for SNS and SQS. I am preparing scripts for creating topics/queues/subscriptions
I want to use env variables to prepare ARNs and have an issue that arns for SNS and SQS are totally different.

arn:aws:sqs:elasticmq:000000000000:testqueue - queue example
arn:aws:sns:us-east-1:123456789012:topic - topic example

topic looks fine.
but how can I have queue arn like
arn:aws:sqs:us-east-1:123456789012:testqueue

So I can set env variable in my script for region and account id and then easily use the same script on real AWS prod

**Comment by Ghazgkull** [comment]
I'm trying to create the world's simplest SNS topic in Localstack using Terraform and I believe this issue is causing it to fail. The output from Terraform first indicates that a topic was created with an ARN containing the account ID "123456789012", but then it immediately blows up complaining about an inability to find the same topic but with an ARN containing "000000000000" instead.

**Comment by whummer** [comment]
Thanks for reporting @tarastriska @Ghazgkull . This should be fixed in the `latest` version, a small test case been added to #2281 avoid regressions in the future. Please report here if the problem persists. Thanks!
