### ISSUE TITLE
Can't create domain in ES service

### ISSUE THREAD

**Issue by zydrunasl** [localstack/localstack#146]
Hello,
i can't create ES service domain. I'm using docker image of localstack.Do i miss some parameters? 
aws es create-elasticsearch-domain --domain-name movies --endpoint-url http://localhost:4578

Expecting value: line 1 column 1 (char 0)
aws es list-domain-names --endpoint-url http://localhost:4578
{
    "DomainNames": []
}

**Comment by whummer** [comment]
This is fixed in commit 5b3d8678eaddafc850f8777bd308bb6161b69692 . Can you please give it a try using the latest Docker image (tags `0.6.0` and `latest`).

Please note that so far only a subset of the ES API is implemented. We'd be happy to merge pull requests if you end up adding new features to the API! Thanks
