### ISSUE TITLE
S3 endpoint on CircleCI rspec tests are failing

### ISSUE THREAD

**Issue by DanCSF** [localstack/localstack#1543]
Rspec tests are failing because WebMock doesn't accept the url: localhost:4572, in order for it to pass it should be localstack:4572, on the development local stack that is the correct url and everything works.
Tried setting the HOSTNAME and HOSTNAME_EXTERNAL ENV variables to localstack in the CircleCi config didn't change the actual url on the tests.
Thank You

**Comment by whummer** [comment]
Thanks for reporting @DanCSF . Can you please provide some details about this issue, or ideally a small, self-contained example that helps reproduce this issue? How is your stack deployed, specifically? How are you starting LocalStack? Are you using Docker, or docker-compose?

> WebMock doesn't accept the url localhost:4572

Can you please be a bit more specific. What's the error you are seeing? Is there an API server listening on port `4572` and accessible from localhost? You mentioned that it "should be" `localstack:4572` - can you simply configure your AWS SDK to use `localstack:4572` instead of `localhost:4572`?

Sorry, it's a bit hard to reproduce this issue with the given information. Closing this issue - but happy to re-open it if more details are provided to reproduce it. Thanks!
