### ISSUE TITLE
development environment python version should match the docker image

### ISSUE THREAD

**Issue by FarhadF** [localstack/localstack#1605]
while developing on localstack found out that the python version used is 2.7, while the docker-image uses version 3.6.8

as in the readme file I brought up my environment using:
```
make install
make infra
```
this will cause issues when touching parts different in these 2 major versions.

workaround:
```
make reinstall-p3
```
this changed the python version to 3.7.3 on debian 10, which is again above docker-image version...

**Comment by whummer** [comment]
Thanks for reporting @FarhadF , and thanks for providing the pull request. Having a proper dev environment depends on various factors, including Python versions. Since Python 2 is approaching its end of life soon, we're assuming that developers have mostly switched to 3.x already. In our CI system, we do actually test various different versions, so at least we have a quality gate before merging code into `master`. Thanks for your input.
