### ISSUE TITLE
Unable to set multiple cookies through API Gateway

### ISSUE THREAD

**Issue by fishion** [localstack/localstack#1637]
There doesn't appear to be any way within localstack to set multiple 'Set-Cookie' headers through API Gateway from a lambda function. 

AWS's API Gateway supports 'multiValueHeaders' which allow this, but even before that it was possible to cheat by using the same key multiple times with different character casing, since the object keys are case sensitive and the HTTP headers are case insensitive.

WIth localstack, neither of these techniques work, which makes it impossible to work around when developing serverless apps which require more than one cookie.

**Comment by whummer** [comment]
Thanks for reporting @fishion . This should be fixed in #2354 - you can now return a  `multiValueHeaders` attribute (list of values) from your Lambda function, which will cause API Gateway to return multiple header entries with the same name. Hope that works - please report here if the problem persists. Thanks
