### ISSUE TITLE
Lamdci container is throwing lambci/lambda:20191117-java11 not found error

### ISSUE THREAD

**Issue by AtithAlur** [localstack/localstack#1782]
The latest docker image for localstack/localstack is throwing
lambci/lambda:20191117-java11 not found error.
<img width="1262" alt="Screen Shot 2019-11-20 at 5 15 01 PM" src="https://user-images.githubusercontent.com/7749613/69286983-3c32b480-0bba-11ea-8c9d-109bcf69cf61.png">

**Comment by rraina91** [comment]
I'm fairly new to serverless (like, been on it for 2 days), but I ran into this issue today too and found your post. I hoped to get some help, but nobody had responded.

That said, I looked into it further. It was because in my serverless.yaml I was specifying a runtime of java11. Changing back to java8 was an immediate workaround that fixed it.

Delving deeper, it looks as if someone is intentionally pre-pending the prefix in the python code below. Since there's no release of 20191117-java11, none can be utilized. 

Hope this helps!

   @classmethod
    def docker_image_for_runtime(cls, runtime):
        docker_tag = runtime
        docker_image = config.LAMBDA_CONTAINER_REGISTRY
        # TODO: remove prefix once execution issues are fixed with dotnetcore/python lambdas
        # See https://github.com/lambci/docker-lambda/pull/218
        if docker_image == 'lambci/lambda':
            docker_tag = '20191117-%s' % docker_tag
        return '"%s:%s"' % (docker_image, docker_tag)
      ^- excerpt from: master/localstack/services/awslambda/lambda_executors.py

**Comment by whummer** [comment]
Thanks for reporting @AtithAlur @rraina91 . This should be fixed in #1855 - please report here if the problem persists. Thanks
