### ISSUE TITLE
Can't connect from localstack container to local domains in same docker network

### ISSUE THREAD

**Issue by ChrisFlannagan** [localstack/localstack#1833]
Localstack is awesome, thanks so much for the contributions here.  I've been using it on a massive project at my agency for a year now and couldn't have done it without localstack.

We recently learned we need to have an endpoint in our system to receive sns messages.  I got the sns service up and running in local stack, creates the topic and subscribes to an https endpoint that is on my local machine only.  The domain is a custom domain setup in our docker configuration 'frac.tribe'

I noticed messages I sent to SNS weren't coming through to our endpoint, so I bashed into the localstack container and ran 'curl http://frac.tribe' which responds with curl: 

(7) Failed to connect to frac.tribe port 80: Connection refused

Same for https and 443.  I know I'm doing something wrong here and its probably simple but I just cannot figure it out.  For some reason localstack can't reach the webserver container setup in the same network. Here's my docker compose file:

```
version: "3.3"
services:

  redis:
    image: redis:alpine
    networks:
      - proxy

  php-fpm:
    build:
      context: .
      dockerfile: phpdocker/php-fpm/Dockerfile
    image: tribe-phpfpm:7.2-fracture
    working_dir: /application
    networks:
      - proxy
    dns: 172.20.10.250
    volumes:
      - ../..:/application/www:cached
      - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
      - ./phpdocker/php-fpm/ssmtp.conf:/etc/ssmtp/ssmtp.conf:ro
      - ./wp-cli.yml:/application/wp-cli.yml
      - ./composer-config.json:/root/.composer/auth.json
      - ./composer-cache:/application/composer-cache
      - ./certs/cacert.pem:/application/certs/cacert.pem
      - ./import:/import
    links:
      - redis
      - localstack
    external_links:
      - "tribe-mysql:mysql"
      - "tribe-mail:mail"
    environment:
      - COMPOSER_ALLOW_SUPERUSER=1
      - COMPOSER_CACHE_DIR=/application/composer-cache

  localstack:
    image: localstack/localstack
    networks:
      - proxy
    ports:
      - "4567-4596:4567-4596"
      - "${PORT_WEB_UI-4699}:${PORT_WEB_UI-4699}"
    environment:
      - LOCALSTACK_SERVICES=s3,sqs,sns,lambda,cloudwatch,logs
      - DEBUG=sns
      - HOSTNAME=localstack
      - HOSTNAME_EXTERNAL=localstack
    volumes:
      - "./localstack:/tmp/localstack"

  webserver:
    image: nginx:stable-alpine
    working_dir: /application
    environment:
      - VIRTUAL_HOST=frac.tribe,*.frac.tribe
    volumes:
      - ../..:/application/www:cached
      - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./phpdocker/nginx/fastcgi.conf:/etc/nginx/fastcgi_params
    networks:
      - proxy
    links:
      - php-fpm
      - localstack

networks:
  proxy:
    external:
      name: global_proxy
```

**Comment by kprzerwa-r7** [comment]
I think this might be more of a docker-compose issue rather than localstack.
You might want to set a hostname of your webserver (unless `VIRTUAL_HOST=frac.tribe,*.frac.tribe` already does it). I would also check that the webserver can be accessed by the IP ( most likely in '172.17.X.X` format). If it's accessible, it's probably just issue with webserver's domain name not visible in localstack. As a last resort you can try setting up an `extra_hosts` for localstack. See https://docs.docker.com/compose/compose-file/#extra_hosts. 
Hope this helps.

**Comment by whummer** [comment]
Thanks for reporting @ChrisFlannagan , and thanks for providing pointers to possible solutions @kprzerwa-r7 !

As @kprzerwa-r7 mentioned, this is more of a docker-compose issue rather than Localstack. Did you succeed connecting to the webserver via the IP directly?

Going to close this issue, as this appears to be very specific to your project setup in docker-compose. However, would be great if you could give us a short update here on whether/how you got it working eventually @ChrisFlannagan. Thanks!
