### ISSUE TITLE
Pass custom environment variables to lambda functions

### ISSUE THREAD

**Issue by andybar2** [localstack/localstack#187]
Is it possible to pass custom environment variables when invoking lambda functions? Ideally I'd like to send the environment variables defined in the docker-compose.yml file to the docker run command here https://github.com/localstack/localstack/blob/d9b2715ba1776e57fabb9e46864e9c5d14d0933b/localstack/services/awslambda/lambda_api.py#L281 but maybe there's a better way of doing it from your point of view.

**Comment by whummer** [comment]
That's a great proposal, environment variables should be supported in Lambdas. There is actually a corresponding API functionality, we should take advantage of it: http://docs.aws.amazon.com/lambda/latest/dg/env_variables.html

The code location you pointed out (in `lambda_api.py`) is the right place to pass in variables to `docker run`. Would you be able to prepare a pull request for this functionality? Otherwise I'm also happy to look into this and help out (if needed). Thanks

**Comment by andybar2** [comment]
Thanks for your response @whummer ! I can try to contribute on this feature but it will be a challenge since I've never worked with python before :disappointed:

**Comment by migurski** [comment]
@andybar2, do you have a way of testing the current master branch of localstack? I think the PR above may close out this issue.

**Comment by andybar2** [comment]
Hey, that's awesome @migurski ! Do you or @whummer know if that change is included in the last localstack docker image (0.7.5) which apparently was updated some hours ago?

**Comment by whummer** [comment]
Yes @andybar2 , this change is included in the latest image version. Closing this ticket now, please re-open if there are any issues. Thanks
