### ISSUE TITLE
Cannot create an Identity Pool

### ISSUE THREAD

**Issue by miles-po** [localstack/localstack#1947]
https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/CognitoIdentity.html#createIdentityPool-property
```js
async function setupCognito() {
  const cognitoIdentity = new AWS.CognitoIdentity({ region: 'us-east-1' });
  const identityPool = await cognitoIdentity.createIdentityPool({
        AllowUnauthenticatedIdentities: true,
        IdentityPoolName: 'example_id_pool',
      }).promise();
}

setupCognito()
  .then(() => console.log('Success'))
  .catch((err) => console.error);
```
The Localstack log prints this during intitialization:
```
Starting mock Cognito Identity Provider (IdP) (http port 4590)...
Starting mock Cognito Identity (http port 4591)...
```
The underlying error is a 404, so looks like it's not implemented yet.

**Comment by whummer** [comment]
Thanks for reporting @miles-po . Turns out this was also an issue related to a missing route in the `edge` router - the Cognito Identity API should indeed be available.

This should be fixed in the latest version - can you please try again after pulling the latest Docker image. Closing this issue - please reopen if the problem persists. Thanks
