### ISSUE TITLE
Provisioning Elasticache with terraform hangs

### ISSUE THREAD

**Issue by JoeReid** [localstack/localstack#1959]
Provisioning Redis Elasticache instances with the following Terraform hangs forever

```terraform
resource "aws_elasticache_cluster" "my-redis" {
  cluster_id           = "my-redis-cluster"
  engine               = "redis"
  node_type            = "cache.m4.large"
  num_cache_nodes      = 1
  parameter_group_name = "default.redis3.2"
  engine_version       = "3.2.10"
  port                 = 6379
}
```
When looking in the localstack logs, I can actually see that redis was started with no error.
```
localstack_1   | 110:C 17 Jan 2020 10:25:54.195 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
localstack_1   | 110:C 17 Jan 2020 10:25:54.195 # Redis version=5.0.5, bits=64, commit=47edd290, modified=0, pid=110, just started
localstack_1   | 110:C 17 Jan 2020 10:25:54.195 # Configuration loaded
localstack_1   | 110:M 17 Jan 2020 10:25:54.196 * Running mode=standalone, port=4510.
localstack_1   | 110:M 17 Jan 2020 10:25:54.196 # Server initialized
```

I think that the hang is caused by terraform calling `DescribeCacheClusters` to confirm creation

```
WARNING:localstack_ext.services.elasticache.elasticache_api: Unknown ElastiCache API action: DescribeCacheClusters
```
I suspect that minimally supporting this API call would fix the issue

**Comment by whummer** [comment]
Thanks for reporting @JoeReid . This should be fixed in the latest version - can you please do another `docker pull localstack/localstack` and try again?

We've also added your example to the sample project here: https://github.com/localstack/localstack-pro-samples/blob/master/terraform-resources/test.tf#L123-L131

Closing this issue - please report here if the problem persists. Thanks!
