### ISSUE TITLE
Port argument (terraform) not supported by RDS or Elasticache

### ISSUE THREAD

**Issue by JoeReid** [localstack/localstack#1966]
When using terraform to provision both an RDS and Elasticache instance, both provisioned resources do not have the expected port values.

I would expect the services to be started on ports `4512` and `6379` respectively.
However the behavior I get is different, and seems to be a race hazard.

It seems both services race to use the port `4510`, sometimes they both attempt to use this port, and other times one is assigned `4510` and the other `4511`.

In both cases however, the requested port number appears to be ignored.
I think this may be a general provisioning error affecting all resource types, but I have only confirmed it against RDS and Elasticache.

I have provided the following terraform scripts to reproduce the error.
```terraform
resource "aws_db_instance" "my-rds" {
  engine            = "postgres"
  instance_class    = "db.m4.large"
  name              = "my_db_test"
  identifier        = "mytestdb"
  allocated_storage = 20
  username          = "my-app"
  password          = "psql"
  port              = 4512
}

resource "aws_elasticache_cluster" "my-redis" {
  cluster_id           = "my-redis"
  engine               = "redis"
  node_type            = "cache.m4.large"
  num_cache_nodes      = 1
  parameter_group_name = "default.redis3.2"
  engine_version       = "3.2.10"
  port                 = 6379
}
```

**Comment by whummer** [comment]
Thanks for reporting this issue @JoeReid .

The issue with the race condition should be fixed in the latest version - Terraform should now be able to provision these resources in parallel.

As far as the port numbers are concerned - that's a slightly more difficult issue. Since LocalStack is running in Docker, we need to expose the set of ports initially when we start the container. In other words, the `port` attribute in your Terraform config is not considered, but an auto-generated port will be used (e.g., `4510`). Would it be an option for you to change your code in a way that it retrieves the port number after the resources have been created?

Thanks

**Comment by JoeReid** [comment]
Hi @whummer thanks for looking at this so quickly.

However, I think there is a remaining issue here (leaving the port allocation requests aside).

Your fix seem to mitigate the race issue on port assignment, however the reported port at the end of the process is wrong.

When running the previous terraform (with the port config removed) the resources are created on ports `4510` and `4512`.
```
localstack_1   | 2020-01-22T09:08:23:DEBUG:localstack_ext.services.elasticache.elasticache_api: Start Redis server on port 4510
localstack_1   | 2020-01-22T09:08:24:INFO:localstack_ext.services.rds.rds_listener: Starting RDS server on port 4512 - database "my_db_test", user "my-app"
```

My suspicion is that the second port is an off by one error, as the reported port from terraform is `4511` which causes the next steps (DB migration in my case) to fail

```
migrate:
    exit status 1. Output: Unable to connect to PostgreSQL:
        dial tcp 127.0.0.1:4511: connect: connection refused
```
