### ISSUE TITLE
docker-compose fails to run the custom initialisation script due to awslocal cli (ModuleNotFoundError: No module named 'localstack_client')

### ISSUE THREAD

**Issue by rp199** [localstack/localstack#2066]
I'm getting this error running the docker-compose with the latest image:
```
localstack_1  | /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initaws.d/init-stack.sh
localstack_1  | Traceback (most recent call last):
localstack_1  |   File "/usr/bin/awslocal", line 28, in <module>
localstack_1  |     from localstack_client import config
localstack_1  | ModuleNotFoundError: No module named 'localstack_client'
```
In the init-stack.sh I create some resources by cloudformation.

Wanted to point out that yesterday was working fine so maybe this is due to some recent change.

Meanwhile I got an workaround by adding to the beginning of the script:
`pip install awscli-local
`

Is it planned to have release soon? It would be nice to lock the version to avoid some breaking changes. Can't use other versions right now because the latest version is the only one who have Java11 support.

Thanks for this awesome project and support!

**Comment by vincentcr** [comment]
We are experiencing the same issue, because our docker image of localstack was not pinned and was using `latest`. Seems like last night's new version introduced this issue.  

We fixed it by pinning localstack to 0.10.7. 

BTW, looking at the image tags here: https://hub.docker.com/r/localstack/localstack/tags, it's a bit strange that:

- `latest` was built 8 hours ago but that build does not seem to have a corresponding versioned tag.
- `0.10.6` was built after `0.10.7`.

**Comment by rp199** [comment]
I would use the version 0.10.7 but it lacks Java11 support. I have some projects in Java 8 and they work fine with the 0.10.7

Looking forward to update them to Java 11 but I'm waiting for a new release because using the localstack image with the latest tag version is always risky due to some unwanted breaking changes.

**Comment by LeandroSNunes** [comment]
I fell into the same error, I needed to go back to v0.10.6 :-/
