### ISSUE TITLE
DeadLetterConfig not being honored in call to create_function

### ISSUE THREAD

**Issue by hjb417** [localstack/localstack#2095]
Attached is a python script that will create a lambda function that will always fail. I setup a dead letter queue and the lambda isn't writing to it on failure. It's also not returning the dead letter config in the return value of the call to "create_function"

[replicate.py.txt](https://github.com/localstack/localstack/files/4256803/replicate.py.txt)

**Comment by whummer** [comment]
Thanks for reporting @hjb417 - this should be fixed in the meantime. Simple integration tests have been added [here](https://github.com/localstack/localstack/blob/edd4f346cf67c9f0a48e59eec68fe3e2862949a8/tests/integration/test_lambda.py#L201-L204) and [here](https://github.com/localstack/localstack/blob/991253de805d14981f746a522538df878af75e90/tests/integration/test_sns.py#L356-L358). Please report here if the problem still persists. Thanks
