### ISSUE TITLE
Missing Sns Subject at LambdaExecutor

### ISSUE THREAD

**Issue by ch4rlyx** [localstack/localstack#2131]
Hello,

I have an issue invoking a java Lambda subscribed to and SNS topic, when i publish an SNS message with a subject, the subject missing.

I have narrowed the issue down to LambdaExecutor

TIA!

**Comment by whummer** [comment]
Thanks for reporting @ch4rlyx . This should be fixed in the latest version, an integration test has been added in #2143 to assert this functionality, and to avoid regressions in the future. Can you please do a `docker pull localstack/localstack` and give it a try with the latest version? Please report here if the problem persists. Thanks
