### ISSUE TITLE
How to run localstack on Ubuntu 19?

### ISSUE THREAD

**Issue by win32nipuh** [localstack/localstack#2156]
I have installed localstack and try to run it, there are errors during 

>localstack start --host
[localstack.txt](https://github.com/localstack/localstack/files/4329584/localstack.txt)

What is wrong? How to run the localstack?

**Comment by whummer** [comment]
Thanks for reporting @win32nipuh . Please note that the supported and recommended way of starting LocalStack these days is in Docker, which is the default if you simply run `localstack start`.

We've deprecated the `--host` option a while ago, as supporting the different combinations of OS/Python/Node.js/Java versions turned out to be infeasible.

Please let us know if working in Docker works for you, or if there are any issues with that. Thanks
