### ISSUE TITLE
CloudFormation - CreationTime is now supported in moto

### ISSUE THREAD

**Issue by bblommers** [localstack/localstack#2178]
Originally reported in https://github.com/localstack/localstack/issues/2099, the CreationTime for CF stacks was hardcoded. This was fixed in in LocalStack itself (https://github.com/localstack/localstack/pull/2103), but is now also fixed in moto (https://github.com/spulec/moto/pull/2818).

I don't know what version of moto you're using, and whether it's acceptable to use dev-releases, but if you do: 

moto 1.3.15.dev550 should fix this issue, so the LS fix can be removed if you upgrade :)

**Comment by whummer** [comment]
Thanks for the update @bblommers . The `latest` version of LocalStack contains the latest moto code. Looks like there are still a few hardcoded dates which we can tackle in the future (e.g., [here](https://github.com/spulec/moto/blob/master/moto/cloudformation/responses.py#L612)). 

Also, for now I had to leave the patch in there because in some cases we were receiving empty `<CreationTime></CreationTime>` entries, which was breaking some boto3 API calls. We'll keep the patch in there until things are fully fixed in moto - thanks again!
