### ISSUE TITLE
Can't run latest localstack in docker as non-root user

### ISSUE THREAD

**Issue by anascotti** [localstack/localstack#2206]
# Type of request: This is a bug report

# Detailed description

Cannot run localstack in docker with non-root user using latest docker image (0.10.9).
Supervisor doesn't allow non-root to switch to root, probably caused by this [commit](https://github.com/localstack/localstack/commit/1d222646c14fbe5c1e5088fb493fc0b473315066#diff-c54bdd2a91116a1c99267149fd2b5390)

Related supervisor issue:
https://github.com/Supervisor/supervisor/issues/1218

Latest docker image is version 0.10.9, which is not a release (?)
Image version 0.10.8 works fine, printing just a warning.

## Actual behavior

Service won't start
```
localstack_1  | Error: Can't drop privilege as nonroot user
``` 

# Steps to reproduce

## Command used to start LocalStack

`docker-compose up` with config:
``` localstack:
    image: localstack/localstack
    user: ${NONROOT}
    environment:
      SERVICES: s3
```

**Comment by whummer** [comment]
Thanks for reporting @anascotti . So my understanding is that this can be fixed by reverting [this commit](https://github.com/localstack/localstack/commit/1d222646c14fbe5c1e5088fb493fc0b473315066#diff-c54bdd2a91116a1c99267149fd2b5390), right? Supervisord would continue to print the warning message, but at least it would work. We'll make that change to give it a try.
