### ISSUE TITLE
Unable to Create SQS Queue with QueueARN without 000000000000

### ISSUE THREAD

**Issue by choudhurysr** [localstack/localstack#2279]
# Type of request: This is a ...

[x ] bug report
[ ] feature request

# Detailed description

Unable to Create SQS Queue with QueueARN without 000000000000 

"QueueArn" seem to always have 000000000000 in all queues created.

This is causing issues with triggering a lambda from a queue when there are more than one queue and lambda.

## Expected behavior

Create SQS Queue with QueueARN without 000000000000 
For example:
QueueArn=arn:aws:sqs:us-west-2:000000000001:queue1

## Actual behavior

Checked by running awslocal sqs get-queue-attributes --queue-url http://localhost:4576/queue/queue1 --attribute-names All

Tried to specify QueueArn of 000000000001 while creating queue using below 2 methods:

awslocal sqs create-queue --queue-name watermarker-file-processing-queue1 --attributes file://create-queue.json

awslocal sqs create-queue --queue-name watermarker-file-processing-queue1 --attributes QueueArn=arn:aws:sqs:us-west-2:000000000001:queue1

But in either case QueueArn was 000000000000 ignoring the QueueArn specified.

# Steps to reproduce

Tried to specify QueueArn of 000000000001 while creating queue using below 2 methods:

awslocal sqs create-queue --queue-name watermarker-file-processing-queue1 --attributes file://create-queue.json

awslocal sqs create-queue --queue-name watermarker-file-processing-queue1 --attributes QueueArn=arn:aws:sqs:us-west-2:000000000001:queue1

But in either case QueueArn was 000000000000 ignoring the QueueArn specified.

## Command used to start LocalStack

docker-compose up -d

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

awslocal sqs create-queue --queue-name watermarker-file-processing-queue1 --attributes file://create-queue.json

awslocal sqs create-queue --queue-name watermarker-file-processing-queue1 --attributes QueueArn=arn:aws:sqs:us-west-2:000000000001:queue1

**Comment by whummer** [comment]
Thanks for reporting @choudhurysr . Not sure I understand exactly what the issue is here.

Please note that `000000000000` corresponds to the account ID that is used in AWS ARNs. Currently, all resources created in LocalStack are associated with a single account, which is hardcoded as `000000000000` by default.

You can use the `TEST_AWS_ACCOUNT_ID` environment variable to configure a different account ID, but the account ID will be globally applied to all resources. Please note that cross-account setups are currently not yet supported (i.e., you cannot create resources in different account IDs). 

Does that make sense, or am I missing something here? Thanks
