### ISSUE TITLE
Put record in Kinesis doesn't find stream

### ISSUE THREAD

**Issue by xaviarias** [localstack/localstack#231]
Hello, I am using JUnit integration and I have a a working environment for Localstack (`awslocal` commands and Maven tests under `ext/java` work fine).

When executing a unit test, I can create a stream in Kinesis and retrieve it through `listStreams`. However, when calling `putRecord` I receive the following error:

`Received error response: com.amazonaws.services.kinesis.model.ResourceNotFoundException: Stream test-stream under account 000000000000 not found. (Service: AmazonKinesis; Status Code: 400; Error Code: ResourceNotFoundException; Request ID: aa131f40-7831-11e7-ae68-5b6130e495ed)`

The CBOR format is disabled (I can see the Kinesis requests content type in `json`) and the started services are `lambda,kinesis,apigateway,sqs`.

Thanks
[test-localstack.txt](https://github.com/localstack/localstack/files/1197010/test-localstack.txt)

**Comment by whummer** [comment]
This might be a timing issue. The underlying Kinesis implementation puts the stream into status `CREATING` immediately after creation, for approximately 500 milliseconds. This is actually great for testing, because it closely reflects the behavior of the AWS API (resource creation might take a while and the stream may not be immediately available).

In your test, you can either:
* Go the simple route and add a `Thread.sleep(1000)`
* Be a bit more sophisticated and add a loop that checks the stream status and waits for it to become `ACTIVE`.

Would you be able to add a few notes to the Troubleshooting section of the `README` (via a pull request)? Much appreciated!

**Comment by whummer** [comment]
Any update on this issue @xaviarias - did you have a chance to give it a try with the fixes suggested above? Thanks

**Comment by xaviarias** [comment]
Hi Waldemar,

Not yet, as soon as I can I'll try tour solution.

Thanks

El dia 16 ag. 2017 5:17 p. m., "Waldemar Hummer" <notifications@github.com>
va escriure:

Any update on this issue @xaviarias <https://github.com/xaviarias> - did
you have a chance to give it a try with the fixes suggested above? Thanks

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/localstack/localstack/issues/231#issuecomment-322805664>,
or mute the thread

**Comment by whummer** [comment]
Hi, we're in the process of cleaning up a few old/untriaged tickets. I'm closing this ticket for now, as there seems to be a solution based on `Thread.sleep(1000)`. Please feel free to re-open the ticket if the problem persists. Thanks.

**Comment by xaviarias** [comment]
The sleep solution works perfectly. Thanks!
