### ISSUE TITLE
docker-compose.yaml creates /tmp/localstack owned by root

### ISSUE THREAD

**Issue by marcindulak** [localstack/localstack#2322]
# Type of request: This is a ...
[x] bug report
[ ] feature request

# Detailed description
localstack started using docker-compose creates `/tmp/localstack` owner by root.
Actually I'm not sure this is a bug, but still something that breaks local development, since cleaning the directory requires root.

# Steps to reproduce
```sh
cat /etc/*release | grep PRETTY
PRETTY_NAME="Ubuntu 18.04.4 LTS"
docker --version
Docker version 19.03.8, build afacb8b7f0
docker-compose --version
docker-compose version 1.17.1, build unknown
```

## Command used to start LocalStack
```sh
cd /tmp
sudo rm -rf localstack
wget https://raw.githubusercontent.com/localstack/localstack/ce8d37628185842621826067fe50d96c3ac11cc2/docker-compose.yml
sed -i'.bak' 's|localstack/localstack|localstack/localstack:0.11.0|' docker-compose.yml
docker-compose down
docker-compose up -d
ls -al localstack/
total 28
drwxr-xr-x  2 root root  108 Apr 19 19:45 .
drwxrwxrwt 39 root root 8192 Apr 19 19:45 ..
-rw-r--r--  1 root root 3644 Apr 19 19:45 server.test.pem
-rw-r--r--  1 root root 1938 Apr 19 19:45 server.test.pem.crt
-rw-r--r--  1 root root 1703 Apr 19 19:45 server.test.pem.key
-rw-r--r--  1 root root  303 Apr 19 19:45 sqs.0ae38457.conf
```

Tested also against https://hub.docker.com/layers/localstack/localstack/latest/images/sha256-7136d9bd2503d887118d0bcba5208c23038d27054c610bd45ed3e80d51c60ee3

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-175) by [Unito](https://www.unito.io/learn-more)

**Comment by whummer** [comment]
Thanks for reporting @marcindulak . It's been some time since this issue has been created. Please note that it depends on the local Docker setup how the volume mounts are created (and which file permissions are being used). Under MacOS/Windows, the Docker engine typically mounts the directories in a way that the tmp files are owned by the local user account. This may be different under Linux, though. 

Currently, the main LocalStack process requires privileged access (e.g., for exposing certain ports, or to talk to the local Docker socket to spawn new Lambda containers). Closing this issue for now, but we'll continue to investigate options around Lambda execution and permissions in the container, including potential non-privileged execution.. Thanks!
