### ISSUE TITLE
s3.upload returns `Location: http://localhost:4566`

### ISSUE THREAD

**Issue by BR0kEN-** [localstack/localstack#2329]
# Bug report

# Detailed description

The `AWS.s3.upload()` (official SDK - https://github.com/aws/aws-sdk-js) returns an object with the `Location` key that points to 4566 instead of 4572 (LocalStack S3 port).

## Expected behavior

The `Location` should point to the file on S3.

Example:

```
Location: http://localhost:4572/path/to/bucket.txt
```

## Actual behavior

The `Location` points to the LocalStack entrypoint.

Example:

```
Location: http://localhost:4566/path/to/bucket.txt
```

# Steps to reproduce

- Upload a file to S3 using the official AWS SDK (https://github.com/aws/aws-sdk-js).
- Check out the `Location` property.

## Client code

```javascript
const AWS = require('aws-sdk');
const s3 = new AWS.S3({
  region: 'us-west-1',
  endpoint: 'http://localhost:4566',
  apiVersion: '2006-03-01',
  s3ForcePathStyle: true,
});

(async () => {
  await s3
    .createBucket({ Bucket: 'my-bucket', ACL: 'private' })
    .promise();

  const { Location } = await s3
    .upload({ Key: 'file.txt', Body: 'test', Bucket: 'my-bucket' })
    .promise();

  console.assert(Location === 'http://localhost:4572/my-bucket/file.txt');
})();
```

**Comment by whummer** [comment]
Thanks for reporting @BR0kEN- . This is the expected behavior. Please note that starting with version 0.11.0 we've added an _edge service_ on port 4566 which acts as a proxy and central API entry point that redirects requests to backend APIs.

My assumption would be that you can access the file under the given URL (http://localhost:4566/path/to/bucket.txt) . Please report here if that's not the case and you cannot access that URL. Thanks

Please note that we also have a pending PR that prints the updated/deprecated port numbers - will be merged soon: https://github.com/localstack/localstack/pull/2318

**Comment by BR0kEN-** [comment]
That's exactly the case @whummer. I'm still able to access the file via `http://localhost:4572/path/to/bucket.txt` while `http://localhost:4566/path/to/bucket.txt` returns `{"status": "running"}`.

**Comment by karrui** [comment]
I am also facing this issue. Using port `4566` results in an error message from localstack: `localstack | 2020-05-06T02:37:08:INFO:localstack.services.edge: Unable to find forwarding rule for host "localhost:4566", path "/local-image-bucket", target header "", auth header ""`

This is using docker-compose

**Comment by philippmalkov** [comment]
Yes. Issue is still actual for POST requests to urls that got from aws.s3.createPresignedPost aws function... For :4572 all works fine.

```
2020-05-24T15:36:54:INFO:localstack.services.edge: Unable to find forwarding rule for host "localhost:4566", path "/local-job-documents", target header "", auth header ""
```
