### ISSUE TITLE
Docker: Unable to store key/cert files for custom SSL certificate

### ISSUE THREAD

**Issue by trombonekenny** [localstack/localstack#2362]
# Type of request: This is a ...
[x] bug report
[ ] feature request

# Detailed description
When running in docker/docker-compose I can't seem to make this error go away:

> Waiting for all LocalStack services to be ready
> 2020-04-27T19:54:20:INFO:localstack.utils.common: Unable to store key/cert files for custom SSL certificate: [Errno 13] Permission denied: '/tmp/localstack/server.test.pem.key'
> 

## Expected behavior
I'm not running SSL in the stack so I'm not sure why it's erroring about the certificate.

## Actual behavior
# Steps to reproduce
```
mussulma@dragon:~$ docker run -it --rm localstack/localstack
Waiting for all LocalStack services to be ready
2020-04-27 19:48:17,660 CRIT Supervisor is running as root.  Privileges were not                                                                                       dropped because no user is specified in the config file.  If you intend to run                                                                                       as root, you can set user=root in the config file to avoid this message.
2020-04-27 19:48:17,665 INFO supervisord started with pid 13
2020-04-27 19:48:18,669 INFO spawned: 'dashboard' with pid 19
2020-04-27 19:48:18,672 INFO spawned: 'infra' with pid 20
(. .venv/bin/activate; bin/localstack web)
2020-04-27 19:48:18,693 INFO success: dashboard entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
(. .venv/bin/activate; exec bin/localstack start --host)
LocalStack version: 0.11.0
LocalStack version: 0.11.0
Starting local dev environment. CTRL-C to quit.
2020-04-27 19:48:20,496 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Waiting for all LocalStack services to be ready
2020-04-27T19:48:30:INFO:localstack.utils.common: Unable to store key/cert files for custom SSL certificate: [Errno 13] Permission denied: '/tmp/localstack/server.test.pem.key'
```

It doesn't matter if I pass in USE_SSL=0 or a volume mount for /tmp/localstack, if the server.test.pem.key exists already or needs to get created.

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-177) by [Unito](https://www.unito.io/learn-more)

**Comment by bobtiernay-okta** [comment]
Also hitting this against `0.11.1`:
```yaml
```
version: '3.7'

services:
  localstack:
    container_name: localstack
    hostname: localstack
    image: localstack/localstack:0.11.1
    ports:
      - "4576:4576"
      - "4572:4572"
      - "4569:4569"
      - "5467:5467"
    environment:
      # See https://github.com/localstack/localstack#configurations
      - SERVICES=sqs,s3,kinesis,dynamodb
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - KINESIS_LATENCY=0
      - SQS_PORT=4576
      - S3_PORT=4572
      - DYNAMODB_PORT=4569
      - KINESIS_PORT=5467
      - USE_SSL=1
      - START_WEB=1
      - AWS_CBOR_DISABLE=true
      - LAMBDA_REMOTE_DOCKER=0
    volumes:
      - localstack-data-volume:/tmp/localstack

volumes:
  localstack-data-volume:
```
```
$ docker-compose up localstack
```
```
Starting mono_localstack ... done
Attaching to mono_localstack
mono_localstack | Waiting for all LocalStack services to be ready
mono_localstack | 2020-05-07 23:46:59,835 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
mono_localstack | 2020-05-07 23:46:59,837 INFO supervisord started with pid 15
mono_localstack | 2020-05-07 23:47:00,842 INFO spawned: 'dashboard' with pid 21
mono_localstack | 2020-05-07 23:47:00,845 INFO spawned: 'infra' with pid 22
mono_localstack | (. .venv/bin/activate; bin/localstack web)
mono_localstack | 2020-05-07 23:47:00,850 INFO success: dashboard entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
mono_localstack | 2020-05-07T23:47:01:DEBUG:bootstrap.py: Loading plugins - scope "commands", module "localstack_ext": <function register_localstack_commands at 0x7fabf3bbd790>
mono_localstack | LocalStack version: 0.11.1
mono_localstack | 2020-05-07T23:47:01:DEBUG:bootstrap.py: Loading plugins - scope "services", module "localstack": <function register_localstack_plugins at 0x7fabf3bef310>
mono_localstack | (. .venv/bin/activate; exec bin/localstack start --host)
mono_localstack | LocalStack version: 0.11.1
mono_localstack | Starting local dev environment. CTRL-C to quit.
mono_localstack | 2020-05-07T23:47:01:DEBUG:bootstrap.py: Loading plugins - scope "commands", module "localstack_ext": <function register_localstack_commands at 0x7f06fc546790>
mono_localstack | 2020-05-07T23:47:01:DEBUG:bootstrap.py: Loading plugins - scope "services", module "localstack": <function register_localstack_plugins at 0x7f06fc578310>
mono_localstack | 2020-05-07 23:47:02,559 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
mono_localstack | 2020-05-07T23:47:03:DEBUG:bootstrap.py: Loading plugins - scope "services", module "localstack_ext": <function register_localstack_plugins at 0x7fabf3431b80>
mono_localstack | 2020-05-07T23:47:03:INFO:localstack.utils.common: Unable to store key/cert files for custom SSL certificate: [Errno 13] Permission denied: '/tmp/localstack/server.test.pem.key'
mono_localstack | 2020-05-07T23:47:03:INFO:localstack.utils.common: Unable to store key/cert files for custom SSL certificate: [Errno 13] Permission denied: '/tmp/localstack/server.test.pem.key'
mono_localstack | 2020-05-07T23:47:03:DEBUG:bootstrap.py: Loading plugins - scope "services", module "localstack_ext": <function register_localstack_plugins at 0x7f06fbdbab80>
mono_localstack | Waiting for all LocalStack services to be ready
mono_localstack | Starting edge router (https port 4566)...
mono_localstack | Starting mock DynamoDB service in https ports 4566 (recommended) and 4569 (deprecated)...
mono_localstack | Starting mock Kinesis service in https ports 4566 (recommended) and 5467 (deprecated)...
mono_localstack | Starting mock S3 service in https ports 4566 (recommended) and 4572 (deprecated)...
mono_localstack | Starting mock SQS service in https ports 4566 (recommended) and 4576 (deprecated)...
mono_localstack | Initializing DynamoDB Local with the following configuration:
mono_localstack | Port:	4563
mono_localstack | InMemory:	false
mono_localstack | DbPath:	/tmp/localstack/data/dynamodb
mono_localstack | SharedDb:	true
mono_localstack | shouldDelayTransientStatuses:	false
mono_localstack | CorsParams:	*
mono_localstack | Listening at http://:::4564
mono_localstack |
mono_localstack | 2020-05-07T23:47:05:INFO:localstack.multiserver: Starting multi API server process on port 51492
mono_localstack | 2020-05-07 23:47:05,914:API:  * Running on http://0.0.0.0:4562/ (Press CTRL+C to quit)
mono_localstack | 2020-05-07 23:47:05,914:API:  * Running on http://0.0.0.0:4562/ (Press CTRL+C to quit)
mono_localstack | 2020-05-07 23:47:05,914:API:  * Running on http://0.0.0.0:4562/ (Press CTRL+C to quit)
mono_localstack | 23:47:06.884 [main] INFO  org.elasticmq.server.Main$ - Starting ElasticMQ server (0.15.5) ...
mono_localstack | 23:47:07.703 [elasticmq-akka.actor.default-dispatcher-4] INFO  akka.event.slf4j.Slf4jLogger - Slf4jLogger started
mono_localstack | 23:47:09.258 [elasticmq-akka.actor.default-dispatcher-4] INFO  o.e.rest.sqs.TheSQSRestServerBuilder - Started SQS rest server, bind address 0.0.0.0:4560, visible server address http://localstack:4576
mono_localstack | 23:47:09.261 [main] INFO  org.elasticmq.server.Main$ - === ElasticMQ server (0.15.5) started in 3120 ms ===
mono_localstack | 2020-05-07 23:47:11,571:API: 127.0.0.1 - - [07/May/2020 23:47:11] "GET / HTTP/1.1" 200 -
mono_localstack | 2020-05-07 23:47:11,571:API: 127.0.0.1 - - [07/May/2020 23:47:11] "GET / HTTP/1.1" 200 -
mono_localstack | 2020-05-07 23:47:11,571:API: 127.0.0.1 - - [07/May/2020 23:47:11] "GET / HTTP/1.1" 200 -
mono_localstack | Ready.
```

**Comment by bobtiernay-okta** [comment]
Looks like this may be related to https://github.com/docker/compose/issues/3270.

Perhaps the entrypoint can change the permissions to allow `localstack` user to access?

**Comment by whummer** [comment]
Thanks @trombonekenny . We have recently introduced a new file layout / folder mapping which should alleviate some of the mounting/permission issues. Also, there is now fallback logic in place that will stores the SSL certs under a different path in case of issues. Closing this issue as resolved - please let us know if the problem persists. Thanks!
