### ISSUE TITLE
when http_proxy is set,  mock server health check fail

### ISSUE THREAD

**Issue by komeda-shinji** [localstack/localstack#239]
In an environment using a proxy server, the mock server health check fail.
Work around is disable proxy setting.

Case 1: http_porxy is set, and run on local.

`localstack start` cause these error:

```
WARNING:infra.py:Service "elasticsearch" not yet available, retrying...
WARNING:infra.py:Service "elasticsearch" not yet available, retrying...
WARNING:infra.py:Service "elasticsearch" not yet available, retrying...
ERROR:localstack.services.es.es_starter:Elasticsearch health check failed (retrying...): TransportError(403, '<!DOCTYPE HTML PUBLIC " ...
```

Case 2: run on Docker for Mac and proxy setting is enabed in Docker for Mac.

`localstack start --docker` cause  these error:

```
WARNING:infra.pyc:Service "kinesis" not yet available, retrying...
WARNING:infra.pyc:Service "kinesis" not yet available, retrying...
WARNING:infra.pyc:Service "kinesis" not yet available, retrying...
ERROR:infra.pyc:Error checking state of local environment (after some retries): Traceback (most recent call last):
File "/opt/code/localstack/localstack/services/infra.py", line 285, in check_infra
raise e
TypeError: 'NoneType' object has no attribute '__getitem__'
Traceback (most recent call last):
File "bin/localstack", line 79, in <module>
infra.start_infra()
File "/opt/code/localstack/localstack/services/infra.py", line 359, in start_infra
raise e
TypeError: 'NoneType' object has no attribute '__getitem__'
```

**Comment by whummer** [comment]
Hi @komeda-shinji , thanks for reporting. Can you please provide a few more details about your use case. Which value are you using for `http_proxy`, and what are you trying to achieve? 

We may be able to fix this issue by simply ignoring/ the `http_proxy` environment variable, but it needs to be documented accordingly because other users may be relying on exactly that behavior. Therefore a better understanding of your use case would be helpful to make sure we're not breaking existing functionality. Thanks

**Comment by komeda-shinji** [comment]
In my envrionment, system proxy is set, and Docker for Mac use system proxy (this is defaut).
Docker activates the container with http_proxy is set.

In localstack, some plugin check functions call internally boto3.session.Session() using aws_stack.connect_to_service().
boto3 is aware to the http_proxy environment variable, then the health check is executed via the proxy.
A health check endpoint url is either http://localhost:port or http://docker-container-address:port, the proxy server cannot connect these addresses, the health check will fail.

**Comment by whummer** [comment]
@komeda-shinji This is fixed in https://github.com/localstack/localstack/pull/243 . The default behavior is now to completely ignore the `http_proxy`/`https_proxy` environment variables.

However, given that this not only affects the local service invocations, but also any external/outgoing HTTP calls done by LocalStack (e.g., when initializing and downloading additional dependencies), I feel like some users might run into issues with this approach. In a future iteration, we may have to change the logic to bypass the proxy for `localhost` invocations only, whereas still using the proxy for any outgoing calls.

**Comment by komeda-shinji** [comment]
Hmm, I cheked boto3 source code, then I noticed the botocore look up `no_proxy` environment variable.
Can we set `no_proxy` in config.py instead of ignore `http_proxy`?

like this:

```
no_proxy = ','.join(HOSTNAME, LOCALHOST)
if os.environ.get('no_proxy'):
  os.environ['no_proxy'] += ',' + no_proxy
else:
  os.environ['no_proxy'] = no_proxy
```

**Comment by whummer** [comment]
Good catch, that makes more sense. `no_proxy` should also work for the `requests` library (https://pypi.python.org/pypi/requests) which we're using for some intra-service calls. Would you be able to raise a pull request with that change @komeda-shinji ? Thanks!

**Comment by whummer** [comment]
Fixed in https://github.com/localstack/localstack/pull/244
