### ISSUE TITLE
Is S3Guard supported in localstack?

### ISSUE THREAD

**Issue by hitesh-goel** [localstack/localstack#2408]
# Type of request: This is a ...
[ ] bug report
[ ] feature request

# Detailed description
...

## Expected behavior
...

## Actual behavior
...

# Steps to reproduce
## Command used to start LocalStack
...

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
...

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-181) by [Unito](https://www.unito.io/learn-more)

**Comment by whummer** [comment]
Thanks for reporting @hitesh-goel . Can you please provide some more details about your specific use case? I'm assuming you're referring to S3Guard feature that provides S3 consistency in Hadoop: https://blog.cloudera.com/introducing-s3guard-s3-consistency-for-apache-hadoop

I think in general it should be possible, as long as you manage to configure Hadoop/S3Guard in a way that it connects to the APIs on `localhost`, instead of the real APIs. We have seen various examples of people connecting Hadoop to LocalStack, e.g.:
https://github.com/risdenk/s3a-localstack
https://github.com/suburbanmtman/hadoop-2.7.3-spark-localstack
https://stackoverflow.com/questions/48767216/spark-error-writing-dataframe-to-localstack-s3

Any chance you can provide a small self-contained project to reproduce your use case or the issue you're facing?

**Comment by HarshCasper** [comment]
Thank you for your issue!

We did not get a response to our questions in our [comment](https://github.com/localstack/localstack/issues/2408#issuecomment-625905704). Given only the information currently available on the issue, we don't have enough information to take action. I'm going to close this issue, but please don't hesitate to reach out if you have further answers we need, we'll be happy to reopen the issue.
