### ISSUE TITLE
Multiple SNS subscriptions not triggered when 429 is returned from web server

### ISSUE THREAD

**Issue by jchannon** [localstack/localstack#2422]
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description

When having multiple SNS subscriptions they are handled via a POST request to the url specified in the subscription. When SNS is triggered and multiple requests are sent (which appears to be in order of how the subscriptions were registered) if one of the requests returns 429 subsequent requests are not sent.  In AWS for example, if a lambda returns 429 it is internally queued and the message is re-issued. 

https://docs.aws.amazon.com/sns/latest/dg/sns-message-delivery-retries.html

https://docs.aws.amazon.com/lambda/latest/dg/invocation-retries.html

https://docs.aws.amazon.com/lambda/latest/dg/invocation-async.html
...

## Expected behavior
All HTTP requests sent on multipe SNS subscriptions
...

## Actual behavior
If one request returns 429 subsequent requests are not sent
...

# Steps to reproduce

Register multiple subscriptions to a route in your webserver
Trigger SNS
On one of the expected requests return 429
Note expected requests after 429 are not executed

## Command used to start LocalStack

...

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

...

**Comment by whummer** [comment]
Thanks for reporting @jchannon . Looks like this issue should be fixed in the meantime - please note that we have recently added several enhancements around SNS notifications. Can you please do a `docker pull localstack/localstack` and give it another try with the `latest` version of the Docker image? Please report here if the problem persists. Thanks!
