### ISSUE TITLE
stuck in Waiting for all LocalStack services to be ready

### ISSUE THREAD

**Issue by justinlazaro-iselect** [localstack/localstack#2439]
Hi guys, im using windows, docker got stuck in "Waiting for all LocalStack services to be ready"

versions:

![image](https://user-images.githubusercontent.com/54691710/82313473-fb95e580-99fa-11ea-843e-00ab07558769.png)

`docker-compose.yml`
```
version: "2.1"

services:
  localstack:
    container_name: test-localstack
    image: localstack/localstack
    ports:
      - "4566-4599:4566-4599"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - SERVICES=${SERVICES- }
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR}
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```

![image](https://user-images.githubusercontent.com/54691710/82312005-0d768900-99f9-11ea-8887-ac0eddaf8d8b.png)

## also having an issue when i run localstack start

![image](https://user-images.githubusercontent.com/54691710/82337685-a2d84400-9a1e-11ea-8fe6-f04e564ea855.png)

**Comment by mrangel** [comment]
I'm having the same issue, usually stops updating status when I have dynamo, s3 or kinesis (so far that I can test)

**Comment by whummer** [comment]
Thanks for reporting @justinlazaro-iselect . Can you please try a `pip install --upgrade --no-cache localstack` - the `subprocess32` dependency has been removed in the latest version, so this issue should be fixed, hopefully. Also, it would be advisable to upgrade to a more recent version of Python, as 2.x has reached its end of life by now.

Can you please try to trim it down to a particular service that's not starting up? As `mrangel` mentioned, dynamodb, kinesis or some other particular service may be the issue here. You can use the `SERVICES` environment variable to define the services to start up. Thanks for your help in resolving this!

**Comment by justinlazaro-iselect** [comment]
@mrangel please check this

![image](https://user-images.githubusercontent.com/54691710/83082349-c30aa180-a0b5-11ea-8232-e2b1501c779a.png)

**Comment by mrangel** [comment]
I've migrated my issue reporting to https://github.com/localstack/localstack/issues/2457, as it may not coincide with my issues. Please let me know if my issue is a dupe or if I should continue to post updates there.

**Comment by mrangel** [comment]
@justinlazaro-iselect looks like your services are marked as 'Ready' (as per the bottom of your terminal)

**Comment by whummer** [comment]
Thanks for the update @justinlazaro-iselect  @mrangel . Looks like the services are up and running - the error/warning message you're seeing is related to missing file permissions in your environment. This should not impact the functionality, though. Please report here if the problem persists in the `latest` version of the Docker image. Thanks
