### ISSUE TITLE
SNS/SQS publish hangs for ~30 seconds using edge port

### ISSUE THREAD

**Issue by lukoyanov** [localstack/localstack#2496]
[X] bug report

# Detailed description
When SNS publish using java AWS Sdk v2.13.9 is done via universal edge port operation is succeed, but hangs for ~30 seconds before API call returns.

Notes:
1. When using old port everything woks smoothly.
2. aws cli works fine (without this 30s delay).
3. Receiving messages from SQS also suffer from this delay.

...

## Expected behavior
Api call to sns publish (and sqs receive) doesn't not suffer from a delay.

## Command used to start LocalStack
localstack is started via terraform:
```hcl
resource "docker_container" "localstack" {
  image   = docker_image.localstack.name
  name    = var.container_name
  env = [
    "SERVICES=sns,sts,sqs",
    "USE_SSL=false",
    "AWS_ACCESS_KEY_ID=localstack-access-key",
    "AWS_SECRET_ACCESS_KEY=localstack-access-key",
    "PORT_WEB_UI=${var.localstack_web_port}",
    "DOCKER_HOST=${var.docker_host}",
    "DEFAULT_REGION=${var.aws_region}",
    "HOST_TMP_FOLDER=${var.localstack_tmp_dir}",
    "DATA_DIR=${var.localstack_tmp_dir}/data",
    "DEBUG=1"
  ]
...
}
```

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
```scala
 val publishRequest =
      awsUtils
        .getTopicArn(topicName)
        .map {
          topicArn =>
            PublishRequest
              .builder()
              .message(eventMeta.codec(event).noSpaces)
              .messageAttributes(
                Map(
                  EventKeys.versionId -> versionIdAttr,
                  EventKeys.eventType -> eventTypeAttr,
                ).asJava
              )
              .topicArn(topicArn)
              .build
        }

    publishRequest
      .flatMap(request => fromFuture(awsUtils.snsClient.publish(request)))
      .map(_.messageId())
      .flatMap(messageId => logger.debug(s"Successfully published $event with messageId=$messageId"))
      .void
```
...

**Comment by whummer** [comment]
Thanks for reporting @lukoyanov . We've made some substantial improvements to the API proxy layer recently (including more stable HTTP/2 support), so we believe this issue should be fixed in the meantime.

There is also a small set of integration tests to cover SNS message publishing here: https://github.com/localstack/localstack-java-utils/blob/master/src/test/java/cloud/localstack/awssdkv2/BasicFeaturesSDKV2Test.java#L65-L80 

Closing this issue as resolved for now - but please report here if the problem persists with the `latest` version of the Docker image. Thanks!
