### ISSUE TITLE
Localstack Lambda service does not accept python3.6 f-string syntax

### ISSUE THREAD

**Issue by njcongtou** [localstack/localstack#264]
I found Localstack Lambda service does not accept python3.6 f-string syntax. 

I have created a simple Lambda python below. 

```
import json
print('Loading function')
def lambda_handler(event, context):
    #print("Received event: " + json.dumps(event, indent=2))
    event2 = {"Records": [3,4,5]}
    print(f'Successfully processed {len(event2["Records"])} records.')
    return event['key1']  
```

An error occurred (Exception) when calling the CreateFunction operation: Unknown error: ('Unable to get handler function from lambda code.', SyntaxError('invalid syntax', ('/tmp/localstack/lambda_script_l_3c0ba2ea.py', 9, 69, '    print(f\'Successfully processed {len(event2["Records"])} records.\')\n')))

**Comment by njcongtou** [comment]
I found local lambda's runtime is 2.7. Could you please do a upgrade to 3.6 ? Most of our Lambda are written in 3.6 syntax. Thanks !

**Comment by njcongtou** [comment]
I found Lambda runtime is 2.7 here. 
https://github.com/localstack/localstack/blob/master/localstack/services/awslambda/lambda_api.py

**Comment by whummer** [comment]
Thanks for reporting @njcongtou . I'm assuming you're using LocalStack in Docker with the `LAMBDA_EXECUTOR=docker` configuration? This issue is fixed in #270 - a simple test case has been added to assert that Python 3 Lambdas work. Can you please give it a try with the latest version of the Docker image? Thanks

**Comment by njcongtou** [comment]
am I not using latest Docker image ? Here is my docker compose config for Localstack. 

  localstack:
    image: localstack/localstack
    ports:
      - "4567-4582:4567-4582"
      - "8080:8080"
    environment:
      - SERVICES=${SERVICES-lambda, kinesis}
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - ".:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

**Comment by njcongtou** [comment]
Thanks for quick fix. I have tested with `LAMBDA_EXECUTOR=docker configuration` and it works. It does not work without this configuration and it still complains syntax error. What this configuration means and why I have to use it ? I was always leaving this empty.

Here is my current configuration. 

  localstack:
    image: localstack/localstack
    ports:
      - "4567-4582:4567-4582"
      - "8080:8080"
    environment:
      - SERVICES=${SERVICES-lambda, kinesis}
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-docker}
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - ".:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

**Comment by whummer** [comment]
The problem is that inside the LocalStack main Docker container we're using Python 2.7. Therefore, if we run the lambda code durectly in the main container, it fails with a syntax error.

The configuration LAMBDA_EXECUTOR=docker causes LocalStack to run the lambdas in a _separate_ Docker container (where we can switch between python versions).

One solution would be to upgrade python from 2.7 to 3.x in the main Docker image. That would probably break some existing tests because python 3 is not fully backward compatible with 2.x (e.g., `print foo` vs `print(foo)`). However, it's probably better to have 2.x tests failing rather than 3.x tests failing.

**Comment by njcongtou** [comment]
OK. thanks for your fix since it solves my issue.

**Comment by ltomes** [comment]
@whummer  is this still the case? We must use `LAMBDA_EXECUTOR=docker` or `LAMBDA_EXECUTOR=docker-reuse` with a python3.* lambda?
Or can we use `LAMBDA_EXECUTOR=local` with python3.* code at this point?
Here:
https://github.com/localstack/localstack/blob/master/localstack/services/awslambda/lambda_api.py it looks like python 2.7-3.6 may be supported with local, but 3.8 is not?
