### ISSUE TITLE
Local Stack: API Gateway

### ISSUE THREAD

**Issue by RSHUKL01** [localstack/localstack#2680]
I was trying to check the feasibility of API gateway and SNS service.
•	First, I have create an SNS topic and configure a subscription to send messages to your cell phone for testing.
•	Then, I have create the basic elements of our API Gateway REST API.
•	Finally, connect our REST API to our SNS topic via an API Gateway service proxy integration.

Command Used:
aws sns create-topic --name service-proxy-topic  --output text  --query 'TopicArn' --enpoint-url=http://localhost:443
Then Error in the below command when subscribing the number:
aws sns subscribe --topic-arn arn:aws:sns:us-east-1:000000000000:service-proxy-topic --protocol sms --notification-endpoint +918939966466 --endpoint-url=http://localhost:443
Error: WARNING:localstack.services.sns.sns_listener: Unexpected protocol "sms" for SNS subscription

@whummer  Can you please help?

**Comment by whummer** [comment]
Thanks for reporting @RSHUKL01 . Please note that SMS delivery for SNS subscriptions is not supported, as we would have to rely on an external service to support such a feature (i.e., it cannot be done purely locally). What would be the expected behavior in this case, from your point of view? We can update the log message and add more details to it, if that is what you are asking for.

I'm going to mark this issues as "won't fix", but if you have some suggestions on how to integrate an actual SMS sending API from an external provider, then please report here or please propose a pull request - PRs are always greatly appreciated. Thanks!

**Comment by RSHUKL01** [comment]
@whummer yes we should update the log and response that we are getting after hitting the end point
