### ISSUE TITLE
Publish image version (tag) to dockerhub

### ISSUE THREAD

**Issue by Veetaha** [localstack/localstack#2846]
Hi, @whummer, I'd like to ask you to publish the image with a new tag (`0.11.4` or `0.12.0`) to dockerhub.
There are a bunch of crucial bugs fixed in the `latest` image (and it also seems to be 2 times smaller in size?).

![image](https://user-images.githubusercontent.com/36276403/90316894-21fdeb00-df2e-11ea-9a80-dca9e2c537ce.png)

**Comment by whummer** [comment]
Hi @Veetaha - thanks for pointing this out. In fact, we recently released a new version `0.11.4`, but the image did not get pushed in our CI due to some small issues (because we had a merge commit right after the release commit, which is unexpected).

We have now updated the builds, and a new version `0.11.4` is now available on Docker Hub. Thanks
