### ISSUE TITLE
ChangeMessageVisibility 400 with concurrent delete

### ISSUE THREAD

**Issue by yaitskov** [localstack/localstack#2892]
```
awslocal sqs create-queue --queue-name "myq"

awslocal sqs send-message --queue-url http://localhost:4576/000000000000/myq \
  --message-body "hello world"

MYQ=http://localhost:4576/000000000000/myq
awslocal sqs create-queue --queue-name "myq"
awslocal sqs send-message --queue-url $MYQ --message-body "hello world"
RH=$(awslocal sqs receive-message --queue-url $MYQ \
          | grep ReceiptHandle | sed -r  's/ +"[^"]+": "([a-z]+)", */\1/')
awslocal sqs change-message-visibility --queue-url  $MYQ \
  --receipt-handle $RH --visibility-timeout 90 &
awslocal sqs delete-message --queue-url $MYQ --receipt-handle $RH

```

**Comment by whummer** [comment]
Hi @yaitskov , thanks for reporting. Please note that the order of events is indeterministic if we start commands concurrently via `&`. May I ask - is there a reason for running these commands in parallel? Not sure if this is a legitimate issue/bug in LocalStack or rather an issue related to usage. What would you expect to be the proper behavior in this case, or how does real AWS behave in such a situation - I would assume it also raises a 400/404 error? Thanks

**Comment by whummer** [comment]
Any update on this issue @yaitskov ? As mentioned above, I'm not sure what the expected behavior should be here, given that you are running commands in parallel here. Closing this one as "not a bug" for now - but please feel free to re-open or provide more details if the problem persists (and if there is a clear discrepancy between LocalStack and real AWS). Thanks
