### ISSUE TITLE
Lambda AWS_REGION not provided in Go docker container.

### ISSUE THREAD

**Issue by Lastin** [localstack/localstack#2951]
# Type of request: This is a ...
[x] bug report
[ ] feature request

# Detailed description
In actual production environment providing AWS_REGION is invalid giving `Reserved keys used in this request: AWS_REGION (Service: AWSLambdaInternal; Status Code: 400; Error Code: InvalidParameterValueException`

## Expected behavior
AWS_REGION being provided as defined in `provider`
...

## Actual behavior
AWS_REGION missing

# Steps to reproduce
## Command used to start LocalStack
...

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
...

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-256) by [Unito](https://www.unito.io/learn-more)

**Comment by whummer** [comment]
Thanks for reporting @Lastin . Can you please provide a few more details about your environment - ideally a small snippet of code or sample project to help us reproduce this issue?

> AWS_REGION being provided as defined in `provider`

Can you please elaborate - are we talking about the `provider` of a serverless.yml configuration file?

Thanks

**Comment by evbo** [comment]
@whummer yes the problem persists. Here's the error AWS will give if you try to provide `AWS_REGION` env var:

> │ Error: error creating Lambda Function (1): InvalidParameterValueException: Lambda was unable to configure your environment variables because the environment variables you have provided contains reserved keys that are currently not supported for modification. Reserved keys used in this request: AWS_REGION
│ {
│   RespMetadata: {
│     StatusCode: 400,
│     RequestID: "9c9cab4f-85cb-4fc3-8772-4f9e3da1c1f4"
│   },
│   Message_: "Lambda was unable to configure your environment variables because the environment variables you have provided contains reserved keys that are currently not supported for modification. Reserved keys used in this request: AWS_REGION",
│   Type: "User"
│ }
│ 

As the OP asserted, LocalStack does not enforce this requirement so it would be great if it did. I am using LocalStack container with version:

> LOCALSTACK_VERSION=1.4.0-arm64

And running the latest Lambda feature: 
> PROVIDER_OVERRIDE_LAMBDA=asf

**Comment by evbo** [comment]
Note there are several reserved environment variables LocalStack should reserve as well: https://docs.aws.amazon.com/lambda/latest/dg/configuration-envvars.html
