### ISSUE TITLE
Localstack cloudfront could not resolve host

### ISSUE THREAD

**Issue by SimFerrer** [localstack/localstack#3042]
# Type of request: This is a ...

[ X] bug report
[ ] feature request

# Detailed description

When i create my cloudfront distribution I am not able to access it

## Expected behavior

...

## Actual behavior

...

# Steps to reproduce

## Command used to start LocalStack

```
localstack:   
     image: localstack/localstack:0.11.5
    ports:
      - "53:53"
      - "4566-4700:4566-4700"
      - "8083:80"
    environment:
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - SERVICES=s3, cloudwatch, logs, cloudfront, elasticache
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - DNS_LOCAL_NAME_PATTERNS='.*cloudfront\.net'
      - DEFAULT_REGION=eu-west-1
```

`docker-compose up -d --build`

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

`aws s3 mb s3://bucket2 --endpoint-url http://localhost:4566 --region eu-west-1`
`aws s3 cp /tmp/hello.txt s3://bucket2/hello.txt --acl public-read --endpoint-url http://localhost:4566 --region eu-west-1`
`aws cloudfront create-distribution --origin-domain-name bucket2.s3.amazonaws.com --endpoint-url http://localhost:4566 --region eu-west-1`

My distribution
{
    "Distribution": {
        "Id": "f381f709",
        "ARN": "arn:aws:cloudfront::000000000000:distribution/f381f709",
        "DomainName": "f381f709.cloudfront.net",
...

```
curl f381f709.cloudfront.net/hello.txt
curl: (6) Could not resolve host: f381f709.cloudfront.net
```

**Comment by SimFerrer** [comment]
Hello @whummer, I saw you added a label 'configuration', I just wanna know if it's a configuration issue on my end

**Comment by whummer** [comment]
Hi @SimFerrer , thanks for reporting this issue. In order to use the `xxx.cloudfront.net` address locally, the local DNS server needs to be configured in the local system - e.g., by adding `127.0.0.1` as a nameserver entry to `/etc/resolve.conf` under Linux.

Alternatively, if you are not using the local DNS setup, you could also try setting the `CLOUDFRONT_STATIC_PORTS=1` environment variable - this will expose your CloudFront distribution on a separate port which can then be called directly on `localhost:xxxx`. Hope that helps - please keep us posted. Thanks!

**Comment by SimFerrer** [comment]
I can access my cloudfront url with the `CLOUDFRONT_STATIC_PORTS` environment variable.

I have another problem on cloudfront but I will go directly through the slack to solve it

Thank you very much @whummer,

**Comment by ptrhck** [comment]
@whummer Is the `CLOUDFRONT_STATIC_PORTS` variable still supported?
