### ISSUE TITLE
ElasticSearch Domain still on port 4571. But start take much time

### ISSUE THREAD

**Issue by rodion-andreev-d8** [localstack/localstack#3075]
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description

Usually we defined port for ElasticSearch Domain. But with latest version, as it said, localstack exposes one universal port for every service.

I've adjusted es like it shown below 
![image](https://user-images.githubusercontent.com/66254512/95216170-6f922800-07fa-11eb-92af-5b27206d0a24.png)
 
and run script for domain creating like this 

![image](https://user-images.githubusercontent.com/66254512/95216416-b54ef080-07fa-11eb-99ec-f4d8bca395cb.png)

and that what i saw in console

![image](https://user-images.githubusercontent.com/66254512/95216589-eaf3d980-07fa-11eb-95e8-f44ec343df7f.png)

As a result i adjusted me services to call port 4571. But it's unavialable. 

But if i  wait for 3-4 minutes this meassge appears in docker comsole 

![image](https://user-images.githubusercontent.com/66254512/95216991-6190d700-07fb-11eb-9073-cae36f432464.png)

and this endpoint for elasticsearch becomes avialable and working as expected.

## Expected behavior

1. Working thorugh one 4566 port or
2. Make 4571 port for ES be avialable quicker

## Actual behavior

1. Es domain still working on  4571
2. We should wait much time to wait while it become avialable 

# Steps to reproduce

Described earlier

## Command used to start LocalStack

docker-compose up

**Comment by whummer** [comment]
Thanks for reporting @rodion-andreev-d8 . Please note that the latest `localstack/localstack` image does not contain Elasticsearch pre-installed (to keep the image size small), hence the required dependencies are downloaded on-demand (and then cached locally). Therefore, the initial startup can take some time.

To improve the startup time, you can try using the `localstack/localstack-full` Docker image and then selecting the default Elasticsearch version. 

In terms of the port - it turned out that routing Elasticsearch requests through the edge port would probably be too tricky, as it is hard to find a reliable way to distinguish Elasticsearch request from other requests (based on path, headers, etc). Therefore, we're using a separate port (`4571` by default) for Elasticsearch.

Hope that helps, please keep us posted.

**Comment by rodion-andreev-d8** [comment]
Thnx whummer. 
I've suspected smth about it. Cuz i saw that ES installed additionaly in old version. But it was visible in contrast to the current flow. That's why confused me a little.
Also there is some misunderstanding between edge port and etc. Maybe it will be good to mark that ES still avialable on other port which doesn't related to edge port. That's only my thoughts :)
Ok, thnx for all.

**Comment by fvcaputo** [comment]
@rodion-andreev-d8 were you able to connect to this new port? I was able to create the domain but it seems that every request I try to do I always receive a 500 status code. I have noticed that if I do `aws es describe-elasticsearch-domain ...` the result still shows `"Created": false` and I'm wondering if it can be related to this.

**Comment by rodion-andreev-d8** [comment]
As i shown before, that's nvm amout 4566 port. Cuz when you're starting you ES service it's created domain on 4571 port and you should connect on that. Please check my screenshots
