### ISSUE TITLE
Address already in use. JDWP Transport dt_socket failed to initialize.

### ISSUE THREAD

**Issue by avajyy** [localstack/localstack#3104]
# Type of request: This is a ...
[x] bug report
[ ] feature request

# Detailed description
When use `LAMBDA_JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=127.0.0.1:8000` to enable remote debugging using Eclipse, the lambda execution failed due to` Address already in use` Exception.

```
Recoverable error occurred (Error executing Lambda function arn:aws:lambda:eu-central-1:000000000000:function:DummyService-local-dummy: Lambda process returned error status code: 2. Result: . Output:
ERROR: transport error 202: bind failed: Address already in use
ERROR: JDWP Transport dt_socket failed to initialize, TRANSPORT_INIT(510)
JDWP exit error AGENT_ERROR_TRANSPORT_INIT(197): No transports initialized [debugInit.c:750] Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 459, in run_lambda
    result = LAMBDA_EXECUTOR.execute(func_arn, func_details, event, context=context,
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 132, in execute
    return do_execute()
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 119, in do_execute
    raise e
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 107, in do_execute
    result = self._execute(func_arn, func_details, event, context, version)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 256, in _execute
    result = self.run_lambda_executor(cmd, stdin, env_vars=environment, func_details=func_details)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 169, in run_lambda_executor
    raise Exception('Lambda process returned error status code: %s. Result: %s. Output:\n%s' %
Exception: Lambda process returned error status code: 2. Result: . Output:
ERROR: transport error 202: bind failed: Address already in use
ERROR: JDWP Transport dt_socket failed to initialize, TRANSPORT_INIT(510)
JDWP exit error AGENT_ERROR_TRANSPORT_INIT(197): No transports initialized [debugInit.c:750]
```

## Expected behavior
The debugger of Eclipse should be attachted to the JVM and the lambda execution should be stopped at the breakpoint.

## Actual behavior
...

# Steps to reproduce
1. Use docker-compose.yml

version: '3'

```
services:
   localstack:
      privileged: true
      image: localstack/localstack:0.11.0
      ports:
      - 4566:4566
      - 4571:4571
      - ${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}
      environment:
      - DEFAULT_REGION=eu-central-1
      - SERVICES=${SERVICES-}
      - DEBUG="1"
      - DATA_DIR=/tmp/localstack/data
      - PORT_WEB_UI=${PORT_WEB_UI-}
      - LAMBDA_EXECUTOR=docker-reuse
      - LAMBDA_JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=127.0.0.1:8000
      - DOCKER_HOST=unix:///var/run/docker.sock
      volumes:
      - localstack-vol:/tmp/localstack
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
   localstack-vol: 
```

1. deploy the lamba function (using serverless)

```
service:
   name: DummyService
plugins:
- serverless-offline
- serverless-pseudo-parameters
- serverless-plugin-include-dependencies
- serverless-localstack
provider:
   name: aws
   runtime: java8
   profile: default
   region: eu-central-1
   versionFunctions: false
   stage: dev
   stackTags:
      PROJECT: ${self:service}
      STAGE: ${opt:stage, self:provider.stage}
package:
   artifact: target/dummy.jar
functions:
   dummy:
      handler: com.serverless.dummy.DummyHandler
      description: Dummy function
      memorySize: 512
      timeout: 30
      events:
      -  http:
            path: dummy
            method: get
custom:
   localstack:
      debug: true
      stages:
      - local
      host: http://localhost
   stages:
   - local
   - dev
   - qs
   - prod
```

1. invoke function (using awslocal)

`awslocal lambda invoke --function-name DummyService-local-dummy result.log`

1. apply remote debugging in Eclipse

## Command used to start LocalStack
`docker-compose up
`

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
```
package com.serverless.dummy;

import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Map;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import com.amazonaws.services.lambda.runtime.Context;
import com.amazonaws.services.lambda.runtime.RequestHandler;

public class DummyHandler implements RequestHandler<Map<String, Object>, String> {
   
   private static final Logger LOG = LogManager.getLogger(DummyHandler.class);
   
   @Override
   public String handleRequest(Map<String, Object> input, Context context) {
      LOG.info("input: " + input);
      String awsRequestId = context.getAwsRequestId();
      String msg = String.format("%s|%s|%s", new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(new Date()),
         awsRequestId, "Task not implemented yet!");
      LOG.info("output: " + msg);
      return msg;
   }
   
}
```

...

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-289) by [Unito](https://www.unito.io/learn-more)

**Comment by kenberkeley** [comment]
Got the same issue.

**Comment by whummer** [comment]
Thanks for reporting @avajyy @kenberkeley . This could be potentially fixed in https://github.com/localstack/localstack/pull/3371 - can you please pull the `latest` Docker image and give it another try? Please let us know if the problem persists. Thanks!

**Comment by avajyy** [comment]
@whummer unfortunately the problem still persists. I could not apply the remote debugging in Eclipse:

Connection Type: Standard (Socket Attach)
Host:127.0.0.1
Port:8000

Failed to connect to remote VM. Connection refused.
Connection refused: connect

**Comment by whummer** [comment]
Thanks @avajyy . We have recently added a couple of enhancements around Lambda execution, including support for "stay-open" mode for the `docker-reuse` Lambda executor - see https://github.com/localstack/localstack/pull/4914 . 

Closing for now - please feel free to open a new Github issue with specific steps to reproduce, in case the problem still persists with the `latest` version. Thanks for your help!

**Comment by vadym-sedna** [comment]
unfortunatelly, this issue is still reproducible 
_docker-compose.yml_
`  localstack:
    image: localstack/localstack:0.14.5
    container_name: localstack
    ports:
      - '4566:4566'
      - '35050:35050'
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOSTNAME=localstack
      - HOSTNAME_EXTERNAL=localstack
      - KMS_PROVIDER=local-kms
      - LAMBDA_JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=*:35050
      - LAMBDA_DOCKER_FLAGS=-p 127.0.0.1:35050:35050`
      
From localstack logs:
`2022-09-02T00:40:16.260:INFO:localstack.services.awslambda.lambda_api: Error executing Lambda function arn:aws:lambda:us-east-1:000000000000:function:message-body-service: {"errorType": "InvocationException", "errorMessage": "Lambda process returned error status code: 2. Result: . Output:\nERROR: transport error 202: bind failed: Address already in use\nERROR: JDWP Transport dt_socket failed to initialize, TRANSPORT_INIT(510)\nJDWP exit error AGENT_ERROR_TRANSPORT_INIT(197): No transports initialized [src/jdk.jdwp.agent/share/native/libjdwp/debugInit.c:735]", "stackTrace": ["  File \"/opt/code/localstack/localstack/services/awslambda/lambda_executors.py\", line 1397, in _execute\n    process.run()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/opt/code/localstack/localstack/services/awslambda/lambda_executors.py\", line 1384, in do_execute\n    result = lambda_function_callable(inv_context.event, context)\n", "  File \"/opt/code/localstack/localstack/services/awslambda/lambda_api.py\", line 644, in execute\n    result = lambda_executors.EXECUTOR_LOCAL.execute_java_lambda(\n", "  File \"/opt/code/localstack/localstack/services/awslambda/lambda_executors.py\", line 1489, in execute_java_lambda\n    invocation_result = self._execute_in_custom_runtime(cmd, lambda_function=lambda_function)\n", "  File \"/opt/code/localstack/localstack/services/awslambda/lambda_executors.py\", line 1332, in _execute_in_custom_runtime\n    raise InvocationException(\n"]} Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 533, in run_lambda`
