### ISSUE TITLE
Terraform Stuck Creating AppSync Data Sources

### ISSUE THREAD

**Issue by theBenForce** [localstack/localstack#3383]
# Type of request: This is a ...

[ ] bug report
[x] feature request

# Detailed description

When creating appsync datasources through terraform it determines when the datasource has been created by sending a GET request to `/v1/apis/apiId/datasources/name`. Currently this results in the following error in localstack:

```
WARNING:localstack_ext.services.appsync.appsync_api: Not yet implemented: Unable to find path mapping for GET /v1/apis/37a04c0c/datasources/dummy
```

## Expected behavior

A GET request to `/v1/apis/apiId/datasources/name` should return data source details as defined in the AWS API documentation: https://docs.aws.amazon.com/appsync/latest/APIReference/API_GetDataSource.html

## Actual behavior

Right now an error message is logged in the localstack console and a 404 is returned.

# Steps to reproduce

## Command used to start LocalStack

...

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

...

**Comment by theBenForce** [comment]
@whummer thanks for picking up these issues so quickly!

**Comment by whummer** [comment]
Thanks for reporting @theBenForce . This issue should be fixed in the meantime - can you please pull the `latest` Docker image and give it another try?

Do you think you could share a small snippet of your Terraform script (either here, or via Slack/Email) to help us reproduce the end-to-end scenario and make sure your project can get properly deployed? Many thanks for your help!

**Comment by theBenForce** [comment]
How do I join the slack workspace?

**Comment by whummer** [comment]
@theBenForce Can you please send us an email to `info@localstack.cloud` - we'll share an invite link with you. Thanks
