### ISSUE TITLE
Push a concrete numbered tag whenever you push latest to docker hub

### ISSUE THREAD

**Issue by dradetsky** [localstack/localstack#3503]
# Type of request: This is a ...

[ ] bug report
[x] feature request

# Detailed description

The current latest version of localstack is 0.12.5. I'd like to use this version via docker-compose, but also not have it get updated to 0.12.6 or 0.13.0 or whatever unless I explicitly decide to do so. So given that I can write

```
services:
  localstack:
    image: localstack/localstack-light:0.12.4
```

and this works as expected (runs 0.12.4), I'd like to put the following in my following in my compose file

```
services:
  localstack:
    image: localstack/localstack-light:0.12.5
```

## Expected behavior

Runs version 0.12.5

## Actual behavior

Complains that "manifest not found." (since this tag doesn't actually exist)

## More info 

This isn't exactly unexpected: as we see [here](https://hub.docker.com/r/localstack/localstack-light/tags?page=1&ordering=last_updated) the available tags are `latest`, `0.12.4`, `0.12.3`, and so on. The problem is that `latest` and `0.12.4` should be the same thing. Or if `0.12.4` is not the latest, there should be another tag with a higher semver which is the same as latest.

I don't actually know how to do this offhand, but I know

0. It's very common thing to do with docker image tags.
1. If you had just done `docker build -t localstack/localstack-light:latest ; docker push localstack/localstack-light:latest`, if you subsequently reran the command with `latest` replaced by `0.12.5` I think you'd have a pretty good chance of having the correct thing happen.

**Comment by whummer** [comment]
Thanks for reporting @dradetsky . Turns out that there was an issue in our CI pipeline and the image tag `0.12.5` wasn't actually pushed properly, thanks for letting us know. The `localstack/localstack-light:0.12.5` image has now been pushed and should be available on Docker Hub.

Please note that `localstack/localstack-light` is only an alias for the default `localstack/localstack` image (as opposed to the `localstack/localstack-full` image which is larger and contains more cached libraries). We generally recommend using the default `localstack/localstack` image, as `localstack/localstack-light` may get removed in a future release. Thanks for your help.
