### ISSUE TITLE
Lambda with container support

### ISSUE THREAD

**Issue by accent** [localstack/localstack#3527]
# Type of request: 

Question

# Detailed description

Create new lambda function based on Docker image

```
aws --endpoint-url=http://localhost:4566 lambda create-function --function-name test-local --package-type Image --code ImageUri=IMAGE_URI --role  arn:aws:iam::000000000:role/lambda-ex
```

## Expected behavior

Lambda is created

## Actual behavior

Getting following error:

```
An error occurred (InternalFailure) when calling the CreateFunction operation (reached max retries: 2): Unknown error: 'Handler' Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 991, in create_function
    func_details.handler = data['Handler']
KeyError: 'Handler'
```

# Steps to reproduce

Run localstack on docker-desktop (WSL2).

## Command used to start LocalStack

```
docker run --name localstack -p 4566:4566 --env DATA_DIR="/tmp/localstack" --volume="C:\data\localstackDockerVolumes":"/tmp/localstack" localstack/localstack
```

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

```
aws --endpoint-url=http://localhost:4566 lambda create-function --function-name test-local --package-type Image --code ImageUri=IMAGE_URI --role  arn:aws:iam::000000000:role/lambda-ex
```

**Comment by theodorebourgeon** [comment]
Same behaviour on my side

**Comment by ssofronov** [comment]
Any plans on adding this to the community edition?

On my end I do not get any errors, but when I run the lambda it does not use the provided ImageUri and instead tries to create a container using the DEFAULT_LAMBDA_CONTAINER_REGISTRY i.e. 'lambci/lambda'. Screenshot below (please ignore the 125 error - that is caused because of a firewall config and is not related)

![image001](https://user-images.githubusercontent.com/35382334/107613737-91d8fe00-6c51-11eb-8e43-dc7904e2dc21.png)

**Comment by BenRbtz** [comment]
Just to confirm, will this only be for the pro version (like lambda layers are)?
