### ISSUE TITLE
localstart fails to start with error: No module named 'localstack.services.cloudwatch'

### ISSUE THREAD

**Issue by ValYouW** [localstack/localstack#3569]
Hi,

Installed localstack using pip on WSL Ubuntu 20.04.
Trying to start:
```
export SERVICES=s3,sqs,logs,lambda
localstack start --host
```
Get the error:
```
LocalStack version: 0.12.6
Unable to register plugins: No module named 'localstack.services.cloudwatch'
2021-02-07T04:11:57:WARNING:bootstrap.py: Unable to load plugins from file /home/xxx/.local/lib/python3.8/site-packages/localstack/plugins.py: No module named 'localstack.services.cloudwatch'
```

Checking the folder: /home/xxx/.local/lib/python3.8/site-packages/localstack/services there's indeed no `cloudwatch` module...

Any ideas?
thx

**Comment by whummer** [comment]
Thanks for reporting @ValYouW . This was likely related to a missing `__init__.py` file in the cloudwatch module, which has now been fixed. We have just pushed a new version - can you please try upgrading:
```
pip install 'localstack>=0.12.6.1'
```

Please note that using the `--host` flag directly is actually deprecated these days (because in the past we've had troubles maintaining compatibility with different operating systems, Python versions, etc.). The recommended / supported way of starting LocalStack is within a Docker container (simply running `localstack start`). Hope that helps, please let us know if there are any other issues. Thanks!

**Comment by ValYouW** [comment]
Works thanks.
