### ISSUE TITLE
Support Lambda runtime nodejs14.x

### ISSUE THREAD

**Issue by jansepke** [localstack/localstack#3591]
# Type of request: This is a ...

[ ] bug report
[x] feature request

# Detailed description

Nodejs14 is now supported by AWS could you please also add support for it in localstack.

## Expected behavior

```
awslocal lambda create-function \
  --runtime nodejs14.x
```
will not produce runtime exceptions

**Comment by mgagliardo** [comment]
Hello @jansepke, thanks for reporting this.
As much as we'd love to support nodejs14.x right now, this is a dependency from `lambci`, as far as I could see there were reports already opened on their end [here](https://github.com/dherault/serverless-offline/pull/1170) and [this open issue](https://github.com/lambci/docker-lambda/issues/329). 
Once these are resolved the localstack framework will automatically pull the docker image, you can check their hub [here as well](https://hub.docker.com/r/lambci/lambda) for the latest images.

Cheers!

**Comment by Tohaker** [comment]
Rather than raise a new issue, it relates to this; `lambci/lambda` is effectively abandoned and now that Node16 is supported by AWS, I'd like to run my lambdas similarly in localstack. Are there any plans to move over to another repository, such as https://hub.docker.com/r/amazon/aws-lambda-nodejs/tags ? At the moment, plugging this into the config doesn't work because the tags are different
