### ISSUE TITLE
listObjects doesn't handle url-encoded delimiters

### ISSUE THREAD

**Issue by bperel** [localstack/localstack#3613]
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description

Localstack doesn't seem to handle sending back the list of objects in a bucket if the delimiter passed in the S3 URL is URL-encoded.
In my case the delimiter is "/" which is URL encoded as "%2F" by the AWS PHP SDK.

## Expected behavior

I expect the list of objects to be sent back.

## Actual behavior

Here is the error message that I get from the AWS PHP SDK when trying to list objects:
```
Fatal error: Uncaught exception 'Aws\S3\Exception\S3Exception' with message 'Error executing "ListObjects" on "http://localstack:4566/mybucket?prefix=&delimiter=%2F&encoding-type=url"; AWS HTTP error: Client error: `GET http://localstack:4566/mybucket?prefix=&delimiter=%2F&encoding-type=url` resulted in a `404
Not Found` response:
{"status": "running"}
```

And indeed:
```
# curl "http://localstack:4566/mybucket?prefix=&delimiter=%2F&encoding-type=url"
{"status": "running"}
```

but if I curl Localstack with a non-URL-encoded delimiter parameter then it works:
```
# curl "http://localstack:4566/mybucket?prefix=&delimiter=/&encoding-type=url"
<?xml version="1.0" encoding="UTF-8"?><ListBucketResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Name>mybucket</Name><Prefix></Prefix><MaxKeys>1000</MaxKeys><Delimiter>/</Delimiter><IsTruncated>false</IsTruncated></ListBucketResult>
```

# Steps to reproduce

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

I created a small repo that allows to reproduce the issue: https://github.com/bperel/localstack_delimiter_issue_poc

**Comment by macnev2013** [comment]
Hi @bperel , Thanks for reporting. Apologies for the delay.

While sending a request to `localstack` without authorization headers - it returns application status.
In this case while creating **s3_client** the credentials is set to false -> `'credentials' => false`. Due to which localstack is responding with `{status: running}` (application status) instead of listing the buckets.

**Fix:**
You can add following in the container **init** script for the app **container**:
```
export AWS_ACCESS_KEY_ID=test
export AWS_SECRET_ACCESS_KEY=test
```

S3 client configuration:
```
use Aws\Credentials\CredentialProvider;

// Only load credentials from environment variables
$provider = CredentialProvider::env();

$s3 = new Aws\S3\S3Client([
    'version'     => 'latest',
    'region'      => 'eu-central-1',
    'endpoint' => "http://localstack:4566",
    'credentials' => $provider
]);
```

I hope that helps.

Ref: 
- [Credentials setup](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/guide_credentials_environment.html)
- [Client Configuration](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/guide_configuration.html#credentials)

Please report us if the issue persists.

Thanks.

**Comment by whummer** [comment]
Closing as "should be fixed" - please let us know if the problem persists @bperel  . Thanks
