### ISSUE TITLE
Lambda does not support nodejs v14

### ISSUE THREAD

**Issue by mattsoftware** [localstack/localstack#3644]
# Type of request: This is a ...

[ ] bug report
[x] feature request

# Detailed description

Now that nodejs 14 has been released on lambda, I am trying to test all my functions using nodejs 14. The lambci container that localstack uses does not yet support v14 (https://github.com/lambci/docker-lambda/issues/329). However, the aws backed sam container can be used (https://hub.docker.com/r/amazon/aws-sam-cli-build-image-nodejs14.x/tags?page=1&ordering=last_updated)

I'm not a java developer, so I'm not sure how easy this will be to drop in, but I suspect it would not be too hard (although I also suspect it will not be trivial).

**Comment by mgagliardo** [comment]
Hello Matt. Indeed this change is not trivial and it would imply us managing different images when we have a strong dependency on lambci, this was also [reported here](https://github.com/localstack/localstack/issues/3591#issuecomment-778877755). 
I would take a look at this but at the same time it would imply rolling back everything when lambci deploys their nodejs v14 image.
My suggestion here is to keep on waiting rather than swapping to another image.

**Comment by whummer** [comment]
Thanks for reporting @mattsoftware . A temporary fix has been pushed in #3688 (until v14 will become available in lambci) - can you please pull the `latest` Docker image and let us know if that works for you? Thanks!

**Comment by ellisium** [comment]
hello @whummer, same issue when deploying with cloudFormation. lambda are using runtime nodejs 12
