### ISSUE TITLE
0.12.7 connection issue on Docker

### ISSUE THREAD

**Issue by 3pdev-alex** [localstack/localstack#3673]
# Type of request: This is a ...

[x] bug report
[ ] feature request

Just updated to the docker image 0.12.7 and rebuilt. My docker-compose service:

```
localstack:
    image: localstack/localstack:0.12.7
    restart: always
    ports:
      - 4566:4566
      - 8080:8080
    environment:
      - DOCKER_HOST=unix.///var/run/docker.sock
      - DEFAULT_REGION=us-east-1
      - DEBUG=1
      - PORT_WEB_UI=8080
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - ./logs/localstack/:/tmp/localstack
      - /var/run/docker.sock:/var/run/docker.sock
      - ./localstack/startup/:/docker-entrypoint-initaws.d
    networks:
      - mynetwork
```
When I run `awslocal sqs list-queues` I get `Could not connect to the endpoint URL: "http://localhost:4576/"`. If I change my ports to `"4566-4599:4566-4599"` I get `Connection was closed before we received a valid response from endpoint URL: "http://localhost:4576/".`.

## Expected behavior

I should be able to list my queues as I used to with 0.11.5.

## Actual behavior

I can't.

# Steps to reproduce

## Command used to start LocalStack
docker-compose up

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

Run `awslocal sqs list-queues`

**Comment by mgagliardo** [comment]
Hello @3pdev-alex, thanks for reporting this.
I have tested this with the following docker-compose, please note there's a slight change on the networks part, can you please give it a try and tell me if it is the same for you? Also `awslocal` should not be connecting to `4576` but to `4566` which is the default port for localstack.

```
localstack:
    image: localstack/localstack:0.12.7
    restart: always
    ports:
      - 4566:4566
      - 8080:8080
    environment:
      - DOCKER_HOST=unix.///var/run/docker.sock
      - DEFAULT_REGION=us-east-1
      - DEBUG=1
      - PORT_WEB_UI=8080
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - ./logs/localstack/:/tmp/localstack
      - /var/run/docker.sock:/var/run/docker.sock
      - ./localstack/startup/:/docker-entrypoint-initaws.d
```


```
$ awslocal sqs create-queue --queue-name test
{
    "QueueUrl": "http://localhost:4566/000000000000/test"
}
```

```
$ awslocal sqs list-queues
{
    "QueueUrls": [
        "http://localhost:4566/000000000000/test"
    ]
}
```

**Comment by 3pdev-alex** [comment]
Still doesn't work for me. Any idea what else I can update/try?

**Comment by mgagliardo** [comment]
I know it might sound silly but have you tried restarting your machine?

**Comment by 3pdev-alex** [comment]
Did just before I posted back. 0.11.5 works, but I'm having the issues described here - [SQS purge/delete not working](https://github.com/localstack/localstack/issues/3279)

**Comment by mgagliardo** [comment]
So if you would remove all the tmp data that fixes the issue described there?

**Comment by 3pdev-alex** [comment]
> So if you would remove all the tmp data that fixes the issue described there?

Same situation.

**Comment by 3pdev-alex** [comment]
Following up - I think this is more an issue with awslocal, so I've opened the issue over there. In the meantime I uninstalled it and created a function to simulate awslocal.

`function awslocal(){ aws --endpoint=http://localhost:4566 "$@" }`

**Comment by mgagliardo** [comment]
Is there any chance you have already configured an env var or config on `~/.aws/` that might be pointing your `awslocal` endpoint there?
`awslocal` is just a wrapper of the `awscli`. I guess both are up-to-date? Can you test uninstalling/purging them and reinstalling?

**Comment by 3pdev-alex** [comment]
I've got a few different profiles set up for aws-cli in ~/.aws/config and ~/.aws/credentials, but nothing mentions a port. I tried setting LOCALSTACK_HOST to http://localhost:4566, but then it was attempting to connect to http://localhost:4566:4576. Both aws-cli and awscli-local are up to date.

Unless I created a global at some point and don't remember it, I'm not seeing anything off in my setup other than that it doesn't work properly. Thanks for your help, by the way!

**Comment by arc2021** [comment]
I am using the localstack 0.12.7 version(The docker images is pulled into corporate internal registry). When I run docker-compose up, it says Services are ready but when I hit the url  https://0.0.0.0:4566 or http://localhost:8080 its not working.   I see in many posts this issue was reported but I haven't seen a concrete solution. Can some one please help?

version: "3"
services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack}"
    image: /container-internal/docker.io/localstack/localstack:0.12.7
    hostname: localhost     
    ports:
      - "4566:4566"
      - "4571:4571"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - SERVICES=s3,sqs,lambda,cloudformation,sts,iam,cloudwatch,apigateway,events,kinesis
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - AWS_ACCESS_KEY_ID=blabla
      - AWS_SECRET_ACCESS_KEY=blabla
      - AWS_DEFAULT_REGION=us-east-1        
      - PORT_WEB_UI=9090
      - LAMBDA_EXECUTOR=docker-reuse
      - LAMBDA_REMOTE_DOCKER=false
      - LAMBDA_REMOVE_CONTAINERS=true
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
    - ./scripts/local/localstack-config-fixtures:/opt/code/localstack/localstack-config-fixtures
    - ./scripts/local/localstack-init:/docker-entrypoint-initaws.d
    tmpfs:
      - /tmp/localstack:exec,mode=600
Logs:

I:>docker-compose up
Recreating localstack ... done
Attaching to localstack
localstack    | Waiting for all LocalStack services to be ready
localstack    | 2021-03-11 18:44:48,907 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid t
his message.
localstack    | 2021-03-11 18:44:48,909 INFO supervisord started with pid 12
localstack    | 2021-03-11 18:44:49,912 INFO spawned: 'dashboard' with pid 18
localstack    | 2021-03-11 18:44:49,913 INFO spawned: 'infra' with pid 19
localstack    | 2021-03-11 18:44:49,928 INFO success: dashboard entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
localstack    | 2021-03-11 18:44:49,929 INFO exited: dashboard (exit status 0; expected)
localstack    | (. .venv/bin/activate; exec bin/localstack start --host)
localstack    | 2021-03-11 18:44:50,931 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
localstack    | Starting local dev environment. CTRL-C to quit.
localstack    | LocalStack version: 0.12.7
localstack    | !WARNING! - Looks like you have configured $LAMBDA_REMOTE_DOCKER=0 - please make sure to configure $HOST_TMP_FOLDER to point to your host's $TMPDIR
localstack    | Starting edge router (https port 4566)...
localstack    | 2021-03-11T18:44:54:INFO:localstack.utils.analytics.profiler: Execution of "load_plugin_from_path" took 3541.7890548706055ms
localstack    | 2021-03-11T18:44:54:INFO:localstack.utils.analytics.profiler: Execution of "load_plugins" took 3542.433023452759ms
localstack    | 2021-03-11T18:44:54:DEBUG:bootstrap.py: Loading plugins - scope "services", module "localstack": <function register_localstack_plugins at 0x7f29f89b8040>
localstack    | Starting mock API Gateway service on http port 4566 ...
localstack    | Starting mock CloudFormation service on http port 4566 ...
localstack    | Starting mock CloudWatch service on http port 4566 ...
localstack    | Starting mock DynamoDB service on http port 4566 ...
localstack    | Starting mock DynamoDB Streams service on http port 4566 ...
localstack    | Starting mock IAM service on http port 4566 ...
localstack    | Starting mock STS service on http port 4566 ...
localstack    | Starting mock Kinesis service on http port 4566 ...
localstack    | Starting mock Lambda service on http port 4566 ...
localstack    | Starting mock CloudWatch Logs service on http port 4566 ...
localstack    | Starting mock S3 service on http port 4566 ...
localstack    | ERROR: 'docker ps -a --filter="name=localstack_lambda_*" --format "{{.Names}}"': exit code 1; output: b''
localstack    | Starting mock SQS service on http port 4566 ...
localstack    | Starting mock Cloudwatch Events service on http port 4566 ...
localstack    | Listening at http://:::45861
localstack    | Initializing DynamoDB Local with the following configuration:
localstack    | Port:   45278
localstack    | InMemory:       false
localstack    | DbPath: /tmp/localstack/data/dynamodb
localstack    | SharedDb:       false
localstack    | shouldDelayTransientStatuses:   false
localstack    | CorsParams:     *
localstack    |
localstack    | 2021-03-11T18:44:54:INFO:localstack.multiserver: Starting multi API server process on port 40898
localstack    | [2021-03-11 18:44:54 +0000] [20] [INFO] Running on https://0.0.0.0:4566 (CTRL + C to quit)
localstack    | [2021-03-11 18:44:54 +0000] [20] [INFO] Running on http://0.0.0.0:40898 (CTRL + C to quit)
localstack    | 2021-03-11T18:44:54:INFO:hypercorn.error: Running on https://0.0.0.0:4566 (CTRL + C to quit)
localstack    | 2021-03-11T18:44:54:INFO:hypercorn.error: Running on http://0.0.0.0:40898 (CTRL + C to quit)
localstack    | 2021-03-11 18:44:54,664:API:  * Running on http://0.0.0.0:33900/ (Press CTRL+C to quit)
localstack    | 2021-03-11T18:44:54:DEBUG:localstack.services.awslambda.lambda_executors: Getting all lambda containers names.
localstack    | 2021-03-11T18:44:54:DEBUG:localstack.services.awslambda.lambda_executors: docker ps -a --filter="name=localstack_lambda_*" --format "{{.Names}}"
localstack    | Waiting for all LocalStack services to be ready
localstack    | Waiting for all LocalStack services to be ready
localstack    | Ready.
