### ISSUE TITLE
Documented steps on integration testing (on python codebases) is not updated

### ISSUE THREAD

**Issue by mt-kelvintaywl** [localstack/localstack#3804]
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description

When running the integration test example (See https://github.com/localstack/localstack#integration-with-nosetests), such that:

```py
import pytest
from localstack.services import infra


def setup_function(_function):
    print("SETTING UP")
    infra.start_infra(asynchronous=True, apis=["s3"])


def teardown_function(_function):
    print("TEARING DOWN")
    infra.stop_infra()


def test_integration():
    assert True
```

This fails as it turns out a lot of dependencies are required to use `localstack.services.infra.start_infra` under the hood.

Specifically, I had to install the following in order to execute the above successfully.

```diff
# snippet from my Pipfile
[dev-packages]
pytest = "*"
localstack = "*"
+ flask-cors = "*"
+ h11 = "*"
+ quart = "*"
+ amazon-kclpy = "*"
```

Of course, i am using Pytest in my case, but i believe that should not matter 🤓 .

My question would be: is the example for running integration tests still relevant?

The suggested file to reference from https://github.com/localstack/localstack/blob/master/tests/integration/test_integration.py, seems to be set up differently.

## Expected behavior

- Instructions on README to be correct and updated.
- Additional dependencies required to be documented.

**Comment by pinzon** [comment]
Hi @mt-kelvintaywl, thank you for bringing this to our attention and your patience. 
To answer your question directly: No, that segment about the test is not relevant any more, since Localstack generally only supports running inside a Docker container and not on the host machine directly.

Currently I'm working on this [utility](https://github.com/localstack/localstack-utils) that allows the user to integrate localstack(inside a docker container) with the tests, pretty similar to [localstack/localstack-java-utils](https://github.com/localstack/localstack-java-utils).

So in simple terms you could write something like this with the new utility:
```
import time
import boto3
import unittest
from localstack import startup_localstack, stop_localstack
class kinesis_test(unittest.TestCase):
        def setUp(self):
            startup_localstack()
            session = boto3.session.Session()

        def tearDown(self):
            stop_localstack()
            return super().tearDown()

        def test_create_stream(self):
            kinesis = boto3.client(
                service_name='kinesis',
                aws_access_key_id='test',
                aws_secret_access_key='test',
                endpoint_url='http://localhost:4566')

            kinesis.create_stream(StreamName='test', ShardCount=1)
            time.sleep(10)

            response = kinesis.list_streams()
            self.assertGreater(len(response.get('StreamNames', [])),0)
```

I'll be closing this issue when that util is completly approved and I have edited the readme section about the tests.

**Comment by whummer** [comment]
Thanks @mt-kelvintaywl @pinzon . This has been updated in the meantime - please let us know if anything is missing. Thanks!
