### ISSUE TITLE
Persistence vs SQS Long Polling - Persistence enabling per service?

### ISSUE THREAD

**Issue by Nevett** [localstack/localstack#3881]
# Type of request: This is a ...

[x] bug report
[x] feature request

I think this is a bug in that it is behaviour that will cause a bad experience for many developers, and I'm suggesting a feature change that would allay it.

# Detailed description

We use [SQS Long Polling](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-short-and-long-polling.html) (specifying `WaitTimeSeconds` when making a `ReceiveMessages` call) within our application. Long Polling means the SQS API will not respond for that many seconds, or until it has messages to return.

We use Localstack for local development, and want to enable persistence (primarily for S3 which we also use via Localstack).

Since Localstack's SQS persistence is based on recording and replaying requests, it replays each long polling request on boot, which leads to startup time taking hours if there have been many such requests recorded. It's common to have message consumers forever loop making long polling requests as they wait for messages, and I imagine many other developers' SQS workflows will come up against this problem when trying Localstack's persistence feature.

I can forsee other issues with the persistence model used for SQS. One example is that we make heavy use of Visibility Timeouts, where the behaviour of the SQS service will differ when replaying the requests at maximum speed versus spread out over time in the real world scenario. Overall we would prefer to be able to disable persistence for SQS while keeping it for other services, as we have doubts about whether it would reliably reproduce the correct state of the queues, and fortunately our use case doesn't demand persistence for SQS.

# Suggested resolutions

## Opt-in to persistence per service

In our case, we don't really need/want SQS persistence, but very much need it for S3. It would be great it we could opt-in/out services from the persistence mechanism, which would avoid this problem for us. e.g. a `PERSISTED_SERVICES=s3` environment variable.

## Discard / transform long polling requests from persistence

There might be a partial solution available in dropping the WaitTimeSeconds parameter from ReceiveMessages requests, it's unlikely to be useful in this replay scenario as there are no other producers to the queue when replaying, so there is no need to wait for messages (notwithstanding messages published with visibility timeouts)

**Comment by whummer** [comment]
Thanks for the detailed report @Nevett , and apologies for the long delay.

Unfortunately, we've come to realize that the "record&replay" based persistence mechanism (storing API calls to `recorded_api_calls.json` and re-running them on restart) has many conceptual flaws which cannot be easily addressed in a robust and generic way. In fact, this persistence mechanism has created more problems and headaches than benefits for most users recently (as indicated in your report as well). 

Due to these fundamental issues, we have decided to **discontinue support for the record&replay based legacy persistence**. Please find more details in the release notes for version 0.13.1: https://github.com/localstack/localstack/releases/tag/v0.13.1 . We have introduced an environment variable `LEGACY_PERSISTENCE` which can be used to continue using the legacy persistence; currently the default setting is still `LEGACY_PERSISTENCE=1` (i.e., no changes required on your end), but this option may default to `LEGACY_PERSISTENCE=0` in an upcoming release.

The recommended solution/workaround for now is to disable the `DATA_DIR` configuration, and instead use init scripts to pre-populate your LocalStack instance with the required state at startup (see documentation around `INIT_SCRIPTS_PATH`/`/docker-entrypoint-initaws.d` in the README). We hope that helps reduce the headaches around `KeyError`, slow startups, flooding of persistence files with SQS long polling API calls, and other issues introduced by the legacy persistence.. Thanks for your support!
