### ISSUE TITLE
API Gateway OPTIONS not implemented.

### ISSUE THREAD

**Issue by vangorra** [localstack/localstack#399]
Looks like API Gateway doesn't support the OPTIONS HTTP method. When I run a call against localstack's apigateway endpoint, I get the following error.

```
{"message": "API Gateway integration type \"MOCK\" for method \"OPTIONS\" not yet implemented"}
```
Understandably this is a feature request but an important one. Most common browser run a preflight check with OPTIONS against your api prior to running a GET/POST. Without OPTIONS, this complicates things.

**Comment by whummer** [comment]
Thanks for reporting @vangorra - this should be fixed in #418 . As a temporary solution we're returning "allow-all" CORS headers on every OPTIONS requests. Note that this is strictly speaking not compatible with AWS - their API requires you to explicitly set an `OPTIONS` method on your resource to return the CORS headers: http://docs.aws.amazon.com/apigateway/latest/developerguide/how-to-cors.html . But 

But I get the point that this is a convenience feature. Closing this issue now, please re-open if there are any other issues related to CORS headers. Thanks

**Comment by vangorra** [comment]
That should be an acceptable work around for now. In my docker compose stack, I have an nginx server that proxies localstack and returns something very similar.

**Comment by vangorra** [comment]
Just tested this now. I'm getting a 404 when calling OPTIONS on the api gateway url. I can run curl requests against my endpoint correctly, only OPTIONS method returns a 404.
```
user@host:/code$ curl -I -X OPTIONS http://localstack-core:4567/restapis/5A-Z18A-Z07A-Z22/local/_user_request_/serviceName
HTTP/1.1 404 Not Found
Server: BaseHTTP/0.3 Python/2.7.13
Date: Fri, 03 Nov 2017 17:06:33 GMT
Content-Length: 95
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: HEAD,GET,PUT,POST,DELETE,OPTIONS,PATCH
Access-Control-Allow-Headers: authorization,content-type,content-md5,x-amz-content-sha256,x-amz-date,x-amz-security-token,x-amz-user-agentReferrer Policy:no-referrer-when-downgrade
```
