### ISSUE TITLE
Unclear how persistent data and `DATA_DIR` should be used

### ISSUE THREAD

**Issue by synfinatic** [localstack/localstack#4070]
# Type of request: This is a ...

[ ] bug report
[ X] feature request

# Detailed description

`DATA_DIR` feature is missing important documentation:

 1. How best to tell if persistent data is compatible with Community or Pro?  It appears that persistence data is not compatible and no error is generated- it is just silently ignored?
 2. does the `.localstack` which only exists in Pro community data contain sensitive information (ie: passwords, license, keys, etc).  Example contents: ```{"cached_key": {"timestamp": 1621385230, "key_hash": "XXXXXXXX", "key": "ZZZZZZZZ"}, "machine_id": "YYYYYY"}```
 3. Are all files in DATA_DIR important for sharing state between one container and another?  Example is the directory `azure-api-specs` necessary for AWS?  What about logs?

## Expected behavior

Enough information so that we can use data persistence between containers to initialize a baseline for unit/system tests.

## Actual behavior

Questions.

# Steps to reproduce

## Command used to start LocalStack

Create persistence directory using Pro and use in Community or vice-versa.   Persistent data is not used when container license changes.

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

N/A

**Comment by whummer** [comment]
Thanks for reporting @synfinatic , and apologies for the long delay. Please note that we've recently introduced a new `Directories` abstraction in the code (see [here](https://github.com/localstack/localstack/blob/5d4f668724c77d6cbe4f9478450bd29e99324562/localstack/config.py#L34-L59)) which should make the use of the different directories a bit more explicit and clear in the future. Most of the directories are for internal use only and should not affect the user, but we'll make sure to better highlighe the relevant directories (in particular around DATA_DIR) in our documentation. 👍 

Regarding persistence - as you correctly pointed out, there are two distinct persistence mechanisms: the legacy persistence in Community (based on API calls record&replay), and the advanced persistence mechanism in Pro (building the basis for our Local Cloud Pods feature). In our [release notes for the 0.13.1 release](https://github.com/localstack/localstack/releases/tag/v0.13.1) we have introduced a `LEGACY_PERSISTENCE` flag, which indicates that the legacy persistence will not be supported going forward, due to its inherent conceptual flaws which are hard to fix in a proper way (various issues have been created in Github, and the legacy persistence has caused lots of headache for users in the past).

Regarding your concrete questions:

> * How best to tell if persistent data is compatible with Community or Pro? 

The approaches are not compatible with each other, but co-exist side-by-side. If you're using Pro, it stores the state primarily into an `api_states` folder in `DATA_DIR`, whereas the legacy persistence stores the API calls to a `recorded_api_calls.json` JSON file.

> * Does the .localstack which only exists in Pro community data contain sensitive information

That is correct - the cache files/folders in `~/.localstack` may contain sensitive information, and are not relevant for the persistence mechanism. In particular, these files should not be checked in to source control (hence, we are deliberately storing them in the home directory, and not inside `DATA_DIR`)

> * Are all files in DATA_DIR important for sharing state between one container and another? Example is the directory azure-api-specs necessary for AWS? What about logs?

Yes, in general the entire content in `DATA_DIR` would be relevant for sharing the application state. Over time, we are actually planning to remove the dependency on `DATA_DIR`, and instead make Local Cloud Pods the first class citizen for storing persistent state that can then be versioned and shared across team members, CI systems, etc. We are working on introducing the necessary abstractions now - we'll announce more features in that area soon, stay tuned. 

Hope that helps clarify things a bit - if you have more specific questions, please feel free to reach out directly (ideally via Slack). We'll continue to update our documentation to better highlight these details. Thanks!
