### ISSUE TITLE
S3 does not preserve `LastModified` timestamp

### ISSUE THREAD

**Issue by p-himik** [localstack/localstack#4077]
# Type of request: This is a ...

- [x] bug report
- [ ] feature request

# Detailed description
LocalStack does not preserve `LastModified` timestamps of S3 objects.

I see that there's explicit code in `s3_listener.py:append_last_modified_headers` that _might_ be doing it.
But I have no idea why `LastModified` isn't saved in the first place.
Perhaps, it's as intended and this discrepancy with AWS S3 is deliberate. In this case, this is a feature request.

# Steps to reproduce
- Start LocalStack container with the S3 service
- Create a bucket there
- Upload an object
- List that object and remember the timestamp
- Restart the LocalStack container
- List the same object and notice that the modification date is now different

## Command used to start LocalStack
```
podman run --name xxx -d -v /local/dir/tmp/localstack/data:/tmp/localstack/data \
  -e SERVICES=s3 \
  -e DATA_DIR=/tmp/localstack/data \
  docker.io/localstack/localstack:latest
```

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
```
$ awslocal s3 mb s3://test
make_bucket: test
$ touch test.txt
$ awslocal s3 cp test.txt s3://test/
upload: ./test.txt to s3://test/test.txt
$ awslocal s3 ls s3://test/test.txt
2021-05-28 08:04:43          0 test.txt
# Restart the container here
$ podman container restart xxx
$ awslocal s3 ls s3://test/test.txt
2021-05-28 08:06:44          0 test.txt
```

**Comment by p-himik** [comment]
It's still an issue.

**Comment by whummer** [comment]
Thanks for the update @p-himik . Please note that this is due to the API call record&replay based persistence mechanism, which is unfortunately broken in many ways - it has hence been [deprecated](https://github.com/localstack/localstack/releases/tag/v0.13.1) and is scheduled to be removed in an upcoming release. (If you want to give it a try, we have a more advanced persistence mechanism in the Pro version.) Thanks!
