### ISSUE TITLE
deleted SQS messages restored upon restarting localstack

### ISSUE THREAD

**Issue by michaelhixson** [localstack/localstack#4168]
# Type of request: This is a ...

[ x] bug report
[ ] feature request

# Detailed description

It seems that if I delete an SQS message, it will stay deleted until I restart the localstack service, then the message will reappear on the queue.

## Expected behavior

Deleted messages should remain deleted after restarting localstack.

## Actual behavior

Here is what I observe over time with `awslocal sqs get-queue-attributes`.

(OK) There's a message on the queue to be processed.
```json
$ awslocal sqs get-queue-attributes --queue-url ...
{
    "Attributes": {
        "ApproximateNumberOfMessages": "1",
        "ApproximateNumberOfMessagesDelayed": "0",
        "ApproximateNumberOfMessagesNotVisible": "0",
```

(OK) My application receives the message, is working on it.
```json
$ awslocal sqs get-queue-attributes --queue-url ...
{
    "Attributes": {
        "ApproximateNumberOfMessages": "0",
        "ApproximateNumberOfMessagesDelayed": "0",
        "ApproximateNumberOfMessagesNotVisible": "1",
```

(OK) My application deletes the message.
```json
$ awslocal sqs get-queue-attributes --queue-url ...
{
    "Attributes": {
        "ApproximateNumberOfMessages": "0",
        "ApproximateNumberOfMessagesDelayed": "0",
        "ApproximateNumberOfMessagesNotVisible": "0",
```

(OK) The queue remains in that state while nothing is happening.

(BAD) I restart localstack, and NotVisible message reappears.
```json
$ awslocal sqs get-queue-attributes --queue-url ...
{
    "Attributes": {
        "ApproximateNumberOfMessages": "0",
        "ApproximateNumberOfMessagesDelayed": "0",
        "ApproximateNumberOfMessagesNotVisible": "1",
```

(BAD) Soon, that message becomes visible.
```json
$ awslocal sqs get-queue-attributes --queue-url ...
{
    "Attributes": {
        "ApproximateNumberOfMessages": "1",
        "ApproximateNumberOfMessagesDelayed": "0",
        "ApproximateNumberOfMessagesNotVisible": "0",
```

(BAD) Inspecting the message, I can tell it's exactly the same message that I deleted before.

# Steps to reproduce

1. Configure localstack to provide SQS.
2. Persist the directory containing `recorded_api_calls.json` in a volume.
3. Start localstack.
4. Create the SQS queue if necessary.
5. Send a message to the queue.
6. Receive that message.
7. Delete that message.
8. Restart the localstack service.
9. Check if the queue is empty.  It should be empty, but I'm observing that the deleted message comes back (invisible at first, then visible after a short time).

## Command used to start LocalStack

I'm not overriding the default command from the localstack image.

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

I don't have a minimal test case that can be separated from my application, sorry.

---

Here's a theory of what is happening.  Take it with a grain of salt; I am inexperienced with SQS and localstack.

The directory containing `recorded_api_calls.json` is persisted in a volume defined in my docker-compose.yml.  My understanding is that localstack restores the state of the SQS queue on startup by replaying all of the API calls that it's seen.

The API calls I'm making to SQS look like:
1. Send message to queue.
2. Receive message from queue, includes a randomly-generated receipt handle.
3. Delete message from queue using the receipt handle from step 2.

Could it be that when localstack replays those API calls, the generated receipt handle from step 2 is different every time, whereas the receipt handle presented in step 3 is always the handle used in my original delete API call?  So the receipt handle presented in step 3 during the replay no longer matches the handle generated in step 2, so SQS ignores the delete call during replays?

**Comment by whummer** [comment]
Thanks for the detailed report @michaelhixson , and apologies for the long delay.

> Could it be that when localstack replays those API calls, the generated receipt handle from step 2 is different every time, whereas the receipt handle presented in step 3 is always the handle used in my original delete API call? So the receipt handle presented in step 3 during the replay no longer matches the handle generated in step 2, so SQS ignores the delete call during replays?

Your analysis is spot on, the wrong handle is being used when replaying the API calls on startup.

Unfortunately, the "record&replay" based persistence mechanism (storing API calls to `recorded_api_calls.json` and re-running them on restart) has many conceptual flaws which cannot be easily addressed in a robust and generic way. In fact, this persistence mechanism has created more problems and headaches than benefits for most users recently (as indicated in your report as well). 

Due to these fundamental issues, we have decided to **discontinue support for the record&replay based legacy persistence**. Please find more details in the release notes for version 0.13.1: https://github.com/localstack/localstack/releases/tag/v0.13.1 . We have introduced an environment variable `LEGACY_PERSISTENCE` which can be used to continue using the legacy persistence; currently the default setting is still `LEGACY_PERSISTENCE=1` (i.e., no changes required on your end), but this option may default to `LEGACY_PERSISTENCE=0` in an upcoming release.

The recommended solution/workaround for now is to disable the `DATA_DIR` configuration, and instead use init scripts to pre-populate your LocalStack instance with the required state at startup (see documentation around `INIT_SCRIPTS_PATH`/`/docker-entrypoint-initaws.d` in the README). We hope that helps reduce the headaches around `KeyError`, slow startups, and other issues introduced by the legacy persistence.. Thanks for your support!
