### ISSUE TITLE
SQS messages automatically deleted after sending to lambda

### ISSUE THREAD

**Issue by CoburnJoe** [localstack/localstack#4180]
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description

When calling SQS `delete_message` from a lambda function, it fails, because localstack has already deleted the message when triggering the lambda (`An error occurred (ReceiptHandleIsInvalid) when calling the DeleteMessageBatch operation: The input receipt handle is invalid.`). I have confirmed this by hard-coding a receipt handle, and double-checking the SQS message attributes, as well as allowing the code to pull out the receipt handle of the provided message.

This is an inaccuracy - when running in AWS directly, you are required to delete messages yourself when processed - I don't want to have to change my logic for running locally, and others may get caught out - e.g. running locally it works, but not in AWS because localstack deletes messages in the background.

The code at fault is [here on line 406](https://github.com/localstack/localstack/blob/3cc0541a260c2f2af90e435f333c623e84ed4880/localstack/services/awslambda/lambda_api.py#L406): 

...

## Expected behavior
Messages stay in the queue, _even when sent to a lambda_. Messages should obey the following AWS-defined criteria:

- Messages sent to a lambda are invisible for the duration of their visibility timeout (default 30 seconds)
- If the lambda does not delete the message using the receipt handle (which indicates a successful processing), SQS retries up to the defined number of retries
- If still unsuccessful, push to a dead letter queue or delete 

...

## Actual behavior

Messages are deleted immediately upon sending to a lambda.

...

# Steps to reproduce

- Create a lambda function triggered by SQS
- Get the lambda function to delete the provided message
- Error

## Command used to start LocalStack
Docker Compose file
...

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

Sample Python lambda handler:

```python
import boto3


def lambda_handler(event, context=None):
    records = event.get("Records", [])
    for record in records:
        receipt_handle = record.get("receiptHandle")

        sqs_client = boto3.client("sqs", endpoint_url="http://localstack:4566")

        # This will fail with ```ReceiptHandleIsInvalid``` exception
        sqs_client.delete_message(
            QueueUrl="http://localstack:4566/000000000000/test-queue", ReceiptHandle=receipt_handle
        )

    return {"Message": "Hello, World!"}

```

Sample Localstack (using a Docker-compose environment):

```bash
awslocal lambda create-function --function-name test-lambda --runtime python3.8 --handler lambda_function.lambda_handler --package-type Zip --role arn:aws:iam::000000000:role/lambda-ex --code S3Bucket="__local__",S3Key="$LAMBDA_CODE_PATH"

awslocal sqs create-queue --queue-name test-queue

awslocal lambda create-event-source-mapping --function-name test-lambda --batch-size 1 --event-source-arn arn:aws:sqs:eu-west-2:000000000000:test-queue
```
...

I'm happy to work on this issue myself (but having never worked on localstack, I may need to get up to speed).
Also, perhaps this could just be hidden behind an environment variable - e.g. $DELETE_SQS_MESSAGES which default to true.

**Comment by pinzon** [comment]
Hi @CoburnJoe thank you for such detail in your issue. I have just replicated the issue like and cofirmet 2 thins:
1. When working in Localstack, the lambda function logs an error that the message has been deleted but 
2. When running the same code in Aws, it deletes the message without issue.


I was thinking about just deleting the callback function to allow the lambda function delete the message but [this documentation](https://docs.aws.amazon.com/lambda/latest/dg/with-sqs.html) _"When Lambda reads a batch, the messages stay in the queue but become hidden for the length of the queue's visibility timeout. If your function successfully processes the batch, Lambda deletes the messages from the queue. If your function is throttled, returns an error, or doesn't respond, the message becomes visible again. All messages in a failed batch return to the queue, so your function code must be able to process the same message multiple times without side effects. "_ 

So I'm thinking maybe the real issue is that even before the lambda function is finished the message is already deleted so it throws an error, let me know what you think.

**Comment by CoburnJoe** [comment]
@pinzon I don't believe this to be the case.
The lambda API raises the error, as it _can't_ delete the message - as it's already been deleted by localstack on [line 406](https://github.com/localstack/localstack/blob/3cc0541a260c2f2af90e435f333c623e84ed4880/localstack/services/awslambda/lambda_api.py#L406).

**Comment by CoburnJoe** [comment]
@pinzon so I've done some more research and testing...
Lambda does automatically delete messages providing it does not have an error,
However...The place and way Localstack deletes messages is different to AWS itself.

In AWS, it's possible to delete messages from within the code (or let them be automatically deleted)
But in Localstack (because it deletes the message immediately), the same code that works in AWS won't work locally.

Now, I'm able to work around this now I fully understand it, but wondered how consistent Localstack is aiming to be vs. AWS?

**Comment by pinzon** [comment]
Hi @CoburnJoe , I think there is a misunderstanding and I'm certain is because I didn't explain my self correctly last time. 
And to make sure, I also took the time to reproduce again your issue.

Let's start with [line 406](https://github.com/localstack/localstack/blob/3cc0541a260c2f2af90e435f333c623e84ed4880/localstack/services/awslambda/lambda_api.py#L406). This line specifies the deletion of the sqs messages used to trigger the lambda function. This line is part of the  [delete_messages](https://github.com/localstack/localstack/blob/3cc0541a260c2f2af90e435f333c623e84ed4880/localstack/services/awslambda/lambda_api.py#L396) function and this function is used as a callback when the lambda function ends, as describe in [line  431 to 432](https://github.com/localstack/localstack/blob/3cc0541a260c2f2af90e435f333c623e84ed4880/localstack/services/awslambda/lambda_api.py#L431).

So, that part you mentioned goes like this (let's call them steps):
1. Define the deletion of the messages
2. Run lambda. (Here you can also delete the messages)
3. Execute the automatic deletion of the messages without knowing if there were already deleted.

I think, that's the expected behaviour. right?

In your case, when you see this next error log, It's from step 3 not step 2.
`2021-06-25T19:27:53:INFO:localstack.services.awslambda.lambda_api: Unable to delete Lambda events from SQS queue (please check SQS visibility timeout settings): [{'Id': 'ieldasd...fasdfadsfal'}] - An error occurred (ReceiptHandleIsInvalid) when calling the DeleteMessageBatch operation: The input receipt handle is invalid.`

------------------------------------------------------

And I can prove to you that you're deleting your messages inside your lambda code. 
So let's define a new handler (it only adds more logs to the one you already defined):
```python
def handler(event, context=None):
    records = event.get("Records", [])
    for record in records:
        receipt_handle = record.get("receiptHandle")

        sqs_client = boto3.client("sqs",
            region_name='us-east-1',
            endpoint_url="http://localhost:4566",
            aws_access_key_id='test',
            aws_secret_access_key='test'
        )

        try:
            sqs_client.delete_message(
                QueueUrl="https://queue.amazonaws.com/000000000000/test-queue", ReceiptHandle=receipt_handle
            )
            print("Message deleted")
        except Exception as e:
            print("Message NOT deleted")
    
    return "hello world"
```
If we reproduce the issue, defining the lambda, creating an event source and triggering it. You will see an error log from the lambda service (Again, from STEP 3)  **but you will not** see the logs from your lambda code. One accesses those logs through the CloudWatch Logs service like in the real AWS.  (Here is a [guide](https://stackoverflow.com/questions/49794781/aws-lambda-logs-using-awscli-how-can-i-access-lambda-logs-using-awscli) if you need help)

So if you follow the guide and find the logs of the lambda function. You will have something very similar to this:
```
{
    "events": [
        {
            "timestamp": 1625832760880,
            "message": "START 6c63e29d-a633-4ce9-810f-bdaaee521ed5: Lambda arn:aws:lambda:us-east-1:000000000000:function:crist-test started via \"local\" executor ...",
            "ingestionTime": 1625832760963
        },
        {
            "timestamp": 1625832760892,
            "message": "Message deleted",
            "ingestionTime": 1625832760963
        },
        {
            "timestamp": 1625832760918,
            "message": "END RequestId: 6c63e29d-a633-4ce9-810f-bdaaee521ed5",
            "ingestionTime": 1625832760963
        },
        {
            "timestamp": 1625832760931,
            "message": "REPORT RequestId: 6c63e29d-a633-4ce9-810f-bdaaee521ed5 Duration: 28973 ms",
            "ingestionTime": 1625832760963
        }
    ],
    "nextForwardToken": "f/00000000000000000000000000000000000000000000000000000003",
    "nextBackwardToken": "b/00000000000000000000000000000000000000000000000000000000"
}
```

And it's in those final logs that you can see that the lambda code is behaving as expected. 
I hope this detailed explanation resolves any doubt left.
Thanks.

**Comment by CoburnJoe** [comment]
@pinzon thank you so much for the detailed information - it's really appreciated. 
I fully understand now (and I guess AWS silently swallows "already deleted" errors when running in the cloud).
