### ISSUE TITLE
Python 3.8 code not supported due to change in base docker image localstack/java-maven-node-python

### ISSUE THREAD

**Issue by Awarua-** [localstack/localstack#4183]
# Type of request: This is a ...

[x ] bug report
[ ] feature request

# Detailed description
Python code for lambda's that requires python 3.8 cannot be run due to the python runtime of the base docker image is 3.7.10 in localstack/java-maven-node-python:latest, whereas it was 3.8 in localstack/java-maven-node-python:0.12.0
...

## Expected behavior
Lamba loads python code artifact
...

## Actual behavior
`File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 644, in exec_lambda_code
    handler_module = imp.load_source(lambda_id, lambda_file)
  File "/usr/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/tmp/localstack/lambda_script_l_29edf3f9.py", line 16, in <module>
<<OMITTED>>
    from typing import TypedDict, List, Dict
ImportError: cannot import name 'TypedDict' from 'typing' (/usr/lib/python3.7/typing.py)`
...

# Steps to reproduce

Execute lambda python artifact that uses features from python 3.8, such as TypedDict 

## Command used to start LocalStack
Started with python-localstack-client
...

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

...

**Comment by pinzon** [comment]
Hi, localstack recently changed its python version but your lambda code should not have any problem if you set the env variable `LAMBDA_EXECUTOR=docker ` so the lambda service will use a docker container to run your code.

if you have it set to **local** and your lambda uses a runtime that starts with python it will try to run it with the python version that Localstack is using at that moment, so you should make sure it's compatible with your code. 

I'll close this issue since it seems to me an usage problem.
