### ISSUE TITLE
invoking "hello world" golang lambda deployed to localstack using terraform fails

### ISSUE THREAD

**Issue by tycobbb** [localstack/localstack#4216]
# Type of request: This is a ...
[x] question phrased as a bug report

# Detailed description

invoking a golang lambda deployed to localstack using terraform fails. the awscli command to invoke it, for example, looks like:

```sh
aws lambda invoke \
    --function-name "echo" \
    --payload $(base64 < input.json) \
    --endpoint-url=http://localhost:4566 \
    --debug \
    output.json
```

## Expected behavior

the lambda fn executes successfully.

## Actual behavior

the lambda fn reports a `200`, but `output.json` contains the following:

```json
{
  "errorMessage": "RequestId: 9128b0ea-7e18-1ce6-7603-5b0743868967 Error: fork/exec /var/task/echo: no such file or directory",
  "errorType": "exitError"
}
```

# Steps to reproduce

i created an example repo demonstrating this problem here: https://github.com/tycobbb/go-lambda-template

## Command used to start LocalStack

```sh
# same problem when using `localstack start`
$ docker-compose up
```

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

the readme in the linked repo contains more detailed instructions.

**Comment by GonzaloSaad** [comment]
Hello @tycobbb! I've cloned your repo and was able to reproduce it on my end! 

I'll do further investigation tomorrow! Thank you very much for the repo, it was super helpful!

**Comment by GonzaloSaad** [comment]
Found a potential solution :partying_face:! I'll check if it is safe and make a PR tomorrow!

**Comment by GonzaloSaad** [comment]
Well. Good news!

I could replicate the error in localstack BUT I could also replicate the error in AWS. So `localstack` is actually OK in its behavior. 

![image](https://user-images.githubusercontent.com/32211561/125147350-f0bb7a00-e100-11eb-909e-7cabc48e917c.png)

The problem resides in the handler specification. Instead of `echo` it should be the path to the **binary** the same way as it was zip. In this case, the binary was zip from `build/echo`, then the handler should be the same :grinning: .

I'm sure you can zip in a different way and just include the binary, to avoid the `build/` prefix. 

In the case of this sample project, what I did was just add: 
`export TF_VAR_fn_binary="$FN_BINARY"` 

And then in terraform
```hcl
variable "fn_binary" {
  type = string
}


---

resource "aws_lambda_function" "echo" {
  ...
  handler          = var.fn_binary // instead of var.fn_name
  ...
}

```



Here working in localstack
```
{
    "StatusCode": 200,
    "LogResult": "",
    "ExecutedVersion": "$LATEST"
}
```
The `response.json` file: 
```
"Bob"
```

Here working in AWS
![image](https://user-images.githubusercontent.com/32211561/125147450-c4ecc400-e101-11eb-9b3d-6ea642d72667.png)

With the provided script: 
```json
{
    "StatusCode": 200,
    "ExecutedVersion": "$LATEST"
}
```

And the `response.json`
```
"Bob"
```

**Comment by tycobbb** [comment]
oh no, thank you for your help!

**Comment by GonzaloSaad** [comment]
> haha, oh no . thank you for your help, i was suffering through this for many days!

No problem! Thank you, that sample project was awesome!
