### ISSUE TITLE
question: lambda go1.x runtime platform issue

### ISSUE THREAD

**Issue by neilkinnish** [localstack/localstack#4281]
### Is there an existing issue for this?

- [X] I have searched the existing issues and read the documentation

### Question

Running localstack with lambda functions on a MAC M1 via compose. I have an issue just with golang runtime functions where I get `platform (linux/amd64) does not match the detected host platform (linux/arm64/v8)`. This is only happening with golang I assume due to the image for the runtime.

**Comment by thrau** [comment]
Hi @neilkinnish, thanks for reaching out. Which lambda executor are you using (the value of `LAMBDA_EXECUTOR`)? local, or docker?

**Comment by alexrashed** [comment]
Hi @neilkinnish. With 0.13.0 (released last week) we now have an arm64-native Docker image of LocalStack. With it we also released an arm64 version of the Go runtime. These changes should hopefully fix your issues. Could you give the latest version a try and tell us if this issue has been fixed with the latest version?

**Comment by thrau** [comment]
closing this as it seems fixed. please re-open if the problem resurfaces.
