### ISSUE TITLE
Cognito - JWKS url returns 500 error

### ISSUE THREAD

**Issue by John-D8** [localstack/localstack#4316]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After creating a user pool, trying to get data from the JWKS urls returns 500 instead of returning the data.
This has worked in previous image versions.

### Expected Behavior

The JWKS data should be returned.

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

1. Create a user pool
2. Try to access the JWKS url:
 http://localhost:4566/<userpool_id>/.well-known/jwks.json
(or http://localstack:4566.... from within the docker network)
--> 500 is returned

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker-compose

### Environment

```markdown
- OS: Windows 10
- LocalStack: latest
```

**Comment by whummer** [comment]
Thanks for reporting @John-D8 . There's been some code refactoring, and this change slipped through the cracks, unfortunately - apologies for the inconvenience. This should be fixed in the meantime (regression tests have been added on our end). Please let us know if the problem persists. Thanks for your help!
