### ISSUE TITLE
When creating DynamoDB to Kinesis streams with CF, stream name is ignored and replaced by a generated name

### ISSUE THREAD

**Issue by jhberthemet** [localstack/localstack#4350]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When using CF like this:
```
{
    "Resources": {
        "TableTest": {
            "Type": "AWS::DynamoDB::Table",
            "Properties": {
                "TableName": "TestTable",
                "KeySchema": [
                    {
                        "AttributeName": "id",
                        "KeyType": "HASH"
                    }
                ],
                "AttributeDefinitions": [
                    {
                        "AttributeName": "id",
                        "AttributeType": "S"
                    }
                ],
                "ProvisionedThroughput": {
                  "ReadCapacityUnits" : 1,
                  "WriteCapacityUnits" : 1
                },
                "StreamSpecification": {
                    "StreamViewType": "NEW_AND_OLD_IMAGES"
                },
                "KinesisStreamSpecification": {
                    "StreamArn": {
                        "Fn::GetAtt": [
                            "TestStream",
                            "Arn"
                        ]
                    }
                }
            }
        },
        "TestStream": {
            "Type": "AWS::Kinesis::Stream",
            "Properties": {
                "Name": "test-stream",
                "ShardCount": 1
            }
        }
    }
}
```

Two streams will be created, first one "test-stream" and another one like:
```
    "StreamARN": "arn:aws:kinesis:us-east-1:000000000000:stream/__ddb_stream_TestTable",
    "StreamName": "__ddb_stream_TestTable",
```

Dynamo events actually goes to __ddb_stream_TestTable instead of test-stream

### Expected Behavior

I would expect that only "test-stream" stream is created and that dynamo events goes it it.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

`awslocal cloudformation create-stack --stack-name myteststack --template-body file://mytemplate.json`

### Environment

```markdown
- OS: MacOS 
- LocalStack: latest
- Docker: 3.5.2
```

**Comment by giograno** [comment]
Hi @jhberthemet, thanks for opening the issue. To clarify, you see two kinesis streams because we use kinesis under the hood to implement `dynamodbstreams` (that's the one with the generated name). Does the stream only work for one kinesis stream?

**Comment by jhberthemet** [comment]
Hi @giograno, yes, only the generated one was working.

**Comment by pinzon** [comment]
Hi @jhberthemet,

I've taken a closer look at this issue, and it appears that the deployment of the required resources is functioning as expected. Once the CloudFormation stack reaches the "CREATE_COMPLETE" status, you can verify that the Kinesis DataStream configuration is correct by executing the following AWS CLI command:

```shell
awslocal dynamodb describe-kinesis-streaming-destination --table-name TestTable
```

The response you should receive is as follows:

```json
{
    "TableName": "TestTable",
    "KinesisDataStreamDestinations": [
        {
            "StreamArn": "arn:aws:kinesis:us-east-1:000000000000:stream/test-stream",
            "DestinationStatus": "ACTIVE",
            "DestinationStatusDescription": "Stream is active"
        }
    ]
}
```

This confirms that the Kinesis DataStream has been properly configured. Additionally, since you've specified the "StreamSpecification" when creating the DynamoDB table, DynamoDB will automatically create a stream within the `dynamodbstreams` service. This stream will always be associated with your table and will have an "LatestStreamArn" similar to:

```
arn:aws:dynamodb:us-east-1:708750094265:table/TestTable/stream/2023-09-14T16:03:08.913
```

Please note that this behavior is consistent with AWS standards.

However, it's essential to understand that the DynamoDB Local project doesn't handle streams internally. To work around this limitation with LocalStack, the Kinesis Stream service is employed to manage the table stream. Consequently, you will observe two streams in the Kinesis service, reflecting this setup.

If you have any further questions or need additional assistance, please feel free to ask.

**Comment by jhberthemet** [comment]
Hi @pinzon,

I don't mind having two streams created, however it is counter intuitive that the one getting data is the generated one, and not the one you created. Would it be possible to swap them? If not, it's not a big deal, I just wanted to report the issue so that someone having the same problem could find the solution.

Thanks for the detailed explanation!

**Comment by pinzon** [comment]
@jhberthemet Thanks for the follow up. I'll take a look again and see if can reproduce it.

**Comment by pinzon** [comment]
Hi @jhberthemet I just finished the PR #9138 which includes an AWS validated test of the integration you mention and the test passes. If you're still encountering the same problem you could open a new issue with the exact reproduction and assertion steps. Also make sure to pull the latest version of LocalStack.
