### ISSUE TITLE
bug: Missing modules when running `localstack pod list`

### ISSUE THREAD

**Issue by Tobolov** [localstack/localstack#4451]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When trying to run the command `localstack pod list`, errors detailing missing modules are thrown.
The 'missing' pip packages are:
* flask_cors
* quart
* hypercorn
* h11
* xmltodict

Additionally, the module 'localstack_ext.utils.pods' can't be found.

### Expected Behavior

The command runs.

### How are you starting LocalStack?

With the `localstack` script

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

1. Install localstack with python3 -m pip install localstack localstack-ext localstack-client
2. Ensure localstack upgraded with python3 -m pip install --upgrade localstack localstack-ext localstack-client
3. Export api key export LOCALSTACK_API_KEY="----------"
4. Set data dir export DATA_DIR="/home/ubuntu/localstack"
5. Logged in localstack login
6. Ran localstack pod list. Received the error ERROR: No module named 'flask_cors'
7. Installed flask_cors manually using pip. Proceeded to additionally install quart, hypercorn, h11, xmltodict for the same reason.
8. Ran localstack pod list. Received the error ERROR: No module named 'localstack_ext.utils.pods'

### Environment

```markdown
OS: Ubuntu 20.04 LTS
Localstack pip packages:
- localstack             0.12.16.1
- localstack-client      1.22
- localstack-ext         0.12.15
```

**Comment by whummer** [comment]
Thanks for reporting @Tobolov . This should (hopefully) be fixed in the meantime. Can you please update the CLI packages and give it another try:
```
pip install --upgrade --no-cache localstack localstack-ext
```
Please note that `LOCALSTACK_API_KEY` should be configured (and exported) as an environment variable in the terminal session where you're running the pods CLI commands.

Hope that helps - please keep us posted how it goes.. Happy to dig more into this if the problem persists. Thanks!
