### ISSUE TITLE
Publish message to the topic as JSON and read it by consumer from body (NOT as RAW data)

### ISSUE THREAD

**Issue by avromanov2009** [localstack/localstack#4850]
### Is there an existing issue for this?

- [X] I have searched the existing issues and read the documentation

### Question

So I have created some topic 
`aws --endpoint-url=http://localhost:8000 sns create-topic --name example-topic`

```
aws --endpoint-url=http://localhost:8000 sns subscribe \
--topic-arn arn:aws:sns:us-east-1:000000000000:example-topic \
--notification-endpoint http://host.docker.internal:9000/listener \
--protocol http \
--attributes RawMessageDelivery=false (also I have tried without any --attributes)
```

after that trying to send message. this case message is delivered to consumers
`aws --endpoint-url=http://localhost:8000 sns publish --topic-arn arn:aws:sns:us-east-1:000000000000:example-topic --message '{"hello": "123"}' --message-structure json`

but if I used as 
`aws --endpoint-url=http://localhost:8000 sns publish --topic-arn arn:aws:sns:us-east-1:000000000000:example-topic --message '{"hello": "123"}'`
this case is works but in endpoint we should get this data as rawBody and convert it to JSON manually.

Could anybody help please. What am I missing to receive endpoint messages directly in the body?

The documentation only says to use --message-structure json to transfer data and it is indicated that when subscribing, you can specify the RawMessageDelivery attribute, which I also tried and it does not work

**Comment by pinzon** [comment]
@avromanov2009 could you be more specific? I just tested the delivery of a message in a subscription with the attribute `RawMessage=true` in both AWS and Localstack and it works fine to me. 

### Steps to reproduce

Create topic:
`awslocal sns create-topic --name test-topic`

Susbscribe endpoint
`awslocal sns subscribe \
	--topic-arn $topicArn \
	--notification-endpoint $endpoint \
	--protocol https \
	--attributes RawMessageDelivery=true`

Send message:
` awslocal sns publish --topic-arn $topicArn --message '{"hello": "123"}'`

### Expected behaviour (AWS)
The endpoint receives only the JSON message:
`{"hello": "123"}`

### Current behaviour (Localstack)
The endpoint receives only the JSON message:
`{"hello": "123"}`

Also make sure you're using the latest version of Localstack.
I'm gonna close this issue for now until more info is provided.
