### ISSUE TITLE
bug: cannot access other docker containers from localstack since 0.13.0

### ISSUE THREAD

**Issue by yonatandbinahai** [localstack/localstack#4947]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Try to access other docker containers from the localstack container fails.
This works in 0.12.15 but not in 0.13.0 or later.

### Expected Behavior

Other containers should be accessible.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    awslocal s3 mb s3://mybucket

### Environment

```markdown
- OS: Windows 10
- LocalStack: 0.13.0
```

### Anything else?

The problem might be that the `nameserver` has 2 entries in the resolv.conf file in the localstack container.

**Comment by dfangl** [comment]
Hi @yonatandbinahai !
Currently, a viable workaround for this issue is either setting the DNS server of localstack to the one provided in docker with `DNS_SERVER=127.0.0.11` or disabling the LocalStack DNS integrations completely (setting `DNS_ADDRESS=0`).
We are continuing to implement a better and permanent solution for this issue, but for now, please set one of the mentioned configuration variables when using LocalStack in docker compose if domain resolution should work.

**Comment by awehrung** [comment]
This fix worked for me with `DNS_SERVER=127.0.0.11`! Thanks (I had this same problem in the linked issue).

**Comment by nini** [comment]
Thanks for the tip. I had a similar issue while running junit on Drone inside of `dind-drone-plugin` while migrating from Travis. My solution was to remove configuration line `HOSTNAME_EXTERNAL=localhost`.

**Comment by dfangl** [comment]
This should be fixed by default in the latest docker image! Thanks for reporting this!
