### ISSUE TITLE
Enhanced Container Image Tagging

### ISSUE THREAD

**Issue by JKomoroski** [localstack/localstack#5032]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

Please Tag [container images](https://hub.docker.com/r/localstack/localstack/tags) for Major/Minor/Patch version ranges. 

As a consumer of the localstack docker image it would be nice to get the latest image within a version range, and not rely on `latest` tag which could contain breaking changes at any time.

One possible example of a tagging scheme:

Current Code Release is: `0.13.0`
Current Image Tag is: `0.13.0.8` (I think)

Example Tag for current for Major Version: `0`
- Would include `0.14.x`
- Would not include `1.x.x`

Example Tag for current Minor Version: `0.13` 
- Would include `0.13.1`
- Would not include `0.14.x`
- Would not include `1.x.x`

Example Tag for the current Patch Version: `0.13.0`
- Would include `0.13.0.x`
- Would not include `0.13.1`
- Would not include `0.14.x`
- Would not include `1.x.x`

An example of a docker image that does this is the [postgres image](https://hub.docker.com/_/postgres/)

### 🧑‍💻 Implementation

While I believe it would be easy enough to update the make file to do this whenever a release is cut, but I don't know how docker hub tags `0.13.0.8` when the latest release is `0.13.0`.

### Anything else?

I don't think the current usage of the `latest` tag would need to change, but it should be known that I don't know if `latest` means latest build in any branch (ie, security patch for 0.12.x) or latest build from the latest release only.

Love the library. Very happy to see that version 0.13.0 introduces lazy loading. This cut down start time by 66% for me!

**Comment by thrau** [comment]
hi @JKomoroski thanks for your interest and your suggestions! improving the release process is certainly something that's on our minds and that we discuss regularly, but have been too caught up in feature requests to get to lately. personally i think the approach you've laid out is pretty good for semver, and is definitely something we could implement. it's not clear at this point whether the zerover scheme that localstack is currently employing will remain in place for much longer, and how that would affect the version range semantics of the tags you are describing.

but i think we could consider adding at least minor version tags (0.13) to always get the latest released patch version within that range, but not the nightly `latest`.

/cc @alexrashed

**Comment by alexrashed** [comment]
Hey @JKomoroski!
That's a good catch. And this shouldn't be too big of a deal:
- As @thrau mentioned, we are currently using zerover. Which means that there are no major versions. :)
- The semantics of the `latest` tag is: Result of the last successful build on the master branch.This means that it is basically a "nightly" build, even though it's not scheduled once a day but executed with every commit on the master. This means we don't really need to care about it, since its not affected.
- The tagging and pushing is all done in the `Makefile`. So we basically only need to parse the version and also tag and push the minor (and possibly the patch if it's a four-digit-version).

The `Makefile` is a bit complex, but we only need to care about the `docker-push-master` and the `docker-create-push-manifests` targets. If you would like to give it a try, I'd be happy to assist. 🚀 

Otherwise I'll try to squeeze this in during the next few days. 😉

**Comment by flaviusemil** [comment]
Hi @alexrashed , hope you don't mind stepping in, I've created a PR for this issue, If I missed something please let me know.

**Comment by alexrashed** [comment]
Thanks for the contribution, @flaviusemil! Since your PR has been merged, I'm closing this issue. :)
