### ISSUE TITLE
question: Cannot connect grafana Timestream plugin to localstack instance

### ISSUE THREAD

**Issue by the-gilbs** [localstack/localstack#5067]
### Is there an existing issue for this?

- [X] I have searched the existing issues and read the documentation

### Question

Trying to use the timestream grafana [plugin](https://grafana.com/grafana/plugins/grafana-timestream-datasource/), I'm having trouble connecting it to a localstack instance.   I can create timestream tables, write to them, query them from the cli, etc.  But I'm not able to connect with grafana.  The endpoint seems to work (if I use something else I get a different error).  Using 'test' for access key/secret. Have also tried creating an IAM role and using that, to no avail.  Any tips?

### Anything else?

![Screen Shot 2021-12-03 at 11 35 05 AM](https://user-images.githubusercontent.com/80845575/144666562-ebe1451b-827d-47b2-9c1e-37a110af0e7b.png)
![Screen Shot 2021-12-03 at 12 10 38 PM](https://user-images.githubusercontent.com/80845575/144666573-68b1a515-0f37-42c2-8cfd-59ff8ce87532.png)

**Comment by whummer** [comment]
Thanks for reporting @the-gilbs . This should be (hopefully) fixed in the meantime. Can you please pull the `latest` Docker image and give it another try? We were able to connect Grafana Timestream with the latest version, and run some test queries against it:

![image](https://user-images.githubusercontent.com/2807888/144899193-701b7fa0-a228-42a3-867a-94cd8301575c.png)

Please keep us posted how it goes.. Thanks!

**Comment by the-gilbs** [comment]
Works! Can now use empty role and it seems to connect.  Haven't figured out the right incantation to get queries working like I want, but probably a separate issue. Thanks!
