### ISSUE TITLE
bug: How come Localstack and Localstack-light have same image sizes???

### ISSUE THREAD

**Issue by vmanikes** [localstack/localstack#5162]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I downloaded both localstack and localstack light they have the same image sizes lol

```
localstack/localstack-light   latest    7d02fe34b6d5   4 hours ago    1.51GB
localstack/localstack         0.13.2    a2037a50ec04   18 hours ago   1.51GB
```

### Expected Behavior

light should be technically smaller as you have mentioned in the docker hub `reduced set of dependencies`

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

```
docker pull localstack/localstack
docker pull localstack/localstack-light
docker image ls
```

### Environment

```markdown
- OS: Mac
- LocalStack: latest
```

### Anything else?

Nope

**Comment by dfangl** [comment]
Hi @vmanikes !
Since version 0.11.4, the light image is the default image, so the tag is mostly for backwards compatibility.
If you look at the difference between `localstack/localstack` and `localstack/localstack-full` you will see the difference.
The description in docker hub is misleading though, and will probably changed soon!

**Comment by vmanikes** [comment]
Thanks for the superfast response @dfangl
