### ISSUE TITLE
bug: log4j vulnerable still in 0.13.2

### ISSUE THREAD

**Issue by justicel** [localstack/localstack#5171]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

There is still an outdated log4j version contained in the 0.13.2 image versions. Below is an output of a check against the filesystem:

```
docker run --rm -i -t --entrypoint /bin/sh localstack/localstack-full:0.13.2
# cd /
# find . -name *log4j*
./opt/code/localstack/localstack/infra/elasticsearch/lib/log4j-api-2.11.1.jar
./opt/code/localstack/localstack/infra/elasticsearch/lib/log4j-core-2.11.1.jar
```

### How are you starting LocalStack?

With a `docker run` command

### Steps To Reproduce

Check localstack build files

### Environment

```markdown
- OS: 
- LocalStack: 0.13.2
```

**Comment by dfangl** [comment]
Hi! You are quite right. This log4j library is part of elasticsearch 7.10.0 which is preinstalled in the full image.
We are evaluating an update to a later elasticsearch version (like 7.16.2) which ships the upgraded versions!
In the meantime, this elasticsearch article marks the setup (with jre11) as currently not exploitable: https://discuss.elastic.co/t/apache-log4j2-remote-code-execution-rce-vulnerability-cve-2021-44228-esa-2021-31/291476 .
While this is reassuring for now, we of course want to move away from the vulnerable versions as soon as possible.
Thanks for bringing this to our attention!

**Comment by alexrashed** [comment]
Hi @justicel!
Unfortunately the current situation with ElasticSearch and AWS (with its fork OpenSearch) lead to the situation where the license of ElasticSearch has been changed. So there most likely won't be any updates to ElasticSearch anymore (in terms of AWS adding new versions, we will continue to work on our support of the AWS ES API in LocalStack).
Luckily - as @dfangl stated - elasticsearch should not be vulnerable within our Docker image (due to the used JDK version). 
We also just recently added support for OpenSearch (https://github.com/localstack/localstack/pull/5341), where we will continue to add new versions.
Therefore, I'll close this issue for now.
