### ISSUE TITLE
Getting localhost to work for s3 without localstack.cloud and changing /etc/hosts

### ISSUE THREAD

**Issue by pfrank13** [localstack/localstack#5211]
### Is there an existing issue for this?

- [X] I have searched the existing issues and read the documentation

### Question

I put this as a question because I'm assuming there is a good reason this doesn't work and I'm just ignorant of it. I saw a related issue here  https://github.com/localstack/localstack/issues/2631 the long and short of it is I want to configure my s3 client to point at localhost:\<somePort\> and use a bucket by name (which is how the library works) WITHOUT munging /etc/hosts to add localstack.cloud. When configuring against localhost the aws provided library in Javascript (and I imagine most others) sends things by name with localhost as the domain.

### Anything else?

Here is the fork branch to build out the localstack-full docker image from that has a working fix
https://github.com/pfrank13/localstack/tree/localhost_test

Here is my project that shows how it fails with the current version of localstack, and works with my patched version localstack-full if built
https://github.com/pfrank13/s3_localstack_test
Specifically this test
https://github.com/pfrank13/s3_localstack_test/blob/main/src/index.test.ts

To run it:
`npm install && npm test` There is a chance it may timeout pulling down the `localstack/localstack` docker image so you may need to execute `docker pull localstack:localstack:0.13.2` before executing the test to ensure the DL completes. Once it's on your machine it's cached so that timeout goes away.

The thing I had to change to make this work that is probably an issue is here https://github.com/pfrank13/localstack/commit/13c9cd8f6594f82ed52fef90f3a3ecb7d80cb45b?diff=unified#diff-35a410627f337229189b46aec210eb9c224e7b53774b5e22c39295d6c601fc18L363, these tests don't like "aws" or "swa" being interpreted as the bucket name but I assume there can be special cases carved out in the regex if these are truly important to behave in that way

I didn't do a PR and a bug report because I'm betting that more work is going to need to be done or this CAN'T work for some other reason. 

NOTE: I'm using Testcontainers by design so just making it work with Docker Compose isn't a solution for me, but I recognize Docker Compose can do all sorts of networking tricks that makes this go away.
Also, we are currently forcing path style access which is our workaround but I'd prefer not to test in a manner that isn't how it will be used against real AWS.

**Comment by calvernaz** [comment]
Hi @pfrank13, thanks for your question.

This is a special case running S3 on LocalStack because of the way S3 addresses [virtual buckets](https://docs.aws.amazon.com/AmazonS3/latest/userguide/VirtualHosting.html). Essentially there are two ways of addressing the buckets by name in S3, [path vs host based style](https://docs.localstack.cloud/aws/s3/). 

Before we jump into the details of how this is implemented in LocalStack, we need to establish two things first:

 * [AWS is deprecating path-based style bucket addressing](https://aws.amazon.com/blogs/aws/amazon-s3-path-deprecation-plan-the-rest-of-the-story/) 
 * For host-based style addressing, the bucket name defined in the host header follows these [rules](https://docs.aws.amazon.com/AmazonS3/latest/userguide/VirtualHosting.html#VirtualHostingSpecifyBucket). The bucket name is prefixed by the s3 domain (regional). In the case of LocalStack, that domain is *localhost.localstack.cloud*

Using *localhost* as your domain, you face two issues:

* Unable to resolve anything that has the shape of `<bucket-name>.localhost`
* and, not compliant with the S3 bucket addressing rules.

Now, if you want to use the "localhost" domain, you have to use the path-based style. Sometimes this is not possible because the library in question is implemented using a host-based style. Or, add to your `/etc/hosts`, which is not your preference nor flexible enough.

The other option is to point your library to `localhost.localstack.cloud` which will resolve to your localhost and be compliant with the rules of AWS S3 bucket addressing (because LocalStack, creates this special case for [<bucket-name>.localhost.localstack.cloud](https://docs.localstack.cloud/aws/s3/)

**Comment by pfrank13** [comment]
So, in essence, Localstack won't support localhost for buckets because that violates the bucket name? Is that the idea? Cause I have a working example linked above, so it's not a CAN'T be supported, it's an overt choice to not support it, from the Localstack point of view; is that accurate?

**Comment by calvernaz** [comment]
> So, in essence, Localstack won't support localhost for buckets because that violates the bucket name? Is that the idea? 

Hi @pfrank13, yes, but as I said above it's not only an issue with the regex thats captures the bucket name from the domain is also resolving the domain of the bucket. 

In your example above, it works because you are able to resolve the `aws.localhost` which works ok in some platforms, particulary [Linux](http://www.tin.org/bin/man.cgi?section=8&topic=systemd-resolved.service ), but it won'
t resolve in other platforms.

**Comment by pfrank13** [comment]
Ahhhh, there we go, that I wasn't clear on at all. Excellent, thanks for your responses!
