### ISSUE TITLE
[PRO] bug: HTTP API (Gateway v2) is broken, the event format is wrong

### ISSUE THREAD

**Issue by micheleangioni** [localstack/localstack#5281]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Lambdas attached to a HTTP API (Gateway v2) receive an event object formatted [like v1, instead than v2](https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-develop-integrations-lambda.html).

### Expected Behavior

Lambdas attached to a HTTP API (Gateway v2) receive an event object properly formatted.

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

Deploy a HTTP API (Gateway v2) with a lambda attached like this 
<img width="313" alt="image" src="https://user-images.githubusercontent.com/7933034/149626722-b4aea5e6-4511-43bd-8dec-15fe890f5d0a.png">

then inspect the event object received by the lambda

<img width="769" alt="image" src="https://user-images.githubusercontent.com/7933034/149626705-c4489f38-79b3-4e7e-9180-1664070ced5d.png">

### Environment

```markdown
- OS: MacOS Big Sour 11.6
- LocalStack: 0.13.3
```

### Anything else?

Related to https://github.com/localstack/localstack/issues/5259

**Comment by calvernaz** [comment]
Hi @micheleangioni thanks for reporting and for having a easy way to reproduce this issue.

I have a fix for it which pretty much adds support for lambda integration payloads for version 2, until now only payload for version 1 was supported. So a possible workaround for your current version would be to specify the [payload version 1, for the provider](https://www.serverless.com/framework/docs/providers/aws/events/http-api#event--payload-format).

[serverless.yml](https://github.com/micheleangioni/sls-node-ts/blob/master/serverless.yml#L99)
```
httpApi:
  payload: '1.0'
```

The other thing I'd like to point out is the endpoint setup logic inside the lambda. [For example for DynamoDB](infrastructure/dynamo/index.ts). There is an environment variable passed into the lambda container where it runs, that can and *should* be used instead of hardcoding (`AWS_ENDPOINT_URL`). 
```
const connectionString = isRunningInLocalStack
      ? 'http://localstack:4566'
      : 'http://localhost:4566';
```
this would translate to:
```
const connectionString = isRunningInLocalStack
      ? process.env.AWS_ENDPOINT_URL
      : 'http://localhost:4566';
```

Another consideration about reaching localstack within lambdas is that Localstack patches the `aws sdk` that is built-in in the container to resolve AWS external calls to Localstack. This way there is no need to have switches within the lambdas to detect if it running in a Localstack environment. I don't think it would for your use case because `apollo-server-lambda` has a dependency on `aws-sdk` and is packaging it into the lambda zip and not using the one existing in the container.

**Comment by micheleangioni** [comment]
Thanks a lot calvernaz for both the upcoming fix and your detailed advises! 🙏 
I'll soon try them out :)

**Comment by calvernaz** [comment]
Hi @micheleangioni, there is a new docker image with the fix, thanks!

**Comment by micheleangioni** [comment]
Thanks a lot @calvernaz :)
