### ISSUE TITLE
bug: <PostResponse> does not include port in <Location>

### ISSUE THREAD

**Issue by jsmecham** [localstack/localstack#5286]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am performing a presigned post to LocalStack's S3 service, which succeeds, but the `<Location>` returned in the `<PostResponse>` does not include the port that LocalStack is listening on in the URL.

### Expected Behavior

The `<Location>` node in the XML response should take into account the configured port in addition to the `HOSTNAME_EXTERNAL` value. See https://github.com/localstack/localstack/blob/master/localstack/services/s3/s3_listener.py#L1172. If my port is 4566, I would expect `<Location>http://localhost:4566/path/to/my/object</Location>`.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    awslocal s3 mb s3://mybucket

### Environment

```markdown
- OS: macOS Docker
- LocalStack: 0.13.3
```

**Comment by bentsku** [comment]
Hello @jsmecham and thanks for your report!

We have been working on a new implementation of S3, and it is now available under a feature flag. Could you try starting LocalStack with `PROVIDER_OVERRIDE_S3=asf` (for configuration of LocalStack, you can see [here](https://docs.localstack.cloud/references/configuration/)) and see if that would fix your problem? We overhauled the S3 pre-signed URLs and I think your issue would be fixed with the new version.

After a quick check, it seems the `Location` header and xml tag in the response in case of `{"success_action_status": "201"}` now includes the port, and the correct host as well.
Without setting `HOSTNAME_EXTERNAL`:
```xml
<Location>http://test-bucket-bfe698b4.s3.localhost.localstack.cloud:4566/key-my-file</Location>
```

And while setting it to `test-hostname`:
```xml
<Location>http://test-hostname:4566/test-bucket-bfe698b4/key-my-file</Location>
```

In the case it's not, don't hesitate to provide us any logs where the issue can be seen. Thanks a lot for your feedback! 

Note: if you are a Pro user, you should use the flag value `asf_pro` instead of `asf`.

**Comment by bentsku** [comment]
Hello, as this issue is pretty old and it is now fixed with the solution above, I'll close for now.

If you still encounter the issue, don't hesitate to comment and I'll reopen! 

Thanks again for your report!
