### ISSUE TITLE
How to use localstack to deploy an existing AWS service into a local service

### ISSUE THREAD

**Issue by HanHanPecan** [localstack/localstack#5365]
### Is there an existing issue for this?

- [X] I have searched the existing issues and read the documentation

### Question

I have an existing AWS service. I need to deploy it as a local service, but now I can't determine what service method the other party uses to deploy, so what documents can be provided? For existing services.

**Comment by whummer** [comment]
Thanks for reporting @HanHanPecan . Can you please provide a few more details, otherwise it will be hard to help out with this query. In general, we recommend using the comprehensive AWS documentation (https://docs.aws.amazon.com/) when it comes to the API methods of the individual services. The APIs in AWS are (mostly) identical to the APIs in LocalStack. 

For the actual LocalStack configuration, please refer to our docs here: https://docs.localstack.cloud/

Hope that helps - please feel free to re-open this issue if you have a more specific question that can be understood and reproduced end-to-end. Thanks!
