### ISSUE TITLE
bug: Cloudformation S3 Uploading

### ISSUE THREAD

**Issue by srobayo222** [localstack/localstack#5404]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have some aws cloudformation deploy scripts to create a bucket on S3 and upload some files on it.The script works awesome
![image](https://user-images.githubusercontent.com/13544207/151809641-4f9178b5-fc97-43ea-b47e-574a88f17cde.png)
![image](https://user-images.githubusercontent.com/13544207/151809842-144db4c3-b901-43ea-9f99-4222a8e0d1dd.png)

This are the files on the bucket
![image](https://user-images.githubusercontent.com/13544207/151809991-6c3c717f-d035-4f00-87d6-324e57a67729.png)

But, when i restart the local stack, this happens
![image](https://user-images.githubusercontent.com/13544207/151810181-d08657cf-cb0b-4c06-b4df-9886c061fb6b.png)
The big file is not persit on the bucket 

### Expected Behavior

The Expected behavior is the big file remains on the bucket after the restat of the enviroment

### How are you starting LocalStack?

Custom (please describe below)

### Steps To Reproduce

awslocal cloudformation package ^
    --template-file xxxxxxx.yaml ^
    --s3-bucket %cf_bucket% ^
    --output-template-file yyyyyyy.yaml ^
    --force

awslocal cloudformation deploy ^
    --template-file yyyyyyy.yaml ^
    --stack-name %stack_prefix%-storage ^
    --parameter-overrides ^
        StackPrefix=%stack_prefix% ^
        ApplicationKey=%application_key% ^
        EnvironmentType=%environment_type% ^
        CdnCertificateArn=%cdn_certificate_arn% ^
        ImagesCdnHost=%images_cdn_host% ^
    --capabilities CAPABILITY_NAMED_IAM CAPABILITY_IAM ^
    --no-fail-on-empty-changeset

### Environment

```markdown
- OS: Windows 10
- LocalStack: latest
```

**Comment by fabrezi** [comment]
I have seen a related issue with file upload to S3. Though I had no use of Cloudformation.

**Comment by srobayo222** [comment]
> I have seen a related issue with file upload to S3. Though I had no use of Cloudformation.

Well uploading normally with S3 it works, but in the main stage i have the CF scripts to do the deploy and upload the files that actually works on aws

**Comment by whummer** [comment]
Hi @srobayo222, thanks for reporting. Just to confirm - this issue is about persistence of S3 buckets and objects, is that right? Can you please share the LocalStack startup configuration you're using (e.g., docker-compose.yml). 

We have recently pushed a number of fixes for S3 persistence - can you please pull the `latest` Docker image and give it another try? Please keep us posted on how it goes.. Thanks!

**Comment by dominikschubert** [comment]
Closing since there hasn't been a response in a while.

As @whummer  mentioned we've heavily changed the persistence mechanism in the meantime. You can read more about it on our [1.0 release blog post](https://localstack.cloud/blog/2022-07-13-announcing-localstack-v1-general-availability/#improved-persistence-support)
