### ISSUE TITLE
feature request: launch port-specific services on predefined ports

### ISSUE THREAD

**Issue by mbklein** [localstack/localstack#5405]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

We have preset configuration files that specify the ports where certain services are expected to be found. However, localstack chooses ports (4510, 4511, etc.) in the order in which the services are provisioned. Because we use Terraform for provisioning, we can't always guarantee the provisioning order, which makes it hard to predict which services are going to come up on which ports. It would make development and _especially_ automated/CI tests much easier to know in advance which port each service will be using when it comes up.

### 🧑‍💻 Implementation

The solution for RDS _might_ be the easiest, because the [`CreateDBInstance`](https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_CreateDBInstance.html) API already supports specifying a port. I'm not sure what the best choice would be for others – maybe a config file or environment variables that reserve ports for specific services based on a combination of the service name and instance name? For example:

```
RDS_MYDATABASE_PORT=4511
```

would reserve port 4511 for an RDS instance with the (case-insensitive) name MYDATABASE (MyDatabase, mydatabase, etc.)

**Comment by thrau** [comment]
Hey Michael @mbklein. I would definitely be open to introducing a more predictable or configurable behavior for assigning ports. Overall though, it seems to me that clients should never rely on explicit assumptions in the first place. Getting endpoints, url, or ports from the AWS entity descriptions seems to make more sense to me. But maybe I am missing something! Would be great to get some clarification.

**Comment by mbklein** [comment]
A lot of the components of our production infrastructure (DB, Elasticsearch cluster, Elasticache, and some things we run ourselves) are maintained using terraform and are addressed using Route53 and CloudMap. The addresses and ports are stable. (This is especially true of our RDS instance, which runs on the port of our choosing, which is the standard PostgreSQL port 5432.) For these services, we use configuration instead of discovery to point at those backend services. What we lose in automated adaptability, we gain in simplicity and startup time from not having to request service descriptions and configure on the fly. We certainly _could_ add a discovery layer, but we've found that there are certain services that are stable enough that we just don't _have_ to. For example, when I use Terraform to provision our stack on AWS, I _know_ PostgreSQL is going to be on port 5432, and I _know_ I can create a Route53 alias for the hostname. There's nothing for the app to discover; it's all known in advance. There may come a time when we need to add a discovery layer, but for now static configuration is working well for us. Since AWS makes this possible, even with repeated teardown/rebuild provisioning, it would be great for localstack to do so as well.

**Comment by thrau** [comment]
Thanks for the clarification, that makes sense to me.

My thought so far:

I think the biggest challenge will be to agree on a clean configuration interface for localstack for this. There are two limiting factors
* We cannot assign single ports to what we call "external services" (postgres instances, elasticache clusters, ...), as localstack can potentially spawn multiple instances of those things (you can have several elasticache clusters at once). So we need a range of ports to select from.
* Currently we have a single port range for _all_ external services . that was just recently extended in #5385 

so to get the behavior that Michael is describing, we will need a way to define service-specific port ranges that are used when spawning new instances. however i think this is either going to involve a very verbose configuration to create deterministic behavior when selecting from port ranges (e.g., 5432 when creating an RDS instance), or work only work under very specific assumptions (e.g., only a single postgres instance will ever be started, and it's started first, and we start from the beginning of the service port range, which will be port 5432).

for example we could define something like:

`EXTERNAL_SERVICE_PORT_START_<service>`, and so on. and if these vars are not available, then we can fall back to the default port `EXTERNAL_SERVICE_PORT_START` value.
i have no good solution on how to get the deterministic port selection behavior from a range of ports though...

any thoughts? @alexrashed @whummer ?

**Comment by mbklein** [comment]
I completely agree with you about how tricky this can be. One thing that might make it easier for RDS is that the CreateDBInstance API call does take a port parameter. For example, using the CLI:

```shell
awslocal rds create-db-instance \
  --db-instance-class db.t3.medium --db-instance-identifier mydatabase \
  --engine postgres --engine-version 11.12 --port 4512 \
  --master-username postgres --master-user-password thisIsNotAGoodPassword
``` 

I think it would be completely reasonable to require that any specified port be somewhere in localstack's service port range, and to throw an error if that port is already being used by another DB instance or service. It looks like the ElastiCache `CreateCacheCluster` API also takes a port parameter, which would solve that problem as well.

What other services use service ports and not just the regular localstack `EDGE_PORT`?

**Comment by alexrashed** [comment]
> What other services use service ports and not just the regular localstack EDGE_PORT?

Another example would be ElasticSearch and OpenSearch in their new implementations (0.14+).

This topic is somewhat tricky, because we always need to make sure that a port used by LocalStack is properly mapped to the host system (since usually LocalStack is executed within a docker container, without the network interface directly attached to the host network). This is why we introduced the external service port range.

As @thrau pointed out, a single port is not an option, since most services allow the creation of multiple instances where LocalStack does not have the possibility to spawn individual machines where the same port can be used multiple times.
I also agree with @thrau that configuration options for individual service port ranges would become quite complex / verbose.

Using a port given by the API could be a feasible option, however it has the potential to break for other users. I'm thinking of the opposite scenario where a user uses the same port all the time in the AWS calls (since it's assumed that one does not have to care about the ports), but has some kind of service discovery in place which uses the endpoint returned by LocalStack.
However, the external service port manager would allow to hand a preferred port:
https://github.com/localstack/localstack/blob/b25fc90d823a60d191956ec7894330fb3c6d88a5/localstack/utils/common.py#L549

Maybe we could add an opt-in config-variable to enable the usage of the given port?
In any case, we should make sure that we introduce a service-independent behavior (i.e. solve the problem in the same way across services).
