### ISSUE TITLE
bug: Poetry install localstack['runtime'] fails 

### ISSUE THREAD

**Issue by orientalperil** [localstack/localstack#5520]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Poetry runs dependency resolver forever when I run `poetry add localstack['runtime']`

### Expected Behavior

Install should succeed

### How are you starting LocalStack?

Custom (please describe below)

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    Can't start it because it failed to install

### Environment

```markdown
- OS: Mac 10.15.6
- LocalStack: 0.14.0
```

**Comment by whummer** [comment]
Thanks for reporting @orientalperil . We're currently using `pip`, and indeed, seems that `poetry` is a bit more strict when it comes to resolving the dependencies / version constraints. 

Just to confirm - your use case is to install the runtime dependencies locally on the host, outside of Docker, correct?

I was able to replicate this issue - `poetry` seems to run indefinitely when attempting to install the runtime package. We'll try to dig a bit more into that - were you already able to extract some debug logs from `poetry`? Thanks

**Comment by orientalperil** [comment]
Yes I am trying to use it outside of Docker.  I do have the Docker version working, but it's slower compared to running without Docker.

I didn't look deeper into the logs.  Just saw that it didn't work so I left it.  This isn't a blocker for me as I can manually install with pip and only use localstack as a dev tool, but it definitely seems unintentional.

**Comment by dimbleby** [comment]
You also reported this at https://github.com/python-poetry/poetry/issues/5217, where I did some investigation.

It turns out that localstack's dependency on `awscli>=1.14.18` is problematic for poetry.  During solving, poetry:

- first tries to deal with `pyyaml>=5.1`, selecting version 6.0
- later tries to deal with `awscli>=1.14.18` - and has to trawl through the _thousands_ of versions of that project satisfying that constraint but which are not compatible with pyyaml 6.0
- (which I think then also reveals accidentally-quadratic edge cases, which normally don't matter)

if localstack wanted to help out poetry users, the simplest thing would be to bump the lower bound on awscli to some much more recent version - so that poetry could _quickly_ learn that none of them were compatible with pyyaml 6.0 (at which point it backtracks and finds a solution).

**Comment by whummer** [comment]
Great, thanks for following up on that thread @dimbleby - we'll get that change in shortly! 👍

**Comment by whummer** [comment]
This has now been updated - when you get a chance, can you please try again and let us know if it works @orientalperil  @dimbleby ? Thanks

**Comment by orientalperil** [comment]
Because there isn't a new release yet, what's the command to install localstack[runtime] from git with poetry?

**Comment by orientalperil** [comment]
Yes can confirm that this works successfully. Thanks @whummer!

`poetry add "git+ssh://git@github.com/localstack/localstack.git[runtime]"`
