### ISSUE TITLE
bug: DynamoDB batch write operation is too slow

### ISSUE THREAD

**Issue by harleyguru** [localstack/localstack#5576]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am trying to do batch write to dynamo db table with test data.
But one batch operation is creating individual lambda functions for each put request, which leads the localstack container dead.
The reason is that localstack is creating  lambda container per each put request (so if batch request includes 25 put requests, it will create and run 25 of lambda containers).. This is really wondering..
So if we are trying to put 1K of items, localstack container dies simply..
wondering how other users use localstack regarding dynamodb... hydrating table with test data is very basic process for local test..

### Expected Behavior

I should mock real batch operation against the table

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

docker-compose up

### Environment

```markdown
- OS: macOS Catalina
- LocalStack: latest
```

### Anything else?

I am a pro user

**Comment by giograno** [comment]
Thanks @harleyguru for reporting the problem. Unfortunately, I am going to close the issue mostly because of the LocalStack version used. We shipped a large number of improvements with the latest versions. Most notably, we now have a new implementation for our Lambda provider (see [docs](https://docs.localstack.cloud/user-guide/aws/lambda/) that is much more performant. 
Of course, if you are still experiencing the issue with the current version, feel free to open a new ticket.
Thank you very much.
