### ISSUE TITLE
Circular dependency between localstack and localstack-ext

### ISSUE THREAD

**Issue by dorranh** [localstack/localstack#5634]
Hi localstack team,

It appears that in the latest versions of `localstack`, `localstack-ext` declares a circular dependency on `localstack`. While this does not cause issues for package managers like `pip`, it makes it so that `localstack` must be patched in order to package / install it using tools like `nix` which do a more thorough job of dependency resolution.

As far as I can tell, there does not seem to be a need for `localstack-ext` to depend on `localstack` directly. Is this correct, and if so would it be possible to remove `localstack` from the `setup.cfg` for `localstack-ext`? I am also happy to submit a PR for this but couldn't find the source for `localstack-ext`.

Note: I'm currently using `localstack` version `0.14.0.9` and `localstack-ext` version `0.14.0.23`.

**Comment by thrau** [comment]
Hello Dorran @dorranh, welcome to the community!

Unfortunately the circular dependency is currently needed because of the way our release and build pipeline is structured, and simply removing the dependency would break localstack for localstack pro users. localstack-ext depends on localstack, because localstack serves as a library for localstack-ext. In turn, localstack depends on localstack-ext, such that when we build and release the CLI distribution to pypi, it includes the localstack-ext extension code. We have an ongoing debate internally about the nature of this, and we're looking into ways of resolving it, but this is not something that will be easily fixed. Sorry!

It would be interesting for me to understand what exactly you are trying to do, and what you are using the localstack pip package for.

**Comment by dorranh** [comment]
Hi @thrau, thanks for the additional background! That does indeed sound like a tricky problem to untangle. 

We are currently using localstack in one of our projects where we are using [Nix](https://nixos.org/) for providing dev dependencies. The technical limitation is actually on Nix's end and is that it explicitly does not handle cases where there are cycles in the dependency graph. We are performing some patching at build-time to work around this, but this is more of a one-off solution. Ideally we would like to offer the free version of localstack in the main Nix package set, but this is a bit blocked by this issue. I also think that this issue probably affects more build systems than just Nix since Bazel also sometimes has issues with cyclical dependencies.

**Comment by thrau** [comment]
Just to clarify: are you including the localstack package to add the CLI to your distribution, or are you using localstack as a library?

**Comment by dorranh** [comment]
This would be for the former: providing the localstack CLI in our dev environment (or also making it available as a part of the core [`nixpkgs`](https://github.com/NixOS/nixpkgs) package set).

**Comment by brendo-m** [comment]
Hey @dorranh are you willing to share your nix install of localstack please? Just had a need for it today

**Comment by dorranh** [comment]
Hi @brendo-m, sure thing, though be warned that it is quite a hacky solution :slightly_smiling_face:. In our case I opted to use [poetry2nix](https://github.com/nix-community/poetry2nix) as a quick solution since many of the python dependencies for localstack are not yet in nixpkgs. Here's a [gist](https://gist.github.com/dorranh/4317dcc5ea301ac5aec4e03edc0e9ffc).

**Comment by brendo-m** [comment]
This is great, thanks!

**Comment by gsornsen** [comment]
Thank you @dorranh. I've been banging my head on my keyboard for a few days on this and also haven't found a workaround for the circular dependency to make it part of `nixpkgs`

**Comment by gsornsen** [comment]
Howdy @dorranh and @brendo-m,

I was able to get this running with [mach-nix](https://github.com/DavHau/mach-nix) and the localstack container running on the host via [colima](https://github.com/abiosoft/colima). This should also work if you use Docker Desktop/Linux.

Check out the [gist and demo here](https://gist.github.com/gsornsen/7085837cdff57d6c92a1b50f7a3c5fd4).

**Comment by calebmer** [comment]
I’m trying to use localstack with [Bazel](https://bazel.build/) and can confirm the cycle is also an error for Bazel. Bazel (like nix) doesn’t support cycles between packages because it breaks incremental compilation.

```
ERROR: /private/var/tmp/_bazel_calebmer/bdcb08d3184e81b525008307e7ae9d3a/external/pypi_localstack/BUILD.bazel:22:11: in py_library rule @pypi_localstack//:pkg: cycle in dependency graph:
.-> @pypi_localstack//:pkg (8c7c8a83495a6b29f5e61b94373e857884c6b6f4ed04fcd868a9a81a5d062e34)
|   @pypi_localstack_ext//:pkg (8c7c8a83495a6b29f5e61b94373e857884c6b6f4ed04fcd868a9a81a5d062e34)
`-- @pypi_localstack//:pkg (8c7c8a83495a6b29f5e61b94373e857884c6b6f4ed04fcd868a9a81a5d062e34)
ERROR: Analysis of target '@pypi_localstack//:pkg' failed; build aborted
INFO: Elapsed time: 14.292s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (42 packages loaded, 3936 targets configured)
```

I’m going to see if Bazel lets me write a patch to remove the circular dependency…
