### ISSUE TITLE
bug: S3 does not respect region

### ISSUE THREAD

**Issue by maciejwalkowiak** [localstack/localstack#5748]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

S3 API does not respect region. Does not matter which region is used by the client, Localstack S3 API never returns `301` status code as real AWS API would. 

Additionally, `get-bucket-location` always returns the region of the client:

### Expected Behavior

All specific-bucket-related operation should require client to be configured to the same region as a bucket. Otherwise API should return `301` HTTP status code with a message like:

```
[PermanentRedirect] The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.
```

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

   docker-compose.yml

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

```
$ aws s3api create-bucket --bucket my-bucket --endpoint-url http://localhost:4566 --region eu-west-1
{
    "Location": "http://my-bucket.s3.localhost.localstack.cloud:4566/"
}
$ aws s3api get-bucket-location --bucket my-bucket  --endpoint-url http://localhost:4566 --region eu-west-2
{
    "LocationConstraint": "eu-west-2"
}
$ aws s3api get-bucket-location --bucket my-bucket  --endpoint-url http://localhost:4566 --region eu-west-1
{
    "LocationConstraint": "eu-west-1"
}
```

### Environment

```markdown
- OS: MacOS 12.2.1
- LocalStack: 0.14.1
```

**Comment by pinzon** [comment]
Hi @maciejwalkowiak, during my testing with AWS,  `get-bucket-location`  always returned the correct LocationConstraint of a bucket, which is not the case for Localstack, in that I concur with you.

But I'm no sure why you suggest that it should return a 301 when calling the method with a client setup with another region.

My changes only make sure that the correct LocationConstraint is returned.

**Comment by maciejwalkowiak** [comment]
@pinzon apologies I wasn't clear. `get-bucket-location` indeed should return a location. `301` should be returned in client is requesting a bucket (for example with `getObject`) from a different region than client is configured with.

**Comment by pinzon** [comment]
@maciejwalkowiak I've been working on making sure that Localstack returns a 301 code when the target bucket is in a different region from the client region. But unfortunately, it's not something should do. Because after receiving the 301, the botocore client will generate the new request but using `"{service}.{region}.amazonaws.com"` to generate the endpoint. So if you're working with localstack, and then it responds with a 301, your client will try again but using AWS.

The class that generates the endpoint allows for a new formatable string as a parameter but during the creation a service client, that parameter is not used. We could create a PR to botocore but it will probably be ignored and we would have to do it for every aws sdk.

Code that dictates the behaviour on a 301 response:
https://github.com/boto/botocore/blob/faa1a44afc58183de90111203ad62e172ec06fc8/botocore/utils.py#L1430

Definition of the class(ClientEventBridge) that handles the new endpoint generation for the redirect:
https://github.com/boto/botocore/blob/faa1a44afc58183de90111203ad62e172ec06fc8/botocore/client.py#L433

Generation of object of class ClientEventBridge for a service client:
https://github.com/boto/botocore/blob/faa1a44afc58183de90111203ad62e172ec06fc8/botocore/client.py#L98

**Comment by maciejwalkowiak** [comment]
Understood. Automatic redirect after receiving 301 is true for `boto` but not for SDKs (at least not for Java SDK).
