### ISSUE TITLE
bug: Kinesis Lambda sets StartingPosition to LATEST no matter what

### ISSUE THREAD

**Issue by akslick** [localstack/localstack#5774]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have a simple localstack pipeline:

Kinesis with a single shard
Single lambda function reading the data
When setting the lambda function event_source_mapping the StartingPosition is always being set to LATEST regardless of what was input. I have tried with awscli and boto3 with the same results. Am I doing something incorrectly?

No matter what I put in the --starting-position argument it always returns with LATEST selected.

I have tried with awscli and boto3 with the same results.

**Example awscli code:**

`aws --endpoint-url=http://localhost:4566 lambda create-event-source-mapping --function-name lambda_2_db --event-source arn:aws:kinesis:us-east-1:000000000000:stream/polling_single_shard --batch-size 100 --starting-position TRIM_HORIZON
`

**Console output:**
![image](https://user-images.githubusercontent.com/22774147/160868278-71380b99-0fa7-4d49-8017-dd700b4bc43b.png)

### Expected Behavior

I expected that the "StartingPosition" would be "TRIM_HORIZON"

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

    docker-compose up

#### To duplicate **Follow this guide until _Add an event source in AWS Lambda_** 
[https://docs.aws.amazon.com/lambda/latest/dg/with-kinesis-example.html](url)

**Then use this instead to create the lambda with TRIM_HORIZON**

```
   aws lambda create-event-source-mapping --function-name ProcessKinesisRecords \
--event-source  arn:aws:kinesis:us-west-2:123456789012:stream/lambda-stream \
--batch-size 100 --starting-position **TRIM_HORIZON**
```

When you get the return you will see that the lambda was created with StartingPosition = LATEST.

In AWS this code works as expected.

### Environment

```markdown
- OS: Windows 10
- LocalStack: latest
```

**Comment by SwatsonCodes** [comment]
Hi @akslick , thanks for bringing this issue to our attention! Currently LocalStack does not support the `TRIM_HORIZON` starting position. That's why you're seeing `LATEST` in the output even though that's not what you specified.
I took some time to look into what it would take to support `TRIM_HORIZON` and unfortunately it's nontrivial to implement due to the way our subscription logic currently works. I went ahead and created a "feature request" issue to track it here:
https://github.com/localstack/localstack/issues/5804
