### ISSUE TITLE
bug: error creating S3 Account Public Access Block

### ISSUE THREAD

**Issue by pasdam** [localstack/localstack#5802]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Terraform apply is returning the following error

```
Error: error creating S3 Account Public Access Block: InvalidParameter: 1 validation error(s) found.
│ - minimum field size of 1, PutPublicAccessBlockInput.AccountId.
│
│
│   with aws_s3_account_public_access_block.this,
│   on main.tf line 23, in resource "aws_s3_account_public_access_block" "this":
│   23: resource "aws_s3_account_public_access_block" "this" {
```

### Expected Behavior

Terraform should correctly apply the changes

### How are you starting LocalStack?

With a `docker run` command

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

```
docker run --rm -it -p 4566:4566 -p 4571:4571 localstack/localstack:latest
```

where latest is in my case is `a6e8aecd3945`.

I also tried with other images, i.e. `localstack/localstack-light:latest`.

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

```
terraform init
terraform apply
```

#### Code

```terraform
terraform {
  required_providers {
    aws = {
      version = "4.8.0"
    }
  }
}

provider "aws" {
  access_key                  = "test"
  secret_key                  = "test"
  region                      = "me-south-1"
  s3_use_path_style           = false
  skip_credentials_validation = true
  skip_metadata_api_check     = true
  skip_requesting_account_id  = true

  endpoints {
    s3 = "http://localhost:4566"
  }
}

resource "aws_s3_account_public_access_block" "this" {
  block_public_acls       = true
  ignore_public_acls      = true
  block_public_policy     = true
  restrict_public_buckets = true
}
```

### Environment

```markdown
- OS: macOS 12.3.1
- LocalStack: docker image localstack/localstack:a6e8aecd3945
```

**Comment by macnev2013** [comment]
Hello, @pasdam. Thank you for reporting the issue. 

The account id parameter is required by `aws_s3_account_public_access_block`. This should ideally be done automatically. However, because you have `skip_requesting_account_id = true`, it will skip fetching the `account_id`. 

To correct this behaviour, use `skip_requesting_account_id = false` or manually specify the account id inside  `aws_s3_account_public_access_block` as `account_id = "000000000000"`

Please do not hesitate to contact us if the problem persists. Thanks.
