### ISSUE TITLE
Filter not working for ec2 search-transit-gateway-routes for Version 0.13.2

### ISSUE THREAD

**Issue by TeLin1996** [localstack/localstack#6055]
Hi Team,

Currently for local stack version 0.13.2:
We found for ec2 search-transit-gateway-routes filter not working issue. 

Basically, if you add a filter with any of the following 
1. `attachment.resource-type`
2. `attachment.resource-id`
3. `attachment.transit-gateway-vpc-attachment-id`

to the request of `search-transit-gateway-routes`, local stack will return all the transit gateway routes that existed in the container whereas for real aws the transit gateway routes specific to the filter will be returned.

We also checked the later version of local stack release document, there are no updates on `transit-gateway-routes`.

**Comment by whummer** [comment]
Hi @TeLin1996 , thanks for reporting - version 0.13.2 is pretty outdated by now, can you please pull the `latest` Docker image and confirm if the problem still persists with the latest version? (the issue may be fixed in the meantime, even without notice in the release notes..). Thanks!

**Comment by manish481989** [comment]
Hi Team, 
We are still observing this issue on 0.14.4 version. 
Could you please plan to support this filter/functionality? 
Let us know if you need any additional information.
Thanks.

**Comment by HarshCasper** [comment]
Thank you for reaching out.

This issue will be closed because the LocalStack version that was reported is no longer supported.

If you're still experiencing this issue on a [supported version](https://hub.docker.com/r/localstack/localstack/tags) of LocalStack, please file a new issue for that version of LocalStack.

Thank you in advance. Your assistance is appreciated.
