### ISSUE TITLE
bug: Error when creating lambda permission

### ISSUE THREAD

**Issue by slee106** [localstack/localstack#6142]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When running `terraform apply` i get the following error

```
╷
│ Error: Invalid ARN or otherwise unable to get qualifier from ARN ("")
│
│   with module.project.module.<my_module>.aws_lambda_permission.lambda_permission,
│   on ..\..\modules\lambda-gateway-api\main.tf line 1, in resource "aws_lambda_permission" "lambda_permission":
│    1: resource "aws_lambda_permission" "lambda_permission" {
│
╵
``` 

### Expected Behavior

`terraform apply` to run successfully

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    `docker compose up -d`

Please find localstack section of docker compose below
```
localstack:
    image: localstack/localstack:latest
    # image: localstack/localstack:0.12.19.1
    container_name: localstack
    environment:
      - EXTRA_CORS_ALLOWED_ORIGINS=http://localhost:3000
      - LOCALSTACK_API_KEY=${LOCALSTACK_LICENSE}
      - DATA_DIR=/tmp/localstack/data
      - SERVICES=s3, lambda, iam, apigateway, events, cloudformation, cognito-idp, cognito-identity, ses, ec2, sqs # this can be a comma separated list of services you want to start
      - TZ=Europe/London
      - DEBUG=1
      - LAMBDA_EXECUTOR=docker-reuse
      - LAMBDA_DOCKER_NETWORK=localstack
      - LOCALSTACK_HOSTNAME=localstack
      - HOST_TMP_FOLDER=/tmp/localstack
      - TRANSPARENT_LOCAL_ENDPOINTS=0
      - DNS_LOCAL_NAME_PATTERNS='.cognito-idp.*.amazonaws.com'
      - DEFAULT_REGION=eu-west-1
    ports:
      - "53:53"
      - "53:53/udp"
      - "443:443"
      - "4566:4566"
    volumes:
      - "/tmp/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    awslocal s3 mb s3://mybucket

### Environment

```markdown
- OS: Windows 10
- LocalStack: 0.14.2
```

### Anything else?

The terraform scripts all run when running using localstack version `0.12.20` so i believe something was introduced in version `0.13.0`

**Comment by calvernaz** [comment]
Hi @slee106, thanks for reporting this! We happen to have a similar example in our repositories using the `aws_lambda_permission` that works properly in the latest localstack version. Do you mind to have a look at the example and compare with yours? 

https://github.com/localstack/localstack-terraform-samples/tree/master/apigateway-cognito-authorizer

**Comment by slee106** [comment]
Hi @calvernaz, i have had a look at the sample and compared it to my code. I have made some changes locally and it now works.

I was passing a variable of type `aws_api_gateway_rest_api` into a module and trying to reference the `execution_arn` from that variable. I have passed the `execution_arn` in explicitly and it now works.

**Comment by calvernaz** [comment]
Hi @slee106, thanks for following up. There's no need to open a new issue, we can work from here!

**Comment by calvernaz** [comment]
Hi @slee106 I don't see the same error as you do! I created a very basic example, could you perhaps add anything to it, that makes it reproducible in our side.

**Comment by slee106** [comment]
Hi @calvernaz, I am not sure why it was doing that but i am running it this morning on a clean run and it seems to be running fine. I will monitor for now and update if any change.

Thanks for your help :)

**Comment by calvernaz** [comment]
Hi @slee106, I'm looking into this issue and while trying to reproduce it I saw this error in localstack, 

```
DEBUG:localstack_ext.bootstrap.state_utils: Unable to read pickled persistence file /localstack/data/api_states/000000000000/iam/static/backend_state: Ran out of input
```

Do you see a similar log, when you run the TF apply twice?

**Comment by slee106** [comment]
Hi @calvernaz, Sorry I have been on holiday. No i don't see that when running twice

**Comment by slee106** [comment]
hi @silv-io / @calvernaz has there been any update on the first issue (passing a module)? Or the second issue (`cognito-user-group` error)?

**Comment by joe4dev** [comment]
Hi @slee106, I can share good New Year news:

## Lambda permissions

Lambda permissions were updated last week (PR #7336) and are available in our new Lambda provider through a feature flag (will become default by v2):

1. Add `- PROVIDER_OVERRIDE_LAMBDA=asf` to the environment in docker-compose
2. Remember to pull the latest image `docker pull localstack/localstack-pro:latest`

That could fix issues related to resolving ARNs when creating lambda permissions.

## Cognito user group

I can confirm that when using `aws_cognito_user_group` **without** an `role_arn`, the **second** `tflocal apply` yields a validation error:

```
│ Error: Error updating Cognito User Group: InvalidParameter: 1 validation error(s) found.
│ - minimum field size of 20, UpdateGroupInput.RoleArn.
│ 
│ 
│   with aws_cognito_user_group.main,
│   on main.tf line 33, in resource "aws_cognito_user_group" "main":
│   33: resource "aws_cognito_user_group" "main" {
```

because `role_arn` changes to `null` (as mentioned by @slee106 )

```
~ resource "aws_cognito_user_group" "main" {
        id           = "us-east-1_b8518b0806454a2d8b6abe8d7bf1e913/user-group"
        name         = "user-group"
      - role_arn     = "arn:aws:cognito-idp:us-east-1:000000000000:userpool/us-east-1_b8518b0806454a2d8b6abe8d7bf1e913" -> null
        # (3 unchanged attributes hidden)
    }
```

There is another unexpected change in the resource `aws_cognito_user_pool`: `- software_token_mfa_configuration {}`
Querying such a non-existing config should probably return `{}` instead of none through `awslocal cognito-idp get-user-pool-mfa-config --user-pool-id us-east-1_b8518b0806454a2d8b6abe8d7bf1e913`

### Root Cause

There were several parity issues when creating a new user pool. LocalStack behaved differently than AWS and therefore subsequent Terraform updates caused these problems.

### Fix

I prepared a PR that fixes these parity issues in Pro and will notify here when it's merged.

## Background

Terraform implementation of user group: https://github.com/hashicorp/terraform-provider-aws/blob/c3a3694e8b0dad5fc9a9357582d1d02ebe0ec28e/internal/service/cognitoidp/user_group.go#L20

There was an almost identical Terraform issue but that was fixed long ago (2018) https://github.com/hashicorp/terraform-provider-aws/pull/4237.
