### ISSUE TITLE
Creating DB and tables in Redshift

### ISSUE THREAD

**Issue by farzdeepsingh** [localstack/localstack#63]
I am still new to localstack and was wondering if we will be able to create DB/tables in redshift mock service and execute sql commands ?.

**Comment by whummer** [comment]
Thanks for the request. This has been discussed in a previous ticket: https://github.com/atlassian/localstack/issues/28 . The actual query capabilities (i.e., accessing Redshift via JDBC, create DB/tables, execute SQL commands) are not supported in LocalStack because at this stage it does not seem feasible to mock the entire query engine. If you know how this can be achieved, though, I would be happy to accept a pull request or discuss possible solutions.

**Comment by whummer** [comment]
This one looks promising and could potentially be integrated: https://github.com/opt-tech/redshift-fake-driver . Did you come across any other Redshift mock implementation @farzdeepsingh ?

**Comment by farzdeepsingh** [comment]
This definitely seems promising and I haven't seen any other Redshift mock implementation.

**Comment by whummer** [comment]
Closing in favor of #833
