### ISSUE TITLE
Docker compose down with `LAMBDA_EXECUTOR` `docker-reuse` fails to remove network

### ISSUE THREAD

**Issue by xtaixe** [localstack/localstack#6312]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

We use LocaStack with Docker Compose and I'm testing if we can use `LAMBDA_EXECUTOR` `docker-reuse`. I've tested both with Stay-open mode enabled and disabled, but when running `docker compose down` it always fails due to
`failed to remove network my-network: Error response from daemon: error while removing network: network my-network has active endpoints`.  We use `LAMBDA_DOCKER_NETWORK`, so it seems that the lambda containers remain active. I also tried using `--remove-orphans` with no luck.

Could LocalStack shut the lambda containers down when itself is being shut down?

### Expected Behavior

Even if reused, the lambda containers are shut down when LocalStack is shut down and `docker compose down` finishes successfully.

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

Start LocalStack with docker compose with:
- `LAMBDA_EXECUTOR` `docker-reuse`
- `LAMBDA_DOCKER_NETWORK` set to the docker compose network that docker compose creates by default
 
Make sure a Lambda is triggered and a Lambda container is started.
Run `docker compose down`

### Environment

```markdown
- OS: macOs 12.4
- LocalStack: 0.14.2
```

**Comment by dfangl** [comment]
Hi! This should have been fixed with #6000. Can you try LocalStack version 0.14.3 or higher and check if this solves your issue?

**Comment by xtaixe** [comment]
Getting the same error with `0.14.3`.

**Comment by dfangl** [comment]
Can you please send/attach the LocalStack logs of a run where this happens? That would help us track down that issue.
Please also attach the full docker-compose configuration you are using.

**Comment by xtaixe** [comment]
Actually, from a few test runs, it seems that this might have actually been fixed in `0.14.3` and now the problem is caused by calling `docker compose down` with `--timeout 0` by default in our case. If I give more time things seem to work fine.  Happy to hear alternatives, but that is something we can change on our side to make things work (once we manage to upgrade to `0.14.3`, as we are blocked by other issues).

@dfangl unless you think there are other improvements that can be done around this or using `--timeout 0`, feel free to close the issue.

**Comment by dfangl** [comment]
Hi @xtaixe !
Sadly, using --timeout 0 will result in the LocalStack container to be immediatly killed. LocalStack will shutdown and stop the lambda containers if it recieves a sigterm signal, but on sigkill there is no chance in any cleanup. Since lambda containers are managed by localstack and not known to docker-compose, they will be orphaned then, including the issue with network removal (they are still connected to the docker-compose created docker network).

Please set the timeout higher. Depending on the running resources, a couple seconds should suffice, but the normal docker-compose timeout (I think its 10s?) should be more then enough.

I will keep this issue open for know, since @ShedPlant still has an issue with this, but maybe it is similar.

**Comment by dfangl** [comment]
I will close this for now, as original issue is resolved. Please make sure not to use --timeout 0 (or some small value), to allow LocalStack to cleanup its containers.
