### ISSUE TITLE
S3: ContentLength incorrect on head-object

### ISSUE THREAD

**Issue by ThisIsMissEm** [localstack/localstack#638]
Hi! I've noticed that when performing a head-object, the ContentLength comes back as "0" instead of the file size.

```
$ aws s3api head-object --endpoint-url http://localhost:4572 --bucket attachments --key 32a795c9-2cbc-4e88-a2df-367180c13845.png
{
    "LastModified": "Mon, 05 Mar 2018 22:24:38 GMT",
    "ContentLength": 0,
    "ETag": "\"785830eb951e3e586d568a818df561b7\"",
    "ContentDisposition": "inline",
    "ContentType": "image/png",
    "Metadata": {
        "uploader": "12"
    }
}
```

In comparison:

```
$ aws s3api list-objects --endpoint-url http://localhost:4572 --bucket fa-sag-sp-attachments
{
    "Contents": [
        {
            "Key": "32a795c9-2cbc-4e88-a2df-367180c13845.png",
            "LastModified": "2018-03-05T22:24:38.983Z",
            "ETag": "\"785830eb951e3e586d568a818df561b7\"",
            "Size": 215945,
            "StorageClass": "STANDARD",
            "Owner": {
                "DisplayName": "webfile",
                "ID": "75aa57f09aa0c8caeab4f8c24e99d10f8e7faeebf76c078efc7c6caea54ba06a"
            }
        }
    ]
}
```

```
$ aws s3api get-object --endpoint-url http://localhost:4572 --bucket fa-sag-sp-attachments --key 32a795c9-2cbc-4e88-a2df-367180c13845.png /tmp/file      
{
    "LastModified": "Mon, 05 Mar 2018 22:24:38 GMT",
    "ContentLength": 215945,
    "ETag": "\"785830eb951e3e586d568a818df561b7\"",
    "ContentDisposition": "inline",
    "ContentType": "image/png",
    "Metadata": {
        "uploader": "12"
    }
}
```

On actual S3, the ContentLength is always returned in the head-object JSON as being equal to that in the get-object JSON.

**Comment by jonassvalin** [comment]
This is a duplicate of an issue I opened a little while ago: 
https://github.com/localstack/localstack/issues/631

Unfortunately it has not been processed yet.

**Comment by ThisIsMissEm** [comment]
@jonassvalin oh! I must've missed that issue when searching for related issues.

**Comment by ThisIsMissEm** [comment]
Okay, so, I've done some investigation: Moto returns the correct content-length, however, there's some code in the s3_listener code which ignores that and returns an incorrect content-length header: https://github.com/localstack/localstack/blob/master/localstack/services/s3/s3_listener.py#L522-L524

I think the correct patch would be to indent those lines, so only if we're modifying the XML response do we update the content-length.

**Comment by ThisIsMissEm** [comment]
Okay, I tried to work on a patch to validate the above, but I'm unable to get localstack to respond to any print/LOGGER statements, nor can I get tests to fail by inserting a test that should fail. I've no idea how to develop on the localstack codebase, and there's not enough documentation for me to take this any further.

**Comment by vurt007** [comment]
:+1 on on this removal of the content-length header breaks clients (for example Spark) that depend on the content length in HEAD requests in order to pre determine the size of the content before making a get request.
According to this [https://github.com/akka/akka-http/issues/377](https://github.com/akka/akka-http/issues/377) sending the content-length with a HEAD request is valid.

Looks like the fix this issue [#541](https://github.com/localstack/localstack/issues/541) , introduced this ...  changing the indentation would change the fix for 541 ...
Commenting out
`if isinstance(response._content, (six.string_types, six.binary_type)):`  and keeping the indentation 
fixes it for the HEAD but would break 541,  for delete requests the 199 content length comes straight from the moto server, so if the content-length 199 is  incorrect for a DELETE request, then the bug is upstream in moto. 
Could add a conditional reset of the content-length for delete requests of course

**Comment by ThisIsMissEm** [comment]
Yeah, either way, the fix for #541 breaks HEAD requests. Most likely it's better to fix in upstream than in localstack, but if we want a temporary fix in localstack, then we should make it specific for the DELETE case.

My use case for HEAD is to get the metadata about the object without getting the whole object.

**Comment by whummer** [comment]
@ThisIsMissEm what is the status of this issue, does this problem persist in the latest version, or has it been fixed in #669?

**Comment by ThisIsMissEm** [comment]
I'll give it a test in a little bit, will follow up today.

**Comment by ThisIsMissEm** [comment]
Confirmed, #669 fixes this issue. Tested using the latest Docker image.
