### ISSUE TITLE
pre-signed post 500 issue

### ISSUE THREAD

**Issue by kingster307** [localstack/localstack#6531]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

sequential POST's with fresh presigned post URL's fail with 500 error

 

### Expected Behavior

POST should be successful & yield 204

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

[Repo Here](https://github.com/kingster307/localstack_post_presigned_error) 

See ReadMe for instructions & notes

### Environment

```markdown
- OS: Mac M1
- LocalStack: 1.0.1
```

**Comment by bentsku** [comment]
Hello and thanks for your report. Your error message seems to be linked to the same issue mentioned here: #6588 

There's a PR soon to be merged #7365

I'll notify you again once this is ready and in our latest image.

**Comment by bentsku** [comment]
Hello again,

The fix is now part of the latest Docker image, you can get it by running docker pull localstack/localstack:latest.

In the meantime, we have been working on a new implementation of S3, and it is now available under a feature flag. You can try starting LocalStack with PROVIDER_OVERRIDE_S3=asf (for configuration of LocalStack, you can see [here](https://docs.localstack.cloud/references/configuration/)). We have overhauled the service globally, and pre-signed URL are part of it, and our efforts to increase parity will be directed towards this new implementation. It will become the default in the next major release.
We'd appreciate the feedback as well!

Thanks again for your report!
