### ISSUE TITLE
ARN being passed into event is missing trailing slash 

### ISSUE THREAD

**Issue by kingster307** [localstack/localstack#6533]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Arn being passed into event is missing trailing slash 

**current - arn:aws:lambda:us-west-2:000000000000:function:s3OnObjectCreatedLambda-b79d29d**

### Expected Behavior

ARN being passed into event has trailing slash 

**expected - arn:aws:lambda:us-west-2:000000000000:function:s3OnObjectCreatedLambda-b79d29d/**

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

run a lambda against localstack & log the event 

### Environment

```markdown
- OS: mac m1
- LocalStack: 1.0.1
- lambda runtime: python 3.7
```

### Anything else?

noticed this while running tests against an authorizer that validates ARN....trailing slash is present in AWS env but not localstack

**Comment by joe4dev** [comment]
Hi @kingster307, thanks for reaching out.

Can you please clarify where the ARN comes from?

* a) Is the arn part of a custom event (e.g., `aws --endpoint-url=http://localhost:4566 lambda invoke --function-name my-lambda --cli-binary-format raw-in-base64-out --payload '{ "arn": "arn:aws:lambda:us-west-2:000000000000:function:s3OnObjectCreatedLambda-b79d29d/" }' response.json`)?
* b) Does the arn come from an S3-triggered lambda? (e.g., the s3 arn in an S3 PUT event doesn't contain a trailing slash in the [AWS example](https://docs.aws.amazon.com/lambda/latest/dg/with-s3-example.html))
* c) Does the arn come from an environment variable (e.g., `AWS_LAMBDA_FUNCTION_INVOKED_ARN` in LocalStack)

I couldn't reproduce the issue in the latest version, neither using Python nor Nodejs runtimes. Are there still any trailing slashes that get removed?

**Comment by kingster307** [comment]
@joe4dev in this specific case it was a apigw authorizer lambda event. ARN coming from apigw 

request -> apigw route -> authorizer lambda

**Comment by joe4dev** [comment]
I tried to reproduce the issue with a TOKEN-based authorizer in Nodejs and a REQUEST-based authorizer in Python but the `event.methodArn` with a trailing slash looks identical in LocalStack and AWS, for example:

```
arn:aws:execute-api:us-east-1:123456789012:ymy8tbxw7b/testStage/GET/
````


@kingster307 Can you share some more detail?

1. What type of apigw authorizer is it?

* apigwv1 or apigwv2 
* TOKEN or REQUEST authorizer
* REST API or HTTP API

2. Does the "arn being passed into event" refer to `methodArn` (v1) / `routeArn` (v2) or something else?

* methodArns have the format `"arn:aws:execute-api:{regionId}:{accountId}:{apiId}/{stage}/{httpVerb}/[{resource}/[{child-resources}]]"` (e.g., `"arn:aws:execute-api:us-west-2:123456789012:ymy8tbxw7b/*/GET/"`) according to the [AWS docs](https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-lambda-authorizer-input.html). For HTTP APIs, input event examples for v1 and v2 are given in [AWS docs](https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-lambda-authorizer.html#http-api-lambda-authorizer.payload-format).

3. Why does the ARN point to a lambda function if it is an apigateway authorizer?

4. What is the runtime of the authorizer lambda?

**Comment by kingster307** [comment]
run make all you'll see the authorizer will fail due to the arn....the arn doesn't contain the trailing slash in localstack but does in AWS where this authorizer works....[see repo here](https://github.com/kingster307/localstack_authorizer_bug)

**Comment by joe4dev** [comment]
Update based on conversation through pro support.

## Problem

When using custom lambda token authorizers with apigateway (v1), the apigateway creates an event that is passed into the authorizer lambda function. The methodArn within this event differs from AWS and causes authorizers that validate the methodArn to fail. In this particular case, the methodArn contains a trailing slash in AWS, which is not present in LocalStack.

Surprisingly, the number of trailing slashes in methodArn depends on how the rest api is invoked (tested against AWS, see new snapshots):

GET /demo => `arn:aws:execute-api:<region>:111111111111:<rest-api-id>/test/GET/demo`
GET /demo/ => `arn:aws:execute-api:<region>:111111111111:<rest-api-id>/test/GET/demo/`
GET /demo// => `arn:aws:execute-api:<region>:111111111111:<rest-api-id>/test/GET/demo//`
GET /demo/// => `arn:aws:execute-api:<region>:111111111111:<rest-api-id>/test/GET/demo///`
GET /demo# => `arn:aws:execute-api:<region>:111111111111:<rest-api-id>/test/GET/demo`
GET /demo?key=value => `arn:aws:execute-api:<region>:111111111111:<rest-api-id>/test/GET/demo`

Another parity issue: Some of these invocations fail because resource matching in LocalStack differs from AWS. Example: test_lambda_token_authorizer currently fails for GET /demo// with assertion error assert 500 == 200.

## Solution

We fixed this issue by configuring routes to use `strict_slashes=False,` in [router_asf.py](https://github.com/localstack/localstack/pull/7557/files#diff-c6c59f3b7b2e86402668f3346dac7bc2d6f38476eba87917b02917e3375a1418). See:

* https://github.com/localstack/localstack/pull/7557
* https://github.com/localstack/localstack-ext/pull/1305 (private repo)

**Comment by joe4dev** [comment]
Resolved for apigateway v1 (see PRs above)
