### ISSUE TITLE
feature request: AWS Neptune with neo4j library + bolt driver usage

### ISSUE THREAD

**Issue by leo6104** [localstack/localstack#6592]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

https://docs.aws.amazon.com/neptune/latest/userguide/access-graph-opencypher-bolt.html 

In Official Document, there is opencyper + neo4j bolt driver support. 

I saw Localstack neptune example and it seems only explain gremlin usage via websocket cluster url.

Hope it could be support for bolt driver + neo4j example

### 🧑‍💻 Implementation

In AWS document, althought the Bolt spec states that Bolt can connect using either TCP or WebSockets, Neptune only supports TCP connections for Bolt.

Bolt driver + neo4j python usage
```python
from neo4j import GraphDatabase, Session

GraphDatabase.driver('bolt://127.0.0.1:8182')
```

**Comment by whummer** [comment]
Hi @leo6104, thanks for reporting. We have now pushed a first version of Neo4J/Bolt support - can you please pull the `latest` LocalStack Docker image and give it a try? 

Please note that you'll need to configure `GRAPH_DB_TYPE=neo4j` in the LocalStack container environment (e.g., in your docker-compose.yml) in order to enable this new functionality. The `Port` number returned from the `create-db-cluster` operation can then be used to connect with a Bolt compatible client, e.g., `GraphDatabase.driver('bolt://...')`. 

Hope that helps - please keep us posted on how it goes. Would be great if you could share a few more details about your requirements, so we can ensure that your use case is covered. Thanks!

**Comment by whummer** [comment]
Closing as resolved - please keep us posted on how it goes @leo6104 . Looking forward to getting your feedback! Let us know if anything is missing.. 👍

**Comment by pandaeli** [comment]
second this @whummer

**Comment by HarshCasper** [comment]
Hi @mbaroody @pandaeli — Please have a look at our docs: https://docs.localstack.cloud/references/configuration/#neptune

If its insufficient, I can look into building a small sample/tutorial for you :) /cc: @steffyP
