### ISSUE TITLE
bug: LocalStack 1.0.5. crashes when you attempt to run it in host mode

### ISSUE THREAD

**Issue by paultipper** [localstack/localstack#6655]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If you do a `git pull` from the master branch, execute `make install` and then try to run LocalStack in host mode by typing `make start`, LocalStack crashes with the following error:

```
2022-08-11T16:27:29.055 ERROR --- [  MainThread] localstack_ext.plugins     : error enabling pro code
Traceback (most recent call last):
  File "/Users/ac8dqzz/myrepos/localstack/.venv/lib/python3.8/site-packages/localstack_ext/plugins.py", line 71, in setup_pro_infra
    try:from localstack_ext.aws.protocol import service_router as C;from localstack_ext.bootstrap.dashboard import dashboard_extended as D;from localstack_ext.services import edge;from localstack_ext.utils.aws import aws_utils as E;D.patch_dashboard();C.patch_service_router();edge.patch_start_edge();patch_start_infra();E.patch_aws_utils();set_default_providers_to_pro()
  File "/Users/ac8dqzz/myrepos/localstack/.venv/lib/python3.8/site-packages/localstack_ext/services/edge.py.enc", line 11, in <module>
  File "/Users/ac8dqzz/myrepos/localstack/.venv/lib/python3.8/site-packages/localstack_ext/services/iam/policy_enforcer.py.enc", line 24, in <module>
  File "/Users/ac8dqzz/myrepos/localstack/.venv/lib/python3.8/site-packages/localstack_ext/utils/aws/aws_utils.py.enc", line 12, in <module>
  File "/Users/ac8dqzz/myrepos/localstack/localstack/utils/aws/message_forwarding.py", line 10, in <module>
    from localstack.services.apigateway.helpers import extract_query_string_params
  File "/Users/ac8dqzz/myrepos/localstack/localstack/services/apigateway/helpers.py", line 392, in <module>
    def extract_query_string_params(path: str) -> list[str, Dict[str, str]]:
TypeError: 'type' object is not subscriptable
2022-08-11T16:27:29.112  WARN --- [  MainThread] l.services.internal        : Enabling diagnose endpoint, please be aware that this can expose sensitive information via your network.
Error starting infrastructure: cannot import name 'cache' from 'functools' (/Users/ac8dqzz/opt/anaconda3/lib/python3.8/functools.py) Traceback (most recent call last):
  File "/Users/ac8dqzz/myrepos/localstack/localstack/services/infra.py", line 416, in start_infra
    hooks.on_infra_start.run()
  File "/Users/ac8dqzz/myrepos/localstack/localstack/runtime/hooks.py", line 63, in run_in_order
    fn_plugin(*args, **kwargs)
  File "/Users/ac8dqzz/myrepos/localstack/.venv/lib/python3.8/site-packages/plugin/core.py", line 183, in __call__
    return self.fn(*args, **kwargs)
  File "/Users/ac8dqzz/myrepos/localstack/.venv/lib/python3.8/site-packages/localstack_ext/services/iam/plugins.py", line 7, in add_iam_enforcement_listener
    def add_iam_enforcement_listener():from localstack.aws.handlers import serve_custom_service_request_handlers as A;from localstack_ext.services.iam.policy_engine.handler import IamEnforcementHandler as B;A.handlers.append(B())
  File "/Users/ac8dqzz/myrepos/localstack/.venv/lib/python3.8/site-packages/localstack_ext/services/iam/policy_engine/handler.py.enc", line 6, in <module>
  File "/Users/ac8dqzz/myrepos/localstack/.venv/lib/python3.8/site-packages/localstack_ext/services/iam/policy_engine/engine.py.enc", line 6, in <module>
ImportError: cannot import name 'cache' from 'functools' (/Users/ac8dqzz/opt/anaconda3/lib/python3.8/functools.py)
```

### Expected Behavior

LocalStack should launch successfully in host mode.

### How are you starting LocalStack?

With the `localstack` script

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    make install
    make start

### Environment

```markdown
- OS: macOS Monterey
- LocalStack: latest (source code pulled from the master branch)
```

**Comment by bentsku** [comment]
Hello Paul,
It seems there are some issues with import from the standard libs. To run in host mode, Localstack needs Python 3.10. The logs seem to indicate 3.8. Is there any possibility to launch it with 3.10? It should at least resolve those issues. Thank you!

**Comment by nathanmcgarvey** [comment]
Related: https://github.com/localstack/localstack/issues/6626#issuecomment-1209664510

If nothing else, the front README.md that shows up on GitHub and PyPI and the official documentation site (https://docs.localstack.cloud/get-started/#localstack-cli) says "(Python 3.7 up to 3.10 supported)". Obviously this is no longer true as you cannot run localstack on a stock Debian-stable in --host mode as of this writing. (Which ships with Python 3.9). 14.3 Was the last successful run that I've had with < Python 3.10.

**Comment by nathanmcgarvey** [comment]
I'm not sure where to voice concerns with language versioning decisions, but when a project stops supporting the stable versions of things shipped with several major Linux distributions, it makes it near impossible to use for many folks without major system impacts. (E.g. RHEL/CentOS/Rocky 8 is on Python 3.6 by default and 3.9 for the latest via streams, Debian 11 is on Python 3.9, openSUSE 15.4 is on Python 3.6 by default, and, humorously, Amazon Linux 2 has Python 3.7.) It's even more frustrating when those decisions aren't reflected in any requirements document. (Literally the first line item in Localstack's requirements section of the readme.) If there's an appropriate place to drop this comment (because it isn't technically relevant to this discussion), I'd like to know where so I can delete this comment.

**Comment by MarcelStranak** [comment]
Hi @nathanmcgarvey.

I would like to apologize for the misunderstanding. You have linked documentation details about our LocalStack-CLI tool. This tool works with different Python versions as mentioned in the documentation.
The main LocalStack service has different requirements. As you have mentioned, there are major differences between operating systems and distributions. Because of this, we recommend using our [LocalStack docker image](https://docs.localstack.cloud/get-started/#docker) instead of running LocalStack locally in a host mode. This will ensure there are no unnecessary application conflicts. We mention it in our [documentation](https://docs.localstack.cloud/developer-guide/setup/#host-mode) as well. I hope that this will provide further clarity on how LocalStack can be run.

**Comment by thrau** [comment]
Thanks for the feedback Nathan @nathanmcgarvey. I also want to add to marcel's post that that host mode is not something that's intended for localstack users. It is meant mainly for development purposes in environments that replicate the container environment. I hope that clarifies everything. We'll work on making the docs more explicit on the issue. Closing for now.

**Comment by nathanmcgarvey** [comment]
@thrau and @MarcelStranak, thanks for the thorough response. I appreciate it. Are there recommendations for using localstack in a testing environment that is already containerized? (E.g. where running automated tests dictate not having a localstack instance running at all times but torn up and down at dynamically as tests are run.) Aside from the complexity and overhead of docker-in-docker or using an entire pod-based K8S install, I'll assume that this isn't [easily] possible but would love to know if have other suggestions. Up until 0.14.4, I was starting localstack in host mode as a background task so it could all run in the same container as the integration tests with significantly lower complexity and retain isolation.

**Comment by nathanmcgarvey** [comment]
@thrau and @MarcelStranak, Regarding documentation: The part that probably the most misleading for me, at least, was the CLI help text, not the official documentation. (As the help text from `localstack start --help` lists `--docker` and `--host` as equally valid options for starting localstack)


:
