### ISSUE TITLE
[Errno 49] Can't assign requested address, 

### ISSUE THREAD

**Issue by wopperer** [localstack/localstack#6709]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Unit test `test_run_and_stop_server` of `tests/unit/utils/test_http2_server.py` fails on line 26, running the server on line 22 with IP address 127.0.0.2 on Mac OS, because there is no 127.0.0.2 on Mac OS. 

Changing the test as follow would make it pass, but the question is why do we need to run a server on both, 127.0.0.1 and  127.0.0.2?:

```
    def test_run_and_stop_server(self):
        port = get_free_tcp_port()
        host = "127.0.0.1"

        LOG.info("%.2f starting server on port %d", time.time(), port)
        thread = run_server(port=port, bind_addresses=[host], asynchronous=True)
        try:
            url = f"http://{host}:{port}"
            assert poll_condition(
                lambda: is_port_open(url, http_path="/"), timeout=15
            ), f"gave up waiting for port {port}"
            assert not is_port_open(f"http://127.0.0.3:{port}", http_path="/")
        finally:
            LOG.info("%.2f stopping server on port %d", time.time(), port)
            thread.stop()

        LOG.info("%.2f waiting on server to shut down", time.time())
        thread.join(timeout=15)
        assert not is_port_open(port), "port is still open after stop"
        LOG.info("%.2f port stopped %d", time.time(), port)
```

### Expected Behavior

Pass the test.

### How are you starting LocalStack?

Custom (please describe below)

### Steps To Reproduce

in `venv` run `python -m pytest --log-cli-level=INFO tests/unit/utils/test_http2_server.py`

### Environment

```markdown
- OS: macOS Monterey 12.4
- LocalStack: 58326f9cc379586925cf9c0d80a926c72274ff53
```

**Comment by alexrashed** [comment]
Hi @wopperer!
This is just a unit test which ensures that our gateway is capable of binding to multiple hosts at the same time.
You can configure your interface on MacOS to have multiple loopback interfaces as well ([see this StackOverflow](https://superuser.com/questions/458875/how-do-you-get-loopback-addresses-other-than-127-0-0-1-to-work-on-os-x)).
Since the unit test is very valuable (and necessary, we need to make sure that we can in fact bind to multiple hosts), I will close this issue for now.
Thanks!
