### ISSUE TITLE
Unsupported argument

### ISSUE THREAD

**Issue by Berg-it** [localstack/localstack#6734]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I try to use localstack with terraform, I followed your official documentation https://docs.localstack.cloud/integrations/terraform/ 
I used **tflocal** in order to deploy my infra on localstack , but always I got the error bellow:

```
│ Error: Unsupported argument
│ 
│   on localstack_providers_override.tf line 67, in provider "aws":
│   67: meteringmarketplace = "http://localhost:4566"
│ 
│ An argument named "meteringmarketplace" is not expected here.
```

### How are you starting LocalStack?

With the `localstack` script

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    tflocal init
    tflocal apply

### Environment

```markdown
- OS: Macos Monterey 12.3.1
- LocalStack: latest
```

**Comment by cam71101** [comment]
I am also getting the same error.

**Comment by gdarcy** [comment]
@Berg-it @cam71101 I had this issue when following the Terraform tutorials. It occurs when the 'aws' Terraform module has been pulled in with an older version (the constraint was >= 2.68.0 and it pulled in 3.23.0) rather than the most up to date one (4.27.0) and the module therefore doesn't support all the LocalStack endpoints.

I fixed this by adding 'version = "~> 4.16"' to the 'aws' block within the 'required_providers' block.

**Comment by fabio-blanco** [comment]
> I fixed this by adding 'version = "~> 4.16"' to the 'aws' block within the 'required_providers' block.

Thank you @gdarcy , your soluction worked for me. I was trying to follow the [Variables / configuration tutorial](https://learn.hashicorp.com/tutorials/terraform/variables?in=terraform/configuration-language) and the same errors occurred. I've implemented your fix to the terraform main script from their official git repository and it works!

```yaml
terraform {
  required_providers {
    aws = {
      source = "hashicorp/aws"
      version = "~> 4.16"
    }
  }
}
```

Unfortunately I was not able to conclude the tutorial because the script depends on creating a Load Balancer  and it is just available on localstack pro.

**Comment by whummer** [comment]
Thanks for reporting @Berg-it @cam71101 @gdarcy @fabio-blanco , this should be resolved in the meantime - can you please try upgrading to the latest version of `tflocal`:
```
pip install --upgrade 'terraform-local>=0.4'
```
Hope that helps - please let us know if the problem persists.. Thanks!

**Comment by whummer** [comment]
Closing as resolved - please do let us know if there are any other questions or issues.. Thanks
