### ISSUE TITLE
spark streaming not working with localstack

### ISSUE THREAD

**Issue by mahesh-ogale** [localstack/localstack#677]
I am trying to use spark streaming with localstack. I gave Kinesis endpoint as http://localhost:4568 but when I use KinesisUtils.createStream, it tries to create a dynamodb table internally and I think it keeps going to default dynamodb url (something like https://dynamodb.us-east-1.amazonaws.com) and not http://localhost:4570. I tried searching in localstack issues and also spent time googling but not able to find anything yet. Any help is much appreciated.

**Comment by yagrxu** [comment]
same problem here@mahesh-ogale 
I got this problem yesterday evening, no time to look in deep.
I guess the problem is on reading side, spark streaming kinesis jar implementation.

**Comment by whummer** [comment]
Thanks for reporting @mahesh-ogale . Can you please provide a minimal, self-contained example to help reproduce this issue?

**Comment by 01streams** [comment]
Same behavior...
My Spark app is trying to read from a Localstack managed Kinesis stream similar to [this article](https://spark.apache.org/docs/2.2.0/streaming-kinesis-integration.html). I provided the Kinesis endpoint URL as http://localhost:4568 while creating the stream to point to my local Kinesis stream. However I could not find a way to configure the DynamoDB endpoint URL to point to my local DynamoDB instance for Kinesis checkpointing. For this reason when my Spark app runs, checkpointing fails with the below error. How do I configure the Kinesis stream to point to my local DynamoDB instance and not to the default endpoint URL (dynamodb.us-east-2.amazonaws.com)?

```
ERROR LeaseManager: Failed to get table status for Dev
com.amazonaws.services.kinesis.leases.exceptions.DependencyException: com.amazonaws.SdkClientException: Unable to execute HTTP request: Connect to dynamodb.us-east-2.amazonaws.com:443 [dynamodb.us-east-2.amazonaws.com/***.***.***.***] failed: connect timed out
        at com.amazonaws.services.kinesis.leases.impl.LeaseManager.tableStatus(LeaseManager.java:163)
        at com.amazonaws.services.kinesis.leases.impl.LeaseManager.createLeaseTableIfNotExists(LeaseManager.java:108)
	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.KinesisClientLibLeaseCoordinator.initialize(KinesisClientLibLeaseCoordinator.java:307)
        at com.amazonaws.services.kinesis.clientlibrary.lib.worker.Worker.initialize(Worker.java:495)
        at com.amazonaws.services.kinesis.clientlibrary.lib.worker.Worker.run(Worker.java:436)
        at org.apache.spark.streaming.kinesis.KinesisReceiver$$anon$1.run(KinesisReceiver.scala:178)
		...
```

**Comment by mitchberg** [comment]
Seeing the same issue.  Is there a way to get Spark Streaming to work with localstack (i.e. have the localstack DynamoDB used)?

How to set the **aws_region** in the receiver create call that knows to use localstack for DynamoDB:
 KinesisUtils.createStream(jssc, kinesisAppName, streamName, "http://localhost:4568", **aws_region**,
		              InitialPositionInStream.LATEST, kinesisCheckpointInterval,
		              StorageLevel.MEMORY_AND_DISK_2())

**Comment by jaggernoth** [comment]
+1

**Comment by vishal98** [comment]
+1

**Comment by Manojd664** [comment]
Can someone help in this?

**Comment by 01streams** [comment]
I got this to work after a small hack. The idea is to redirect traffic for 'https://dynamodb.us-east-1.amazonaws.com' to the localstack container. Also we need to specify the port number (4568) to connect to the kinesis port for localstack to receive those requests. Since this is not possible simply from the hosts file, I had to setup a reverse proxy (nginx) container. Then I setup the ngnix conf to route all https traffic to localstack:4568. This also required to transform the https packets to http without which localstack Kinesis would fail with an SSL encryption error. I know this makes it vulnerable and I'm not aware of any alternatives but that solves my purpose coz I'm only testing on my local workstation which is inside a DMZ. At last I configured my hosts file to route all traffic to 'https://dynamodb.us-east-1.amazonaws.com' to the reverse proxy container. In summary these are the steps:
1. Set up an nginx  reverse proxy docker container.
2. Configure nginx to route all traffic to localstack:4568.
3. Set up SSL certificates to convert the HTTPS packets to HTTP - or else Kinesis throws a SSL encryption error.
4. Configure the hosts file to redirect traffic for 'https://dynamodb.us-east-1.amazonaws.com' to the new reverse proxy container.

**Comment by etspaceman** [comment]
https://github.com/apache/spark/blob/9fa4a1ed38713e2d18a3320d3fc56f9f6db07b06/external/kinesis-asl/src/main/scala/org/apache/spark/streaming/kinesis/KinesisReceiver.scala#L162

This is the root of the problem. It is not a `localstack` issue really, rather its an issue w/ the Kinesis integration not allowing users to configure dynamo (and cloudwatch) endpoints. Spark would need to provide support for these endpoints for localstack to work properly.

**Comment by whummer** [comment]
Thanks for digging into this @etspaceman! Any update on the pull request in the Spark repo? 

Closing this issue, as this is not really a bug in LocalStack. But please keep us posted here once the Spark PR gets merged. Thanks!!
