### ISSUE TITLE
HTTP header casing when localstack proxies requests

### ISSUE THREAD

**Issue by thrau** [localstack/localstack#6849]
In #6778 we found that AWS forwards HTTP headers to Lambdas from clients without modifying their casing. Since users are relying on this behavior, it effectively renders a web server that lowercases headers unusable as proxy for localstack. In general, I think there is a case to be made that web servers should not manipulate the casing of request headers, so that they can function as application-layer proxy to backends that make assumptions about header casing.

The issue of header casing for HTTP/1.1 in hypercorn was addressed with https://github.com/pgjones/hypercorn/issues/66, but later reverted with https://github.com/pgjones/hypercorn/issues/77. Apparently the relevant ASGI spec is being discussed here https://github.com/django/asgiref/issues/246 where I think we should make that case.

If this is a fundamental limitation of ASGI and we cannot get this into hypercorn, then we will be forced to either
- apologize to lambda users and tell them that they need to re-write their lambda code in a way that treats headers in a case-insensitive way
- fork hypercorn and maintain our own version
- use another webserver that does not manipulate HTTP headers, or at least allows access to the raw headers in some way

**Comment by thrau** [comment]
interested in getting your opinion @whummer (in particular the lambda user perspective), and @alexrashed

**Comment by alexrashed** [comment]
Currently, it feels like the discussion is going towards keeping the spec as it is right now (or just weakening the phrase a bit).
But, even if the spec stays the same we could maybe continue using hypercorn. The recent changes were addressing the way of accessing the headers as specified by ASGI. Maybe we can find a compromise to preserving the raw headers and to have a way of accessing them outside of ASGI. No-one prevents any framework from providing a additional features than specified in the spec. :)

If we can't stick with hypercorn (because we need the header casing being preserved and we can't find a way to access the raw headers), we could search for a suitable alternative (where the landscape is somewhat limited), or we could try to create a tightly-synced fork which simply adds this feature (which I would like to avoid if possible).

**Comment by thrau** [comment]
I've proposed a config option approach in hypercorn to allow for raw headers, which would let us continue using upstream hypercorn :crossed_fingers: https://github.com/pgjones/hypercorn/pull/117
