### ISSUE TITLE
bug: Unable to build localstack from source with make docker-build

### ISSUE THREAD

**Issue by sha-shrestha** [localstack/localstack#6881]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

```
[3/6] STEP 7/13: RUN (virtualenv .venv && source .venv/bin/activate && pip3 install --upgrade pip wheel setuptools)
created virtual environment CPython3.10.6.final.0-64 in 467ms
  creator CPython3Posix(dest=/opt/code/localstack/.venv, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/root/.local/share/virtualenv)
    added seed packages: pip==22.2.2, setuptools==65.3.0, wheel==0.37.1
  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
/bin/sh: 1: source: not found
Error: error building at STEP "RUN (virtualenv .venv && source .venv/bin/activate && pip3 install --upgrade pip wheel setuptools)": error while running runtime: exit status 127
make: *** [Makefile:101: docker-build] Error 127
```

### Expected Behavior

Docker build succeeds without errors.

### How are you starting LocalStack?

With a `docker run` command

### Steps To Reproduce

```
make docker-build
```

### Environment

```markdown
- OS: RHEL 8.6
- Docker: Podman 4.1.1
```

**Comment by whummer** [comment]
Hi @sha-shrestha , thanks for reporting. Can you please share some more details about your environment - which operating system and version of Docker are you using?

Regarding your fix in PR https://github.com/sha-shrestha/localstack/pull/1 - instead of using `bash -c "source .venv/bin/activate"` you could also try using the dot `.` operator: `. .venv/bin/activate`

**Comment by sha-shrestha** [comment]
> Hi @sha-shrestha , thanks for reporting. Can you please share some more details about your environment - which operating system and version of Docker are you using?
> 
> Regarding your fix in PR [sha-shrestha#1](https://github.com/sha-shrestha/localstack/pull/1) - instead of using `bash -c "source .venv/bin/activate"` you could also try using the dot `.` operator: `. .venv/bin/activate`. Hope that helps - please keep us posted..

Sure. 

- OS: RHEL 8.6
- Docker: Podman 4.1.1

**Comment by sha-shrestha** [comment]
@whummer, please review: https://github.com/localstack/localstack/pull/6899

**Comment by dfangl** [comment]
For the record: The base issue for this is that the OCI specification does not have the directive `SHELL`, so our `SHELL ["/bin/bash", "-c"]` in the dockerfile is ignored with podman, which leads to all instructions be executed with `sh` instead of `bash`.
See this issue: https://github.com/containers/podman/issues/8477 .
You can usually fix this by adding `--format docker` to the build command, in the case of our Makefile that should be `DOCKER_BUILD_FLAGS="--format docker" make docker-build` (untested, but should work).
This answer is unrelated to the PR though, I have no problems with changing `source` to `.`, but it might not be the last problem to encounter when skipping the `SHELL` directive.
