### ISSUE TITLE
Support for EC2 instances 

### ISSUE THREAD

**Issue by smand90** [localstack/localstack#691]
Does Local stock support EC2 instances ,I didn't see anything mentioned about EC2 api in the cloud api section??

**Comment by nottoseethesun** [comment]
There's this, which I maintain: https://www.npmjs.com/package/aws-mock  It would be cool to have a bridge or something similar between `localstack` and `aws-mock`, so that using both would be relatively seamless to the end user.

**Comment by ejrgilbert** [comment]
It seems that the way it was implemented is just for "mocking" EC2 instances instead of having ones that are functional. Is this a true statement? 

Since localstack is described as a "fully-functional local AWS cloud stack" I was expecting the EC2 instances to be able to function. Is there a way to get this as a feature? Or maybe I'm missing how to get this working?

I tried creating an EC2 instance using a terraform with localstack (as mentioned in a comment on the MR). Terraform exited correctly, but running an `aws ec2 describe-instances` with the localhost endpointed showed up empty. So it seems that there's enough functionality in localstack currently to "act" like it made ec2 instances, but they aren't actually created.

If you would like a use case for why this would be helpful, I am willing to provide a description of what I am trying to use this for.

**Comment by nottoseethesun** [comment]
Perhaps aws-mock would be useful here: https://github.com/treelogic-swe/aws-mock  (f.d.: treelogic-swe is my org).

**Comment by ejrgilbert** [comment]
Reading through the docs, it seems like aws-mock is a step above the moto mock, but still not quite what I'm looking for. To make it more transparent what I was trying to accomplish via localstack, here's a description of my use case:

I was hoping to take the `terraform` modules I've developed for my cloud infrastructure and run it locally as a fully-functional smaller "cloud" environment. This would enable me to consolidate several different use case solutions into one piece of "code" through using the same `terraforms` with different providers. If I could have a fully-functional local cloud via localstack, I would be able to use my `terraform` cloud infrastructure:
- in AWS for my test/prod deployments
- in localstack for spinning up my cloud infrastructure locally for CI/CD smoke tests
- in localstack for spinning up my cloud infrastructure locally for running my code in a development environment. This would keep me from having to update my env with new releases of my code. Rather, I would just use my versioned TF for managing all of that for me.

In this use case, I would need fully-functional EC2 instances since my cloud infrastructure requires it in order to interact with my `localstack` cloud similarly to how I would in a test/prod deployment scenario.
