### ISSUE TITLE
[ApiGateway] Implement ARNs for ApiKeys and make it possible to change ApiKey tags with TagResource by such ARNs.

### ISSUE THREAD

**Issue by ironman-255** [localstack/localstack#7073]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

Hi, I am not sure how to well describe which feature exactly need to be implemented here. But below, in the Anything else section you have an example of what I am trying to achieve.

My ultimate goal is to use the CLI command tag-resources (later on NodeJS) to update the value of a tag for a specific resource, but this command requires the resource ARN as parameter.  Using the get-resources command against tagged resource in local stack returns an empty array.

In AWS cloud environment everything works fine, for better local development we would like this functionality implemented.

Finally, my guess is I am asking for aws **resourcegroupstaggingapi** functionality available in LocalStack.

[https://awscli.amazonaws.com/v2/documentation/api/latest/reference/resourcegroupstaggingapi/index.html#cli-aws-resourcegroupstaggingapi](url)

Thank you.

### Anything else?

I am running local stack into Docker inside AWS Cloud9
Just tried with the most recent image, still do not get expected result.

**LocalStack**
"LOCALSTACK_BUILD_VERSION=[1.2.1.dev](http://1.2.1.dev/)"

Run LocalStack into Docker container
`docker run --rm -d -it -p 4566:4566 -p 4571:4571 --name lstack localstack/localstack`

Create an API-Key with tags
```
aws apigateway create-api-key \
--name apikey1 \
--description 'API Key' \
--enabled --tags 'tag1=10, tag2=20' \
--region ca-central-1 \
--endpoint-url http://localhost:4566
```

Get tagged resources info (ResourceARN)
```
aws resourcegroupstaggingapi get-resources \
--region ca-central-1 \
--endpoint-url http://localhost:4566
```
Result
```
{
   "ResourceTagMappingList": []
}
```

**AWS**

Create an API-Key with tags
```
aws apigateway create-api-key \
--name apikey1 \
--description 'API Key' \
--enabled --tags 'tag1=10, tag2=20' \
--profile profileName
```
Get tagged resources info (ResourceARN)
```
aws resourcegroupstaggingapi get-resources \
--tag-filters Key=tag1,Values=10 \
--profile profileName
```
Result
```
{
   "ResourceTagMappingList": [
       {
           "ResourceARN": "arn:aws:apigateway:ca-central-1::/apikeys/0x77gvy9h1",
           "Tags": [
               {
                   "Key": "tag1",
                   "Value": "10"
               },
               {
                   "Key": "tag2",
                   "Value": "20"
               }
           ]
       }
   ]
}
```

**Comment by taras-kobernyk-localstack** [comment]
Could you please check again if this command really works for you?
```
aws resourcegroupstaggingapi get-resources \
--region ca-central-1 \
--endpoint-url http://localhost:4566
```
This service doesn't seem to be implemented in LocalStack, you are supposed to get an error. If you drop the `--endpoint-url` parameter, the call goes to AWS instead, which would return you an empty list, as the previous
```
aws apigateway create-api-key \
--name apikey1 \
--description 'API Key' \
--enabled --tags 'tag1=10, tag2=20' \
--region ca-central-1 \
--endpoint-url http://localhost:4566
```
was executed against LocalStack.

As for the `tag-resources` call to ApiGateway, I think it is supposed to be for resources created with `create-resource` [call](https://docs.aws.amazon.com/cli/latest/reference/apigateway/create-resource.html) to ApiGateway itself, `create-api-key` is not supposed to return you any ARN. Might be wrong there, as I am not that familiar with ApiGateway itself. But this is how it looks to me.

**Comment by ironman-255** [comment]
**Could you please check again if this command really works for you?**

```
aws resourcegroupstaggingapi get-resources \
--region ca-central-1 \
--endpoint-url http://localhost:4566

```
Yes, It really works!!
Stopping the container running LocalStack will sure give me the error "Could not connect to the endpoint URL"
This let me to believe that command is really ran against LocalStack.

More Over, I tested it out in a brand you environment (windows), I installed docker and downloaded LocalStack image. Installed AWS CLI V2, and run aws configure with fake values. I ran the same command ang got the same result wherever there are resources (aws resources) created or not. 

**This service doesn't seem to be implemented in LocalStack, you are supposed to get an error. If you drop the --endpoint-url parameter, the call goes to AWS instead, which would return you an empty list, as the previous**

I don't know why I am not getting an error.
The terminal that I use to perform the command, is not even connected to AWS.
If I drop the --endpoint-url, the command is going to use the default profile which only has region set. This let me to believe that command is not run against AWS account.

```
[default]
region = ca-central-1
```

I will then get this error

_An error occurred (UnrecognizedClientException) when calling the GetResources operation: The security token included in the request is invalid._ 

**As for the tag-resources call to ApiGateway, I think it is supposed to be for resources created with create-resource call to ApiGateway itself, create-api-key is not supposed to return you any ARN. Might be wrong there, as I am not that familiar with ApiGateway. But this is how it looks to me.**

We need to clarify the word Resource
1- AWS::ApiGateway::Resource, resource creates a resource in an API
2- In AWS, a resource is an entity that you can work with, S3 Bucket, Lambda, API-Key, etc.

I am talking about the second "Resource" definition

Here is my understanding, I could also be wrong. Every entity (Resource) you create in AWS has a unique identifier, ARN.
The "resourcegroupstaggingapi" is not an API Gateway thing but looking at all the resources in AWS particularly those that has tags associated. There should be somewhere in AWS an ARN-tags association table, database...

Please let me know your thoughts, If I can do something else to help.

**Comment by taras-kobernyk-localstack** [comment]
If the `resourcegroupstaggingapi get-resources` call goes to LocalStack, it is supposed to be in LocalStack logs. Could you check them?

Alternatively, if you could install our wrapper for the AWS CLI with `pip install awscli-local` and then run `awslocal resourcegroupstaggingapi get-resources`, that might tell us something. `awslocal` is basically a substitute for `aws --endpoint-url http://localhost:4566`. Not sure what might be wrong there, but just in case. As if you use `awslocal` instead of `aws`, there is less possibility that the call goes to AWS instead.

Doesn't matter which approach you decide to use, it might be useful to drop the region from the command. Shouldn't change much, but as a rule of thumb - better to make things as simple as possible while debugging.

As for the ARN - it is possible to construct it yourself without ResourceGroupsTaggingApi, as the ARN is `arn:aws:apigateway:<REGION>::/apikeys/<API KEY ID>`. Won't help, though, as `tag-resource` in LocalStack doesn't seem to work the way it does in AWS, doesn't update the tags by such an ARN. It is possible that we missed the ARNs for ApiKeys in our implementation, as they are not mentioned on AWS ApiGateway pages for CreateApiKey or GetApiKey.

I am going to rename the ticket and add a comment to define its scope - to tag ApiKeys with this ARN. As for ResourceGroupsTaggingApi - I have just created https://github.com/localstack/localstack/issues/7092. To be honest, unless there is a demand for it, we might not have time to implement it in the nearest feature, as we are busy with other things.

As a workaround - I would advise to recreate keys with required tags if you need to change them. Or to wait for the current issue to get fixed and then use `tag-resource` with a tag constructed manually.

**Comment by taras-kobernyk-localstack** [comment]
The new scope:
1. Implement ARNs for ApiKey objects. Such ARNs are supposed to looks like `arn:aws:apigateway:<REGION>::/apikeys/<API KEY ID>`.
2. Make it possible to use [TagResource](https://docs.aws.amazon.com/apigateway/latest/api/API_TagResource.html) to change tags for ApiKeys. `TagResource` requires an ARN of a resource to tag, so we need those ARNs for ApiKeys implemented first.

**Comment by calvernaz** [comment]
Hi all, this is not an API Gateway issue per se. The service is not implemented in Localstack in his totally, so resources tagged using the ResourcegroupsTaggingApi are not working.

Given that we have an [issue open ](https://github.com/localstack/localstack/issues/7092)to tackle this services, the not optimal solution is to run the command to get all api-keys in the account. 

```
awslocal apigateway get-api-keys
```

That will contain the tags associated to the api-key;

```
{
    "items": [
        {
            "id": "a4wl2bk0zu",
            "name": "api-key",
            "description": "Managed by Terraform",
            "enabled": true,
            "createdDate": "2022-10-26T09:09:49+01:00",
            "lastUpdatedDate": "2022-10-26T09:09:49+01:00",
            "stageKeys": [],
            "tags": {
                "Environment": "Local",
                "Service": "LocalStack"
            }
        }
    ]
}
```

**Comment by taras-kobernyk-localstack** [comment]
@ironman-255 Sorry for the confusion. We wanted to have a separate ticket for the ApiGateway behaviour, but didn't communicate it well.

The new ticket is https://github.com/localstack/localstack/issues/7094

The current ticket is closed just for bookkeeping reasons. You can subscribe to both https://github.com/localstack/localstack/issues/7094 and https://github.com/localstack/localstack/issues/7092 to monitor the progress there. https://github.com/localstack/localstack/issues/7092, though, won't get much attention in the nearest feature. But I hope that at least https://github.com/localstack/localstack/issues/7094 would provide you with decent workarounds.

**Comment by ironman-255** [comment]
@taras-kobernyk-localstack  No worries, I will proceed with recommendations, look at the LocalStack logs, use awslocal.

@calvernaz  Thank you, I know well the get-api-keys command. I am working on a proof of concept of api-key rotation and in the process I would like to change the value of the "status" tag.

I think that the **apigateway** get-tags, tag-resource and
**resourcegroupstaggingapi** get-resources, tag-resources ...
are pretty much the same, they require (or look at) resource ARN and again by resource I mean AWS resource.

I am now thinking/wondering, if this could not have something to do with Identity and Access Management (IAM) because a place where we deal alot with ARN, is,  in IAM, for policy as example.

To be honest when I asked question in LocalStack community-support.
_I would like to know if LocalStack supports resource arn?
I am creating resources (Usage Plans and API-Keys) using AWS CLI and resources does not seem to have arn._
I was hoping to get as an answer to use Pro or enterprise version of LocalStack as it manages the IAM service (I think). I may try, as soon as I have a chance, Pro version just to see if there is different behavior.

Thanks for your implication.

**Comment by taras-kobernyk-localstack** [comment]
Created https://github.com/localstack/localstack/issues/7098 for Usage Plans.

I do not see how the Pro version would help here. Both Api Keys and Usage Plans are in ApiGateway service. And ApiGateway is available in the community version. Also ResourceGroupsTaggingApi is not implemented at all, so switching to Pro doesn't matter there either.

I think the issue here is that ApiGateway might be a somewhat old service. Its documentation is definitely lacking, as I see no mention there of ARNs for Api Keys. With Usage Plans it seems to be the same case. And since we use this documentation to create our implementations of AWS services, we probably had no idea about these ARNs even existing.

I do not think it is going to be too hard to implement these ARNs now. So my advice is to wait for these tickets to get resolved. Meanwhile, as a workaround, you can try deleting and re-creating Api Keys and Usage Plans if you have to change their tags. Or maybe change the design of your project to try to avoid changing the tags for the moment. Only saying it because I imagine that people somehow avoid changing these tags in general, as this whole topic is pretty obscure due to the AWS documentation not covering this stuff.

If you still want to try the Pro version -  you can probably create a trial key (free subscription) in our [web app](https://app.localstack.cloud/). Unless you have already used that chance. But again, the Pro version won't help with these particular issues.

**Comment by ironman-255** [comment]
Thank you for the clarification.

Yes, we will follow your advice, wait for the tickets to get resolved, presently we have the "status" of the api-key in its name, having it in the tag was an alternative we wanted to try, I still think it would be a nice feature.

Thanks again.

**Comment by taras-kobernyk-localstack** [comment]
Yeah, I imagine.

Well, at least I am glad to hear that you have an even better workaround than I thought of. Even if it is not a workaround per se, but your normal setup. :-)
