### ISSUE TITLE
feature request: allow the customization of the max lambda zip upload size

### ISSUE THREAD

**Issue by TheDumbfounds** [localstack/localstack#7074]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Feature description

Despite the fact that the AWS Lambda official docs say that the limit is 50MB, I'm deploying a larger function in production and it's working fine.

However, Localstack gives me an error when I try to create a lambda using the zip package I deployed to AWS, saying that the max limit was exceeded.

It would be nice to have a variable where I can control the max limit myself.

This would also be useful for people who want to make sure to not deploy
packages above a certain limit they set and want to limit themselves when testing using
localstack as well.

**Comment by joe4dev** [comment]
Hi @TheDumbfounds. Thanks for reporting a potential mismatch and suggesting an interesting feature.

## AWS <=> LocalStack Parity regarding AWS Lambda Limit

I tested different file sizes (using `dd if=/dev/urandom of=large_file bs=1M count=50`) and found that the current LocalStack behavior matches AWS (us-east-1, eu-central-1) using a threshold of 69905067 bytes for the maximum request size (defined in `localstack/services/awslambda/invocation/lambda_models.py:571`). The behavior is consistent with AWS in the current old Lambda provider as well as the new Lambda provider, which is available since `1.3.0` through the feature flag `PROVIDER_OVERRIDE_LAMBDA=asf`.

Assuming you create a lambda via zip like this:

```bash
aws --endpoint-url=http://localhost:4566 \
lambda create-function --function-name my-large-lambda \
--zip-file fileb://function.zip \
--handler main.handler --runtime python3.9 \
--role arn:aws:iam::000000000000:role/lambda-role
```

1. Is your error message related to a maximum request size (rather than other [Lambda quotas](https://docs.aws.amazon.com/lambda/latest/dg/gettingstarted-limits.html) such as the 50MB limit for zipped direct uploads)?

    > An error occurred (RequestEntityTooLargeException) when calling the CreateFunction operation: Request size (69916993) must be smaller than 69905067 bytes for the CreateFunction operation

3. Does your AWS account has any modified limits?

4. What is the exact size of your zip file in bytes (e.g., `ls -la large_file`)?

5. In which AWS region did your larger-than-50MB zipped function deploy successfully?

## Feature suggestion for a configurable deployment size limit

That's a nice suggestion and would be a good candidate for a [LocalStack extension](https://localstack.cloud/blog/2022-09-12-announcing-localstack-extensions/).

## Background

`LAMBDA_LIMITS_CREATE_FUNCTION_REQUEST_SIZE = 69905067` comes from an AWS error message initially mentioned in this [issue](https://github.com/localstack/localstack/issues/2990#issuecomment-699530272) and added it in this [PR](https://github.com/localstack/localstack/pull/2999).

**Comment by TheDumbfounds** [comment]
Hi again, sorry for the late reply, haven't checked this in a while.

1) Yes, it was.

2) No, we don't.

3) The exact size in bytes, coming from the command you pasted, is 71207695.

4) I'm deploying to eu-central-1 without any issues.

Thanks!

**Comment by joe4dev** [comment]
@TheDumbfounds Thanks for sharing.

That's interesting given that your zip of size `71207695` bytes is clearly larger than the AWS request size limit of `69905067` bytes (validated with multiple accounts and regions).

The exact error message changed in the meantime omitting the actual request size:
`An error occurred (RequestEntityTooLargeException) when calling the CreateFunction operation: Request must be smaller than 69905067 bytes for the CreateFunction operation`

How do you deploy the lambda function? Maybe through S3?

**Comment by joe4dev** [comment]
Hi @TheDumbfounds 

We [recently](https://github.com/localstack/localstack/commit/aeb3000b8e71ba79743d206d23ea1cdf63a84518#diff-8ee48b2bcad465473db1a1b202781ca2c7c23db7bd1670e79d45668fb2bd718fR700) made these limits configurable. You can try to increase the limit for `LAMBDA_LIMITS_CREATE_FUNCTION_REQUEST_SIZE` beyond the current default of `69905067` bytes (i.e., 69 MB).

We have not added these limits to the officially supported lambda [configuration](https://docs.localstack.cloud/references/configuration/#lambda) documentation to avoid configuration overload. However, we can envision more configurable limits in the future if that is a desired feature.

**Comment by xtaixe** [comment]
@joe4dev just came across this and `LAMBDA_LIMITS_CREATE_FUNCTION_REQUEST_SIZE` would be really useful to us, but if we provide features relying on it and later it goes away, it would prevent us from keeping LocalStack upgraded or require a big effort to provide a similar feature, so can we rely on it not going away and as a supported feature (in which case I think it should be documented)?

**Comment by joe4dev** [comment]
Thank you for asking @xtaixe 

> so can we rely on it not going away and as a supported feature

We will definitely continue to support this feature. We are mainly looking into feedback about what is the best way to define this API. Maybe we could expand our support for [AWS service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) and generalize it for other services. Hence, we need to find a scalable, standardized, and user-friendly solution for configuring such limits. Given that there are so many different quotas, we were a bit reluctant so far to document every possible configuration (e.g., 7 for Lambda [here](https://github.com/localstack/localstack/commit/aeb3000b8e71ba79743d206d23ea1cdf63a84518#diff-8ee48b2bcad465473db1a1b202781ca2c7c23db7bd1670e79d45668fb2bd718fR873-R879)).

---

Would `LAMBDA_LIMITS_CREATE_FUNCTION_REQUEST_SIZE` be sufficient for your use case or would it require modifying other limits?
Feel free to share more details, feedback, or ideas on how we can best support your scenario?

**Comment by xtaixe** [comment]
@joe4dev `LAMBDA_LIMITS_CREATE_FUNCTION_REQUEST_SIZE` (or any other way to configure LocalStack for the same) has been enough for the cases we have found, but we might need some of the other variables you point to in other cases. We just want to be able to allow our users to create/upload big Lambdas, ideally without having to implement some non trivial workaround like uploading them to S3 or similar.

I still think these features should be documented. Maybe these specific things should be documented on the page for each resource and not in a big "configuration" page?

**Comment by joe4dev** [comment]
@xtaixe Your requested limit configuration `LAMBDA_LIMITS_CREATE_FUNCTION_REQUEST_SIZE` is now documented under LocalStack Configuration: https://docs.localstack.cloud/references/configuration/#lambda

**Comment by xtaixe** [comment]
@joe4dev thanks a lot for the heads up. We will need to use and rely on `LAMBDA_LIMITS_CODE_SIZE_ZIPPED` so it would be great if it was documented.

**Comment by joe4dev** [comment]
@xtaixe You are welcome. I guessed that you would need that :). It's already done in https://github.com/localstack/docs/pull/933 🚀🚀🚀 

You can find the configuration documentation of `LAMBDA_LIMITS_CODE_SIZE_ZIPPED` here: https://docs.localstack.cloud/references/configuration/#lambda
