### ISSUE TITLE
Duplicates with same SequenceNumber in localstack->kinesis

### ISSUE THREAD

**Issue by karkok-nauto** [localstack/localstack#719]
Hi,

Strange behaviour on kinesis - message written to kinesis stream (PutRecord) is consumed more than once by consumer.
Consumer uses GetRecord in loop passing NextShardIterator as ShardIterator.
Duplicates are exactly the same with the same SequenceNumber.

Problem doesn't occur when real AWS env is used.

BR

**Comment by jkuehl2** [comment]
Might not related to localstack -are you using the KPL? You might have to parse the SubSequence numbers using the UserRecord Datastructure and set your cursor accordingly.

**Comment by karkok-nauto** [comment]
Hi @jkuehl2. 
No, we are not using Producer neither Consumer library (not available in golang).
We are operating on pure kinesis API.

Writing:
			_, err := k.PutRecord(&kinesis.PutRecordInput{
				StreamName:   aws.String(streamName),
				PartitionKey: aws.String(dev.ID),
				Data:         msg,
			})

Reading:
	in := &kinesis.GetRecordsInput{
		ShardIterator: (some value here),
	}
       iterator, err := s.Master.GetRecords(in)   // pure kinesis api

As per @AnvilStriker example - even though shard iterator changes (taken from NextShardIterator from kinesis response), sometimes duplicate occurs with exactly the same SequenceNumber.

Works properly with real AWS env.

**Comment by AnvilStriker** [comment]
Hi @jkuehl2,

It took quite a while, but I have come up with a standalone test case that evokes the duplicate-message behavior. https://gist.github.com/AnvilStriker/b54c4d67b6c2a3e10b027553d0496fae

The test can be run in one of two "modes". With `GOPATH` set appropriately to resolve the package imports:
- `go test -run TestLocalstackKinesis -args -mode=func` gets duplicate messages
- `go test -run TestLocalstackKinesis -args -mode=chan` does not get duplicate messages
 
The difference seems to be in the rapidity with which successive calls to `GetRecords` are made when the test is run with `-mode=func`. In that mode, record-counting is done by a simple function called from within the loop that processes the `GetRecordsOutput`.

In the other mode, each received record is passed through a Go channel to a separate body of code that does the counting, and at least a couple of context-switches are needed before the next record is processed or next call to `GetRecords` is made.

**Comment by AnvilStriker** [comment]
Further info: this bug seems to be environment-dependent:
- It occurs when running the localstack container (either of 0.8.5 or 0.8.6) under **Docker for Mac**, Version 18.03.1-ce-mac64 (24245)
- It does _not_ occur when running in the **Circle CI 2.0** build environment. We specify the image without explicit version number in that environment, i.e.. `image: localstack/localstack`, which at this point is presumably pulling the 0.8.6 version.

**Comment by whummer** [comment]
Thanks for the detailed report @AnvilStriker @karkok-nauto @jkuehl2 . 

This seems to be fixed in the latest version. I just ran a test with the [sample Go project](https://gist.github.com/AnvilStriker/b54c4d67b6c2a3e10b027553d0496fae), and both versions (`-mode=func` and `-mode=chan`) seem to be working (ran 5+ executions of the tests each).

Closing - please reopen if the problem persists. Thanks
