### ISSUE TITLE
feature request: QLDB query by "metadata.id" is not supported

### ISSUE THREAD

**Issue by amitassaraf** [localstack/localstack#7432]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

In the QLDB [documentation](https://docs.aws.amazon.com/qldb/latest/developerguide/working.metadata.html), you are allowed to query the QLDB database by the documentId that is returned, by doing -
`SELECT * FROM Book as b WHERE b.metadata.id = ?`

But that is not supported by the current QLDB implementation. The workaround is querying the __doc_id__:
`"SELECT * FROM Book WHERE __doc_id__ = ?"`

But ofcourse that is not production compatible.

Can you support queries by metadata.id?

### 🧑‍💻 Implementation

Quick hack is to replace .metadata.id in queries to __doc_id__

**Comment by simonrw** [comment]
Hi @amitassaraf , thanks for reporting this issue to us.

From the documentation you linked, the `metadata.id` field is on the committed table (`_ql_committed_<table name>`) rather than the `Book` table. We have a fix in the works that's validated against AWS, and the tests perform a queries against the committed table. We validate that this matches the behaviour of AWS with our [snapshot testing](https://localstack.cloud/blog/2022-08-04-parity-explained/) and so we're not going to support the query you suggest in your example.  Is that what you expected?

**Comment by whummer** [comment]
Hi again @amitassaraf , we have now pushed a couple of enhancements for QLDB `_ql_committed_<table name>` queries. Can you please pull the `latest` Docker image and give it a try? 

You should now be able to run queries like the following:
```
 SELECT * FROM _ql_committed_Book as b WHERE b.metadata.id = ?
```

Please keep us posted on how it goes.. Thanks!

**Comment by whummer** [comment]
Closing as resolved - please do let us know if the problem persists or if there are any questions.. 👍
