### ISSUE TITLE
bug: aws-sdk on host environment cannot connect to localstack endpoint but aws cli can

### ISSUE THREAD

**Issue by ianwremmel** [localstack/localstack#7487]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

`@aws-sdk/*` cannot connect to localstack using node 18 on the host system. lambdas deployed to localstack using the node 18 runtime seem to work without issue.

```
Error: connect ECONNREFUSED ::1:4566
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1300:16) {
  errno: -61,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '::1',
  port: 4566,
  '$metadata': { attempts: 1, totalRetryDelay: 0 }
}
```

### Expected Behavior

`@aws-sdk/*` can connect to localstack

### How are you starting LocalStack?

With the `localstack` script

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

```sh
localstack start
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

This works with `nvm use 16` but fails with `nvm use 18` both locally and in CI.

```ts
import {
  CloudFormationClient,
  DescribeStacksCommand,
} from '@aws-sdk/client-cloudformation';

(async () => {
  try {
    process.env.AWS_ACCESS_KEY_ID = 'test';
    process.env.AWS_SECRET_ACCESS_KEY = 'test';
    process.env.AWS_REGION = 'us-east-1';
    const client = new CloudFormationClient({
      endpoint: 'http://localhost:4566',
    });

    await client.send(new DescribeStacksCommand({}));
  } catch (err) {
    console.error(err);
    process.exit(1);
  }
})();
```

This works:

```
awslocal cloudformation describe-stacks 
```

### Environment

```markdown
- OS: macOS, GitHub Actions
- LocalStack: 1.3.1
```

### Anything else?

[This PR](https://github.com/ianwremmel/data/pull/95) changes nothing except switching the test environment from the default node 16 to node18 and, as you can see, the [this file](https://github.com/ianwremmel/data/blob/a7a09ba3b4813f7ba15674529daed661820d33e4/jest.d/global-setup/stack-env.ts) throws. I tried swapping out the client in there to instead shell out to awslocal. That worked, but all the code under test failed since the dynamo and eventbridge clients couldn't connect.

**Comment by dominikschubert** [comment]
Hi @ianwremmel !

This is unfortunately caused by a change in NodeJS as you already correctly determined. Newer versions now try to resolve and use IPv6 first which usually fails if you didn't bind the LocalStack port to an IPv6 address. `localstack start` by default only binds `127.0.0.1:4566`.

There are a few ways you can address this:

1. use the IPv4 address explicitly, e.g. `      endpoint: 'http://127.0.0.1:4566',`
2. use a hostname that only resolves to an IPv4 address, e.g. `      endpoint: 'http://localhost.localstack.cloud:4566',`
3. bind localstack to `::1:4566` by adding `"::1:4566:4566"` to you docker-compose port bindings


The third option right now won't work with `localstack start` though

**Comment by ianwremmel** [comment]
Awesome, thanks! switching to 127.0.0.1 fixed it. Kinda weird that node doesn't seem to do the right thing here. I would expect it to try IPv6 first, but fallback to IPv4 instead of just barfing.
