### ISSUE TITLE
bug: SSM client returns incorrect exception type on invalid parameter name

### ISSUE THREAD

**Issue by darrengrove-RL** [localstack/localstack#7712]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Incorrect exception type for `awslocal ssm get-parameter` on an invalid ssm parameter name.

`awslocal ssm get-parameter --name="{test}-test"`

Returns:

`An error occurred (ParameterNotFound) when calling the GetParameter operation: Parameter {test}-test not found.`

### Expected Behavior

`aws ssm get-parameter --name "{test}-test"`

Returns

`An error occurred (ValidationException) when calling the GetParameter operation: Parameter name: can't be prefixed with "ssm" (case-insensitive). If formed as a path, it can consist of sub-paths divided by slash symbol; each sub-path can be formed as a mix of letters, numbers and the following 3 symbols .-_`

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    awslocal ssm get-parameter --name="{test}-test"

### Environment

```markdown
- OS: MacOS Ventura 13.1
- LocalStack:1.4.0
```

**Comment by GuddyTech** [comment]
Yes! Using the ARN works instead of using the names and this will throw an error 
`aws ssm get-parameter --name "ec2-image-builder/devops/rhel8-stig-golden-image"`

`An error occurred (ValidationException) when calling the GetParameter operation: Parameter name: can't be prefixed with "ssm" (case-insensitive). If formed as a path, it can consist of sub-paths divided by slash symbol; each sub-path can be formed as a mix of letters, numbers and the following 3 symbols .-_`

Instead use: 
`$ aws ssm get-parameter --name arn:aws:service:us-east-1:0000000000:parameter/myparam`

NOTE: If the parameter has a forward slash already do not add it
`$ aws ssm get-parameter --name arn:aws:service:us-east-1:0000000000:parameter${myparam}`
