### ISSUE TITLE
bug: queue is ambiguous, got region us-east-1 from request

### ISSUE THREAD

**Issue by ArchieY393** [localstack/localstack#7869]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

```
version: '3.7'

services:
    localstack:
        image: localstack/localstack:latest
        environment:
            - DEBUG=1
            - SERVICES=s3,sqs
            - AWS_DEFAULT_REGION=us-east-1
            - AWS_REGION=us-east-1
            - AWS_ACCESS_KEY_ID=****
            - AWS_SECRET_ACCESS_KEY=****
            - LAMBDA_EXECUTOR=docker
            - HOSTNAME_EXTERNAL=localhost
            - SQS_ENDPOINT_STRATEGY=path
        ports:
            - "4566:4566"
        volumes:
            - ../docker/localstack/init:/etc/localstack/init/ready.d/
    example-service:
        build:
            context: ..
            dockerfile: Dockerfile
        entrypoint:
            - /example-service/wait-for-it.sh
            - http://localstack:4566/upload/test.txt
            - http://localstack:4566/_localstack/health
            #- http://localstack:4566/000000000000/queue-name
            - http://localstack:4566/queue/us-east-1/000000000000/queue-name
            # - http://us-east-1.queue.localhost.localstack.cloud:4566/000000000000/queue-name
            - --
        env_file: ../env/example


The localstack comes up fine, but the example-service fails to come up as it can't see the queue http://localstack:4566/queue/us-east-1/000000000000/queue-name and it dumps the following logs:
localstack_1        | 2023-03-15T11:35:35.847  INFO --- [   asgi_gw_0] localstack.request.http    : GET /queue/us-east-1/000000000000/cvl_production_feed_importer_feed_ready => 404
localstack_1        | 2023-03-15T11:35:36.889  INFO --- [   asgi_gw_6] localstack.request.http    : GET /queue/us-east-1/000000000000/cvl_production_feed_importer_feed_ready => 404
 
where as, when I try to use the queue http://localstack:4566/000000000000/queue-name  it dumps the following logs:
localstack_1        | 2023-03-14T21:54:10.489 DEBUG --- [   asgi_gw_0] l.services.sqs.query_api   : Region of queue URL http://localstack:4566/000000000000/queue-name is ambiguous, got region us-east-1 from request

I've tried different queue URLs by setting the `SQS_ENDPOINT_STRATEGY` to `path/domain` but no luck. I do have S3 configured and it comes up fine. 
```

### Expected Behavior

SQS to come up fine. If I use the localstack image 0.12.13, it comes up straight away. This issue is blocking me to use any of the localstack latest features.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

 Use the docker-compose above and you should be able to see the issue.

### Environment

```markdown
- OS:Ubuntu 20.04
- LocalStack:latest
```

**Comment by thrau** [comment]
Hello @ArchieY393. We know that connecting external containers to SQS is a bit of a pain right now, and should be a bit easier once https://github.com/localstack/localstack/pull/7774 is merged.

However, from your issue description it's not clear to me what the actual problem is and what behavior you are expecting.
If you are only using us-east-1, then `SQS_ENDPOINT_STRATEGY=off` should work just fine.
```
where as, when I try to use the queue http://localstack:4566/000000000000/queue-name  it dumps the following logs:
localstack_1        | 2023-03-14T21:54:10.489 DEBUG --- [   asgi_gw_0] l.services.sqs.query_api   : Region of queue URL http://localstack:4566/000000000000/queue-name is ambiguous, got region us-east-1 from request
```
is fine in this case - since you are using us-east-1 anyway.

I don't know what it is that your `example-service` is doing exactly, but calling `curl http://localstack:4566/000000000000/queue-name` may not behave in the way you expect anymore if you are comparing it to LocalStack 0.12. We completely re-wrote the SQS Query API since then, and calling an empty GET request on the queue URL will now correctly return `<UnknownOperationException/>`. You can find more info in our docs in [SQS Query API](https://docs.localstack.cloud/user-guide/aws/sqs/#sqs-query-api).
