### ISSUE TITLE
How to do Aws kinesis firehose data transformation with Aws lambda in localstack ??

### ISSUE THREAD

**Issue by akashgoel1197** [localstack/localstack#788]
My firehose delivery stream is connected to a s3 bucket. I need to perform data transformation on the data in delivery stream using lambda function and send the updated data to the s3 bucket. How do i do this in localstack ??

**Comment by whummer** [comment]
Hi @akashgoel1197 , this appears to be more of a general question regarding the usage of the AWS SDK, rather than a LocalStack specific question. Generally speaking, what you need to do is point your AWS client library to the local endpoints. Have you been able to do that? Can you be a bit more specific which problem you're facing exactly?

Closing this issue for housekeeping reasons (because we have lots of open issues), but please feel free to follow up here with a more specific question. Please provide more details about your environment, as well as a code snippet with an example to reproduce your problem. Thanks
