### ISSUE TITLE
bug: S3 Presigned URL doesn't map bucket name correctly

### ISSUE THREAD

**Issue by bennbollay** [localstack/localstack#7971]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Using the Javascript SDK, creating a presigned url for a PUT places the file under the specified `Bucket`, but when running under localstack, the bucket parameter is ignored and localstack returns back 404 with the first part of the `Key` path used as the `Bucket`.

### Expected Behavior

It's expected that AWS and Localstack will behave identically for this operation, and will use the `Bucket` specified.

### How are you starting LocalStack?

With the `localstack` script

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    localstack start

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

First, create the `data-storage-bucket` in localstack:

```
AWS_DEFAULT_REGION=us-east-1 \
AWS_ACCESS_KEY_ID=A \
AWS_SECRET_ACCESS_KEY=B \
aws s3 --endpoint-url="http://localhost.localstack.cloud:4566" mb s3://data-storage-bucket
```

Then create the test file:
```javascript
const { S3Client, PutObjectCommand } = require('@aws-sdk/client-s3');
const { getSignedUrl } = require('@aws-sdk/s3-request-presigner');

const go = async () => {
  const s3Client = new S3Client({ endpoint: process.env.S3_ENDPOINT, region: 'us-west-1' });
  const command = new PutObjectCommand({
    Bucket: "data-storage-bucket",
    Key: "acc-aaaaaaaa/uniqueKey",
  });
  const url = await getSignedUrl(s3Client, command);

  try {
    const result = await superagent
      .put(url)
      .send('12345');
  } catch (err) { console.log(err.response.statusCode, err.response.body.toString('utf8')); }
}
go();
```

Executed using this command:
```
AWS_ACCESS_KEY_ID=A \
AWS_SECRET_ACCESS_KEY=B \
S3_ENDPOINT=http://localhost.localstack.cloud:4566 \
node ./test_upload.js
```

This generates the following output:
```
404
<?xml version='1.0' encoding='utf-8'?>
<Error>
  <Code>NoSuchBucket</Code><Message>The specified bucket does not exist</Message>. 
  <RequestId>CV...ZV</RequestId>
  <BucketName>acc-aaaaaaaa</BucketName>
</Error>
```

If the acc-aaaaaaaa bucket is created:

### Environment

```markdown
- OS:
- LocalStack:
```

**Comment by bentsku** [comment]
Hi @bennbollay and thanks for your report. Your issue seems to be the same as in #7295, resolved with this comment https://github.com/localstack/localstack/issues/7295#issuecomment-1343058900. 

It boils to the [virtual host addressing](https://docs.aws.amazon.com/AmazonS3/latest/userguide/VirtualHosting.html), and LocalStack not being able to pick the bucket name from the subdomain while not using the S3 specific endpoint (see the documentation here: https://docs.localstack.cloud/user-guide/aws/s3/#getting-started). 

Could you try to either setup your client to use the S3 specific endpoint `s3.localhost.localstack.cloud:4566`, or use `forcePathStyle=true` in your config? It should solve your issue.

Thanks again!
