### ISSUE TITLE
bug: S3 Presigned URL doesn't map bucket name correctly

### ISSUE THREAD

**Issue by bennbollay** [localstack/localstack#7972]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Using the Javascript SDK, creating a presigned url for a PUT places the file under the specified `Bucket`, but when running under localstack, the bucket parameter is ignored and localstack returns back 404 with the first part of the `Key` path used as the `Bucket`.

### Expected Behavior

It's expected that AWS and Localstack will behave identically for this operation, and will use the `Bucket` specified.

### How are you starting LocalStack?

With the `localstack` script

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    localstack start

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

First, create the `data-storage-bucket` in localstack:

```
AWS_DEFAULT_REGION=us-east-1 \
AWS_ACCESS_KEY_ID=A \
AWS_SECRET_ACCESS_KEY=B \
aws s3 --endpoint-url="http://localhost.localstack.cloud:4566" mb s3://data-storage-bucket
```

Then create the test file:
```javascript
const { S3Client, PutObjectCommand } = require('@aws-sdk/client-s3');
const { getSignedUrl } = require('@aws-sdk/s3-request-presigner');

const go = async () => {
  const s3Client = new S3Client({ endpoint: process.env.S3_ENDPOINT, region: 'us-west-1' });
  const command = new PutObjectCommand({
    Bucket: "data-storage-bucket",
    Key: "acc-aaaaaaaa/uniqueKey",
  });
  const url = await getSignedUrl(s3Client, command);

  try {
    const result = await superagent
      .put(url)
      .send('12345');
  } catch (err) { console.log(err.response.statusCode, err.response.body.toString('utf8')); }
}
go();
```

Executed using this command:
```
AWS_ACCESS_KEY_ID=A \
AWS_SECRET_ACCESS_KEY=B \
S3_ENDPOINT=http://localhost.localstack.cloud:4566 \
node ./test_upload.js
```

This generates the following output:
```
404
<?xml version='1.0' encoding='utf-8'?>
<Error>
  <Code>NoSuchBucket</Code><Message>The specified bucket does not exist</Message>. 
  <RequestId>CV...ZV</RequestId>
  <BucketName>acc-aaaaaaaa</BucketName>
</Error>
```

If the `acc-aaaaaaaa` bucket is created:
```
AWS_DEFAULT_REGION=us-east-1 \
AWS_ACCESS_KEY_ID=A \
AWS_SECRET_ACCESS_KEY=B \
aws s3 --endpoint-url="http://localhost.localstack.cloud:4566" mb s3://acc-aaaaaaaa
```

then the example code succeeds.

### Environment

```markdown
- OS:
  MacOS 13.2.1
- LocalStack:
  1.4.0
- Javascript:
    "@aws-sdk/client-s3": "^3.299.0",
    "@aws-sdk/s3-request-presigner": "^3.299.0",
```

**Comment by bentsku** [comment]
Hi @bennbollay and thanks for your report. Your issue seems to be the same as in #7295, resolved with this comment https://github.com/localstack/localstack/issues/7295#issuecomment-1343058900. 

It boils to the [virtual host addressing](https://docs.aws.amazon.com/AmazonS3/latest/userguide/VirtualHosting.html), and LocalStack not being able to pick the bucket name from the subdomain while not using the S3 specific endpoint (see the documentation here: https://docs.localstack.cloud/user-guide/aws/s3/#getting-started). 

Could you try to either setup your client to use the S3 specific endpoint `s3.localhost.localstack.cloud:4566`, or use `forcePathStyle=true` in your config? It should solve your issue.

Thanks again!

**Comment by bennbollay** [comment]
Confirmed; using `s3.localhost.localstack.cloud:4566` as the `endpoint` produces the expected behavior.

**Comment by jacekgajek** [comment]
This is still open. I use localstack in tests. I cannot magically tell the application to suddenly use a different endpoint for this specific AWS feature.

**Comment by bentsku** [comment]
@jacekgajek We have this entry in the documentation explaining the reasons: https://docs.localstack.cloud/user-guide/aws/s3/#path-style-and-virtual-hosted-style-requests

LocalStack cannot automatically guess your bucket name if your endpoint does not follow the right format. 

How are you currently setting your tests to target LocalStack instead of the real AWS?

AWS also has a documentation page about endpoints: https://docs.aws.amazon.com/sdkref/latest/guide/feature-ss-endpoints.html

Some SDK allows the injection of the endpoint URL via environment variables (as`AWS_ENDPOINT_URL`), maybe yours does too? See this table: https://docs.aws.amazon.com/sdkref/latest/guide/feature-ss-endpoints.html#ss-endpoints-sdk-compat

Also, AWS even allows specific service endpoints to be set now (https://docs.aws.amazon.com/sdkref/latest/guide/feature-ss-endpoints.html#ss-endpoints-envar), in the format of `AWS_ENDPOINT_URL_S3=s3.localhost.localstack.cloud:4566`.

Maybe this can help you. Easiest for S3 currently is to tell the client to the Path Style.

**Comment by jacekgajek** [comment]
If LocalStack claims to be fully functional AWS, why do I need to provide a configuration specific for LocalStack in my application? I don't want to modify it just for tests.

**Comment by bentsku** [comment]
Let's continue the discussion on the other issue you've opened, I'm sure we can find a way to unblock you.
