### ISSUE TITLE
bug: ListAllMyBucketsResult when using "GetBucketPolicy" Golang SDK v2

### ISSUE THREAD

**Issue by notdodo** [localstack/localstack#8475]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When using [Golang AWS SDK v2](https://github.com/aws/aws-sdk-go-v2) to list a bucket policy with the function `GetBucketPolicy` the output return is an XML:

```xml
<ListAllMyBucketsResult><Owner><DisplayName>webfile</DisplayName><ID>75aa57f09aa0c8caeab4f8c24e99d10f8e7faeebf76c078efc7c6caea54ba06a</ID></Owner><Buckets><Bucket><Name>awslambda-eu-west-1-tasks</Name><CreationDate>2023-06-10T13:31:07Z</CreationDate></Bucket><Bucket><Name>nuvola-s3-test</Name><CreationDate>2023-06-10T13:47:18Z</CreationDate></Bucket><Bucket><Name>lambda-output</Name><CreationDate>2023-06-10T13:47:18Z</CreationDate></Bucket><Bucket><Name>awslambda-us-east-1-tasks</Name><CreationDate>2023-06-10T13:48:02Z</CreationDate></Bucket></Buckets></ListAllMyBucketsResult>
```
Using `awslocal s3api get-bucket-policy --bucket lambda-output` correctly return the bucket policy in JSON.

### Expected Behavior

identical to the one for `awslocal` command: the output of the go SDK call in json format with the bucket policy

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

```
version: "3.8"

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME}"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566" # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559" # external services port range
    environment:
      - DEBUG=${DEBUG-}
      - PERSISTENCE=${PERSISTENCE-}
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
```

### Environment

```markdown
- OS: Ubuntu 22.04
- LocalStack:latest
```

**Comment by bentsku** [comment]
Hello @notdodo and thanks for your report!
Is it the only operation going wrong for you? From a first glance, it could because you're accessing LocalStack using the virtual host addressing (putting the bucket in the domain) by default, and LocalStack not picking up the bucket name and returning the base `/`.
Basically, `http://<bucket>.localhost:4566/?policy`, where LocalStack will ignore your bucket.

When using the default virtual host addressing, the S3 endpoint for your client should be `http://s3.localhost.localstack.cloud:4566`, which translated to virtual host by your client would give `http://<bucket>.s3.localhost.localstack.cloud:4566` which LocalStack will properly pick up.
Otherwise, you can try to set `UsePathStyle ` to `true` to make your request look like `http://localhost:4566/<bucket>?policy` which would be properly picked up as well. 

You can read more about virtual host and path style in our documentation. 
S3: https://docs.localstack.cloud/user-guide/aws/s3/
Configuring the Go SDK: https://docs.localstack.cloud/user-guide/integrations/sdks/go/

If that's not the issue, could you please set `DEBUG=1` and `LS_LOG=trace` when starting up LocalStack, and share the logs when the issue happens? Thanks!

**Comment by notdodo** [comment]
Hi @bentsku! :)

> Is it the only operation going wrong for you?

Actually yes. From the Golang POV I perform read/list/describe with no problems (no only on S3).
Forgot to mention that I'm setting `S3_HOSTNAME=localhost`; dunno if this could help investigate the issue.

Thank you so much for the tips about the hostname and `UsePathStyle` and the link to the documentation to configure Go (didn't know about it).
I'll look into what you suggest and I'll update you

**Comment by notdodo** [comment]
Setting UsePathStyle solved the problem (ref: https://aws.amazon.com/blogs/developer/aws-sdk-for-go-version-2-general-availability/).
Thank you!
