### ISSUE TITLE
Error connecting to localstack container on jenkins

### ISSUE THREAD

**Issue by shyam-coda** [localstack/localstack#8516]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm trying to set up an s3 bucket on jenkins with localstack. I can see the container is created, and in a healthy state from the `docker ps` output. But the curl fails with `curl: (7) Failed to connect to 0.0.0.0 port 4566: Connection refused`
```
    stages {
        stage('Start Localstack') {
            steps {
                script {
                      sh 'docker run --network new-network --name localstack -d -p 4566:4566 -e SERVICES=s3 localstack/localstack'
                      sh 'sleep 20'
                      sh 'docker ps'
                      sh "curl http://0.0.0.0:4566/_localstack/health"
                      // other stuff
                        }
                   }
             }
      }
```
here's the `docker ps` output:
```
CONTAINER ID   IMAGE                             COMMAND                  CREATED          STATUS                    PORTS 
852bf19dc492   localstack/localstack             "docker-entrypoint.sh"   33 seconds ago   Up 32 seconds (healthy)   4510-4559/tcp, 5678/tcp, 0.0.0.0:4566->4566/tcp
```

### Expected Behavior

I'd expect the curl to work, the same works on my mac.

### How are you starting LocalStack?

With a `docker run` command

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run --network new-network --name localstack -d -p 4566:4566 -e SERVICES=s3 localstack/localstack

### Environment

```markdown
- OS:
- LocalStack:latest
```

**Comment by nathanmcgarvey-modopayments** [comment]
Is the `0.0.0.0` IP address supposed to be `127.0.0.1` or `localhost` or similar? I'm not sure how `0.0.0.0` works on a local mac, but that seems unusual to resolve to your local computer.

**Comment by shyam-coda** [comment]
@nathanmcgarvey-modopayments all three of those work on my mac
<img width="1714" alt="Screenshot 2023-06-18 at 9 15 35 PM" src="https://github.com/localstack/localstack/assets/136784697/58b76060-6417-447a-a5b7-82e5beb91724">

**Comment by nathanmcgarvey-modopayments** [comment]
Sorry if I may have miscommunicated: I'm saying that `0.0.0.0` is highly operating-system dependent IP address in terms of using it as a destination IP. The `0.0.0.0` in your `docker ps` output is the *listening* address, implying "all" addresses local to that computer. It is unusual to use that as a destination IP address as it isn't a valid IP address, per se, but your operating system *may* automatically translate it to something else, internally.

Example: Using your logic above, if I start a localstack container: `docker run --name localstack -d -p 4566:4566 -e SERVICES=s3 localstack/localstack`

Then capture traffic using tcpdump going to that port (4566): `tcpdump -nni any port 4566`

You'll see that the actual IP address that OS X is using auto-translated the `0.0.0.0` in your curl command to `127.0.0.1`.: `IP 127.0.0.1.55058 > 127.0.0.1.4566`. That's because IP traffic *cannot* use `0.0.0.0` as a valid IP address except in very very special circumstances (I'm looking at you, DHCP, etc.)


My suggestion it to try the following:

In your pipeline, change the `0.0.0.0` to `127.0.0.1`, and additionally do the same for your local Mac OS X testing, as that is the "more correct" thing to do, IMHO (debatable, of course). As you noted, this also works for your local setup, as expected.

If, in Jenkins, that still does not work, there is a very very very good chance that whatever the docker network `--network new-network` is, is not configured properly to allow traffic and is just being an isolated network that isn't actually bound to the underlying host networking at all.

**Comment by shyam-coda** [comment]
Thank you for clarifying. I should have added I had already tried with `127.0.0.1` on jenkins. The result was the same. Now, I also removed the `--network` so the relevant steps are just this
```
sh 'docker run --name localstack -d -p 4566:4566 -e SERVICES=s3 localstack/localstack'
sh 'sleep 20'
sh 'docker ps'
sh "curl http://127.0.0.1:4566/_localstack/health"
```
But I'm afraid the result is still the same.

**Comment by shyam-coda** [comment]
This turned out to be an issue where jenkins agents were running inside docker container. So some issues related to running docker-in-docker. It went away by directing the pipeline to run on an ec2 instance instead of docker. I can close this
