### ISSUE TITLE
SQS FIFO queue MessageGroupId is not available

### ISSUE THREAD

**Issue by osleg** [localstack/localstack#861]
Creating SQS FIFO queue should provide `MessageGroupId` for messages received as described here https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/FIFO-queues.html#FIFO-key-terms

Currently there is no `MessageGroupId` provided in response object

**Comment by mberlanda** [comment]
This should be fixed by this pr upgrading the dependency for SQS and including FIFO support:

https://github.com/localstack/localstack/pull/880

May you try to pull the image `localstack:latest` or to build the image out of the master branch to confirm that it working?

Ps. Note that if you have already a `localstack:latest` you may delete it and the base image as well `localstack/java-maven-node-python`

**Comment by whummer** [comment]
Thanks for reporting, and for confirming it works - closing.
