### ISSUE TITLE
Sending messages with accented characters thru SQS/SNS is breaking

### ISSUE THREAD

**Issue by guilhermestorck** [localstack/localstack#868]
On my localstack I have configure a SNS topic and a SQS queue that listens to it. When I send a message with special characters, the message that the queue's listener receives does not have the right encoding.

On my example, `é` is turning into `\u00c3\u00a9` instead of `\u00E9`.
This issue does not happen when I send the same message to the AWS' SQS/SNS service.

Is there any configuration I need to set to make this work?

**Comment by mberlanda** [comment]
It looks like an encoding issue.
Do you have this problem for all *special characters*?

Would you have this issue only when you send the message via SNS->SQS or you are facing the issue also on SNS only and SQS only?

**Comment by guilhermestorck** [comment]
Yes I'm having for a lot of special characters (I didn't really test them all 😀) and the issue only happens when SNS sends a message to SQS.

**Comment by Nighthawk14** [comment]
Hi @guilhermestorck, I'm having the same issue here with an EN dash. Did you manage to resolve it on your end?

**Comment by leandroandrade87** [comment]
Any news?

**Comment by whummer** [comment]
Thanks for reporting @guilhermestorck @mberlanda @Nighthawk14 @leandroandrade87 @mosesyu . This should have been fixed in the meantime - a test with unicode characters has been added here: https://github.com/localstack/localstack/blob/master/tests/integration/test_sns.py#L29-L41 Please report here if the problem persists. Thanks
