### ISSUE TITLE
Java : RuntimeException When Using Spring Test Runner Mac [macOS High Sierra]

### ISSUE THREAD

**Issue by mongoDynamo** [localstack/localstack#887]
Similar to this issue : https://github.com/localstack/localstack/issues/593

I get this Runtime error when trying to use the @RunWith(LocalstackTestRunner.class) : https://pastebin.com/RQBTXq4b

From the top most link, (https://github.com/localstack/localstack/issues/593), I tried the debugging steps mentioned by @whummer and I seem to able to execute the python version checks
![image](https://user-images.githubusercontent.com/38298138/43802901-33494e1e-9a65-11e8-88c9-3973703d5173.png)

But not seeing the desired output when using make install, and make infra from the localstack root
![image](https://user-images.githubusercontent.com/38298138/43802966-69ebf840-9a65-11e8-8ca2-18553fbfea9c.png)

Not sure how to remedy this, intention is to run this in a different environment than my own PC. So it would be helpful if localstack automatically setup everything for me. Because I don't want to make any manual changes outside of my project. 

Also, this is the dependency I added in my POM : 
`<dependency>

            <groupId>cloud.localstack</groupId>

            <artifactId>localstack-utils</artifactId>

            <version>0.1.14</version>

        </dependency>`

**Comment by jpierz** [comment]
Hi,

I ran into this exact issue also on macOS High Sierra. The issue was that `virtualenv` was installed, but not in my `PATH`. Running the command from [this](https://stackoverflow.com/questions/31133050/virtualenv-command-not-found/41429177#41429177) answer moved it to a location in my `PATH` and localstack started running just fine.

I don't know if this fits your bill of not making changes outside your project, but if you can give this a shot, it might help.

Best of luck.

**Comment by whummer** [comment]
Thanks for the update - the Java libs have been moved to a [separate repe](https://github.com/localstack/localstack-java-utils) and in the meantime the startup has been significantly reworked. Please create a follow-up issue in the LocalStack Java libs repo if the problem persists. Thanks!
