### ISSUE TITLE
bug: Permission denied when accessing binary in lambda layer

### ISSUE THREAD

**Issue by samuelhgf** [localstack/localstack#8897]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm getting this error when using lambda layer
[Errno 13] Permission denied: '/opt/bin/wkhtmltopdf'

### Expected Behavior

Not have Permission Denied

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    ```
    container_name: localstack
    image: localstack/localstack-pro
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    environment: &aws-env
      AWS_ACCESS_KEY_ID: 12345
      AWS_SECRET_ACCESS_KEY: xyz
      AWS_REGION: us-east-1
      LOCALSTACK_API_KEY: API_KEY
      DEBUG: 1
      PERSISTENCE: 1
      DOCKER_HOST: unix:///var/run/docker.sock
      SERVICES: lambda:4510
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      -  atena_network
     ```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    awslocal s3 mb s3://mybucket

### Environment

```markdown
- OS: MacOS
- LocalStack: latest
```

### Anything else?

My Sam Template:

```
Transform: AWS::Serverless-2016-10-31

Parameters:
  AppEnv:
    Type: String
    Default: localhost
    AllowedValues:
      - localhost
      - development
      - staging
      - production

Resources:
  Url2PdfS3Function:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      FunctionName: 'url-to-pdf-s3'
      Handler: main.handler
      Runtime: python3.9
      Timeout: 900
      Tracing: Active
      MemorySize: 256
      ReservedConcurrentExecutions: 5
      Environment:
        Variables:
          APP_ENV: !Ref AppEnv
      Tags:
        Name: Utl2PdfS3
      Policies:
        - AWSLambdaBasicExecutionRole
      Layers:
        - !Ref libs

  libs:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: wkhtmltopdf-lib
      Description: wkhtmltopdf bin.
      ContentUri: wkhtmltopdf/.
```

And it work properly with localtsack-pro:1.4

**Comment by joe4dev** [comment]
Thank you for reaching out @samuelhgf 

Can you confirm that the same binary also executes on real AWS Lambda?

By chance, do you have an example at hand to reproduce the issue?

**Comment by samuelhgf** [comment]
@joe4dev Thanks for the reply!

Yes. We have the binary working in production at AWS.

I created a clone repo of my work. It's at https://github.com/samuelhgf/localstack-lambda-layer-issue with the instructions.

Please reach me out any time for anything.

**Comment by joe4dev** [comment]
Hi @samuelhgf 

The reproduction repo is very helpful. Thank you!

## Reproduction Attempt

I tested the project on my M1 Macbook and it worked fine both on AWS and on localstack-pro (latest image as of today). The binaries have exactly the same permissions as on AWS, checked with `ls -la /opt/bin`:

```
-rwxr-xr-x 1 root root 39460864 Jan  1  1980 wkhtmltoimage
-rwxr-xr-x 1 root root 39530496 Jan  1  1980 wkhtmltopdf
```

I was able to download the PDF from the container `docker cp 657623c7aeb5a23d299c69f629dbd118ee6b5e15593f4027bd34e046414f65e4:/tmp/12345.pdf .`
<img width="763" alt="Screenshot 2023-08-14 at 12 21 21" src="https://github.com/localstack/localstack/assets/8161292/271d5dc2-d8fd-4f42-bca5-759c2f0f36e0">

PS: the 4th step should be `deploy` rather than `build` and the 60s sleep at the end of the Python Lambda seems unnecessary.

## Troubleshooting

1. Could you try pulling the latest image `docker pull localstack/localstack-pro`
2. Could you try without persistence by commenting out `PERSISTENCE: 1` Removing the deprecated configuration `SERVICES: lambda:4510` also could hurt.
3. Does the permission error occur in the Lambda logs? `[Errno 13] Permission denied: '/opt/bin/wkhtmltopdf'`
4. What are the permissions for the binaries? `os.system('ls -la /opt/bin')`

**Comment by samuelhgf** [comment]
Hi @joe4dev 

1. I did and removed all old containers
2. Did as requested
3. Yes. Still print out permission denied
4. It's different from yours. But are the same in the repo I created for this bug. Probably this is the solution. The binaries are not executable. But I don't know why it works in `localtsack-pro:1.4` and not in the latest.
```
-rwxr--r-- 1 root root 39460864 Aug 14 11:22 wkhtmltoimage
-rwxr--r-- 1 root root 39530496 Aug 14 11:22 wkhtmltopdf
```

PS: the time.sleep(60s) was for the `1.4` test since the lambda container stoped right after the execution. And I needed running to check the file creation in `tmp` folder.

**Comment by joe4dev** [comment]
Thank you for the extra details @samuelhgf 

I can reproduce the issue now. I can also confirm that AWS Lambda makes binaries under the `bin` directory executable during deployment.

## Workaround

As a temporary workaround while we are looking to fix this parity issue, please make the binaries executable before packaging using `chmod 755 wkhtmltopdf`.

## Initial difference in my setup

Upon checkout via `gh repo clone samuelhgf/localstack-lambda-layer-issue`, I got the following permissions and therefore didn't experience the same issue:

```
-rwxr-xr-x@ 1 joe  staff  39460864 Aug 16 14:47 wkhtmltoimage
-rwxr-xr-x@ 1 joe  staff  39530496 Aug 16 14:47 wkhtmltopdf
```

**Comment by joe4dev** [comment]
Hi @samuelhgf 

We improved permission parity with AWS for the directories `/opt` (0755) and `/tmp` (0700). Can you please pull the latest LocalStack image and try again?

We are looking forward to hearing your feedback 👂 

-----

**Limitation with hot-reloading**: This parity support might not work after hot-reloading unless disabling user parity using `LAMBDA_DOCKER_FLAGS= -e LOCALSTACK_USER=""` because dropping root privileges can lead to permission issues when trying to fix the permissions.
