### ISSUE TITLE
Does localstack work with Kinesis Client Library v2?

### ISSUE THREAD

**Issue by justinborromeo-toast** [localstack/localstack#893]
Amazon recently updated the architecture of their client library (see https://docs.aws.amazon.com/streams/latest/dev/introduction-to-enhanced-consumers.html).  Now, Kinesis pushes data to consumers instead of consumers polling Kinesis for data.  Will localstack still work with KCL version 2.x?

**Comment by thala321** [comment]
Same issue here. I can't connect to localstack using KCL version 2.x. Are you planning to support KCL version 2.x in the near future ??

**Comment by sahas-** [comment]
+1

**Comment by Matt343** [comment]
Localstack uses Kinesalite to do the heavy lifting for managing Kinesis streams. There is an open issue on that project to add support for the new Kinesis features, that would probably need to be resolved before anything can be done here https://github.com/mhart/kinesalite/issues/75

**Comment by etspaceman** [comment]
It seems that AWS has discontinued their `disableCertChecking` parameter in the v2 API:

https://github.com/aws/aws-sdk-java-v2/blob/master/docs/LaunchChangelog.md#11-client-creation-defaults

So, in order to get v2 to work, you either have to disable localstack's SSL (USE_SSL=false) and connect that way (which isn't acceptable for the KPL, which requires SSL), Or...

- Generate self-signed certificates as outlined https://github.com/localstack/localstack#a-note-about-using-custom-ssl-certificates-for-use_ssl1
- Create a keystore/truststore that trust the certs
- Use the certs in localstack by attaching volumes to the docker contianer w/ the certs
- Update the JRE to use the new keystore/truststore (e.g. -Djavax.net.ssl.keyStore)
- Set CBOR_ENABLED -> False
- Use the HTTP1.1 protocol in the KinesisAsyncClient creation, like so:

``` .httpClientBuilder(
        NettyNioAsyncHttpClient
          .builder()
          .protocol(Protocol.HTTP1_1)
      )```

**Comment by etspaceman** [comment]
I have also created https://github.com/aws/aws-sdk-java-v2/issues/1230 to try to get this flag supported again.

**Comment by etspaceman** [comment]
The support team member has provided a much better option! There is a configuration option `TRUST_ALL_CERTIFICATES` that can be provided to the `NettyNioAsyncHttpClient`. This example works for me without any new certificates / trust stores.

```
    KinesisAsyncClient
      .builder()
      .endpointOverride(
        URI.create(s"https://${config.host.value}:${config.kinesisPort.value}")
      )
      .region(Region.of(config.region.getName))
      .httpClient(nettyClient)
      .credentialsProvider(AwsCredsV2.LocalCreds)
      .build()
  )
```

**Comment by mjones3** [comment]
> The support team member has provided a much better option! There is a configuration option `TRUST_ALL_CERTIFICATES` that can be provided to the `NettyNioAsyncHttpClient`. This example works for me without any new certificates / trust stores.

Is there a way to use a V2 Kinesis client without having to work asynchronously?  I too am getting a 502 Bad Gateway error when I try to use a synchronous Kinesis client:

`        AmazonKinesis kinesis = AmazonKinesisClientBuilder.standard()`
`.withEndpointConfiguration(localstack.getEndpointConfiguration(LocalStackContainer.Service.KINESIS))`
`.withCredentials(localstack.getDefaultCredentialsProvider())`
`.build()`

Is there any way to use just AmazonKinesisClientBuilder that will work with localstack?  I'm trying to avoid complicating my codebase by rewriting all the Kinesis calls in my application to be async just so I can get integration tests working.  Has anyone had any luck with this?

**Comment by madhead** [comment]
@mjones3, try:

```java
val client = ApacheHttpClient
            .builder()
            .buildWithDefaults(
                AttributeMap
                    .builder()
                    .put(SdkHttpConfigurationOption.TRUST_ALL_CERTIFICATES, Boolean.TRUE)
                    .build()
            );

clientBuilder.httpClient(client);
```

**Comment by khitsik** [comment]
> The support team member has provided a much better option! There is a configuration option `TRUST_ALL_CERTIFICATES` that can be provided to the `NettyNioAsyncHttpClient`. This example works for me without any new certificates / trust stores.
> 
> For context, I have a configuration object and a mocked credentials class that I use for local tests.
> 
> ```
>  val nettyClient: SdkAsyncHttpClient =
>     NettyNioAsyncHttpClient
>       .builder()
>       .protocol(Protocol.HTTP1_1)
>       .buildWithDefaults(
>         AttributeMap
>           .builder()
>           .put(
>             SdkHttpConfigurationOption.TRUST_ALL_CERTIFICATES,
>             java.lang.Boolean.TRUE
>           )
>           .build()
>       )
> 
>     KinesisAsyncClient
>       .builder()
>       .endpointOverride(
>         URI.create(s"https://${config.host.value}:${config.kinesisPort.value}")
>       )
>       .region(Region.of(config.region.getName))
>       .httpClient(nettyClient)
>       .credentialsProvider(AwsCredsV2.LocalCreds)
>       .build()
> ```
Maybe you know how to set it up in node js consumer/provider? Getting the same issue

**Comment by Goose1985** [comment]
Hi! i am having the same issue. Any updates? thanks!

**Comment by slnowak** [comment]
@Goose1985 
As I understand, there's still no support for fan-out functionality.
The `SubscribeToShard` API call which should open http2 connection is not implemented. The only way to integrate with KCL2 that I found was to change the `RetrievalSpecificConfig` in KCL to `PollingConfig`. Did you find a better way?

**Comment by ravitejakasthala** [comment]
Hi All 
Thanks for all the above suggestions, My connection to Localstack Kinesis and AWS SDK 2 with Java is still failing.


I am using Java 11 and below dependencies
<dependency>
   <artifactId>netty-nio-client</artifactId>
   <groupId>software.amazon.awssdk</groupId>
   <version>2.13.31</version>
</dependency>
<dependency>
   <groupId>software.amazon.kinesis</groupId>
   <artifactId>amazon-kinesis-client</artifactId>
   <version>2.2.11</version>
 </dependency> 

**Java code scenario 1**:
    SdkAsyncHttpClient sdkAsyncHttpClient =
        NettyNioAsyncHttpClient.builder()
            .protocol(Protocol.HTTP1_1)
            .buildWithDefaults(
                AttributeMap.builder()
                    .put(SdkHttpConfigurationOption.TRUST_ALL_CERTIFICATES, java.lang.Boolean.TRUE)
                    .build());
KinesisAsyncClient kinesisClient =
        KinesisClientUtil.createKinesisAsyncClient(
            KinesisAsyncClient.builder()
                .region(region)
                .endpointOverride(myUri)
                .httpClient(sdkAsyncHttpClient));

I am seeing an exception:
java.lang.IllegalArgumentException: The asyncHttpClient and the asyncHttpClientBuilder can't both be configured.
data-producer-java_1  | 	at software.amazon.awssdk.utils.Validate.isTrue(Validate.java:76) ~[utils-2.13.31.jar!/:na]
data-producer-java_1  | 	at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder.resolveAsyncHttpClient(SdkDefaultClientBuilder.java:276) ~[sdk-core-2.13.25.jar!/:na]
data-producer-java_1  | 	at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder.finalizeAsyncConfiguration(SdkDefaultClientBuilder.java:231) ~[sdk-core-2.13.25.jar!/:na]
data-producer-java_1  | 	at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder.asyncClientConfiguration(SdkDefaultClientBuilder.jav

**Java code scenario 2:**
NettyNioAsyncHttpClient.Builder httpClientBuilder = NettyNioAsyncHttpClient.builder();
    httpClientBuilder.buildWithDefaults(
        AttributeMap.builder()
            .put(SdkHttpConfigurationOption.TRUST_ALL_CERTIFICATES, Boolean.TRUE)
            .build());
    httpClientBuilder.buildWithDefaults(
        AttributeMap.builder().put(SdkHttpConfigurationOption.PROTOCOL, Protocol.HTTP1_1).build());
    httpClientBuilder.protocol(Protocol.HTTP1_1);

    KinesisAsyncClient kinesisClient =
        KinesisClientUtil.createKinesisAsyncClient(
            KinesisAsyncClient.builder()
                .region(region)
                .endpointOverride(myUri)
                .httpClientBuilder(httpClientBuilder));
Error:
An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
data-producer-java_1  | 
data-producer-java_1  | java.io.IOException: The channel was closed before the protocol could be determined.
data-producer-java_1  | 	at software.amazon.awssdk.http.nio.netty.internal.http2.Http2SettingsFrameHandler.channelUnregistered(Http2SettingsFrameHandler.java:58) ~[netty-nio-client-2.13.31.jar!/:na]

Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:4568
 | Caused by: java.net.ConnectException: Connection refused

Please suggest if i am doing anything wrong

**Comment by Goose1985** [comment]
@slnowak not yet! I have not any find other workaround, i will try to spend a little more time on this.

**Comment by prateeksinghal10** [comment]
@Goose1985 did we figure out any work arounds?

**Comment by Goose1985** [comment]
Sorry i cant continue with this tasks, others priorities. But I did an update and doesnt work magically.

**Comment by whummer** [comment]
@Goose1985 @prateeksinghal10 @ravitejakasthala @slnowak @khitsik @madhead @mjones3 @etspaceman @hoangtrucit  Thanks all - support for CBOR encoding has been added in #3078. Can you please give it another try with the `latest` version of the Docker image? We have also added a couple of simple integration tests using Kinesis Client Library v2 to the LocalStack Java libs repo: https://github.com/localstack/localstack-java-utils . Please let us know if the problem persists. Thanks!
