### ISSUE TITLE
bug: Implementation ip command does not work on CentOS

### ISSUE THREAD

**Issue by miguelsimoes** [localstack/localstack#9326]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

`2023-10-10T10:41:03.748  INFO --- [uest_thread)] localstack.dns.server      : Unable to get DNS result: Command '['ip', '--json', 'route', 'show', 'default']' returned non-zero exit status 255.
Option "-json" is unknown, try "ip -help".`

The `-json` option is not supported for default  `ip` command (seems to only work for Debian based systems) not allowing to start localstack on host mode on CentOS due to the previous error.

### Expected Behavior

Continue to work as it was before https://github.com/localstack/localstack/commit/1782c0091eb6ac836d6fa204f57f4364fe1a9cd9 which implements the culprit:
`cmd = ["ip", "--json"] + list(args)`

### How are you starting LocalStack?

With the `localstack` script

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

localstack start --host

### Environment

```markdown
- OS: CentOS
- LocalStack: localstack[runtime] (installed with `pip install --upgrade localstack[runtime]`
```

**Comment by simonrw** [comment]
Hi @miguelsimoes , thanks for raising this issue with us.

I am interested in your use case of using LocalStack in host mode. Can you tell me more about why you are running in this mode, rather than using our more conventional mode of using docker?

I can confirm that `ip` on CentOS does not support the `--json` parameter.
