### ISSUE TITLE
enhancement request: Support Java 21 preview

### ISSUE THREAD

**Issue by eddumelendez** [localstack/localstack#9330]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Enhancement description

Currently, Java 21 preview is provided according to [this comment](https://github.com/aws/aws-lambda-base-images/issues/113#issuecomment-1742819624). It would be nice to support it via LocalStack and start testing it.

### 🧑‍💻 Implementation

I think java21-preview should be added [here](https://github.com/localstack/localstack/blob/4ddec69f77f26e40c0a69a1e374ead27f16f1b1a/localstack/aws/api/lambda_/__init__.py#L200-L232)

So, the code below should work.

```java
var createFunctionRequest = CreateFunctionRequest.builder()
			.functionName(fnName)
			.runtime("java21-preview")
			.role("arn:aws:iam::123456789012:role/irrelevant")
			.packageType(PackageType.ZIP)
			.code(FunctionCode.builder()
				.zipFile(SdkBytes.fromByteArray(FileUtils.readFileToByteArray(new File(jar))))
				.build())
			.timeout(10)
			.handler("org.springframework.cloud.function.adapter.aws.FunctionInvoker::handleRequest")
			.environment(Environment.builder().variables(envVars).build())
			.build();
```

### Anything else?

It can be tested with this [java project](https://github.com/eddumelendez/testcontainers-localstack/blob/main/lambda/src/test/java/com/example/springcloudfunctionaws/SpringCloudFunctionAwsApplicationTests.java)

**Comment by eddumelendez** [comment]
https://aws.amazon.com/about-aws/whats-new/2023/11/aws-lambda-support-java-21/

**Comment by joe4dev** [comment]
The `latest` LocalStack image now (since 2023-11-23) supports the new Lambda runtime `java21` 🚀 

Thank you for your initiative in https://github.com/localstack/localstack/pull/9685 🙏 

Facilitated by our recent improvements https://github.com/localstack/localstack/pull/9697, we are looking forward to supporting new runtimes faster 🚀🚀🚀. We should definitely adopt your great idea of supporting new runtimes before they are GA as a preview💡 

@eddumelendez Can you confirm that the new Lambda runtime `java21` now works as expected for your project?

**Comment by eddumelendez** [comment]
I just tested with latest image and it works! 🎉 

Looking forward for the release 😃

**Comment by joe4dev** [comment]
We are excited that everything works 🎉 and appreciate your feedback 💯

`3.0.1` has just been released https://github.com/localstack/localstack/releases/tag/v3.0.1 📦 🥳
