### ISSUE TITLE
bug: ListObjectsV2 Returns EncodingType When Not Specified

### ISSUE THREAD

**Issue by tustvold** [localstack/localstack#9427]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

```
$ docker run -d -p 4566:4566 -e PROVIDER_OVERRIDE_S3=v3 localstack/localstack:2.3

$ aws --no-sign-request --endpoint-url=http://localhost:4566 s3 mb s3://tustvold

$ curl -X PUT --data-binary 'test' -H "Content-Type: text/plain" 'http://localhost:4566/tustvold/a%252Fb.txt'

$ curl 'http://localhost:4566/tustvold'
<?xml version='1.0' encoding='utf-8'?>
<ListBucketResult><IsTruncated>false</IsTruncated><Marker /><Name>tustvold</Name><Prefix /><MaxKeys>1000</MaxKeys><EncodingType>url</EncodingType><Contents><Key>a%252Fb.txt</Key><ETag>"d41d8cd98f00b204e9800998ecf8427e"</ETag><Owner><DisplayName>webfile</DisplayName><ID>75aa57f09aa0c8caeab4f8c24e99d10f8e7faeebf76c078efc7c6caea54ba06a</ID></Owner><Size>0</Size><LastModified>2023-10-21T18:45:37.298607Z</LastModified><StorageClass>STANDARD</StorageClass></Contents></ListBucketResult>
```

Using `PROVIDER_OVERRIDE_S3=v3` does not appear to change this behaviour, nor does it differ between ListObjects and ListObjectsV2

### Expected Behavior

```
$ docker run -d -p 4566:4566 localstack/localstack:2.0

$ aws --no-sign-request --endpoint-url=http://localhost:4566 s3 mb s3://tustvold

$ curl -X PUT --data-binary 'test' -H "Content-Type: text/plain" 'http://localhost:4566/tustvold/a%252Fb.txt'

$ curl http://localhost:4566/tustvold/a%252Fb.txt
test

$ aws --no-sign-request --endpoint-url=http://localhost:4566 s3 ls s3://tustvold
2023-10-21 19:43:04          4 a%2Fb.txt

$ curl 'http://localhost:4566/tustvold'
<?xml version='1.0' encoding='utf-8'?>
<ListBucketResult><IsTruncated>false</IsTruncated><Marker /><Contents><Key>a%2Fb.txt</Key><LastModified>2023-10-21T18:43:04Z</LastModified><ETag>"098f6bcd4621d373cade4e832627b4f6"</ETag><Size>4</Size><StorageClass>STANDARD</StorageClass><Owner><DisplayName>webfile</DisplayName><ID>75aa57f09aa0c8caeab4f8c24e99d10f8e7faeebf76c078efc7c6caea54ba06a</ID></Owner></Contents><Name>tustvold</Name><MaxKeys>1000</MaxKeys></ListBucketResult>
```

Unless encoding-type is specified in the request, it shouldn't return encoded paths for compatibility with the behaviour of S3 itself. 

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

See above

### Environment

```markdown
Linux
```

**Comment by bentsku** [comment]
Hello! Just to confirm, this behaviour is only with the `v3` provider, is that right? Just tried it, we got this bug in because out testing client is using `boto`, and this adds it by default, so we didn't have a negative test case where the encoding type was not specified. I'll have a PR up soon to fix this! Thanks for reporting!

**Comment by tustvold** [comment]
I thought it was both, but trying this now it would appear as you say to be specific to the v3 provider. Must have gotten confused when testing different scenarios.

**Comment by bentsku** [comment]
Yes, this is linked to this issue: https://github.com/boto/boto3/issues/816 which made me do a wrong assumption. I'll fix that now! Thanks for using the `v3` provider, I'll be happy to have any feedback!

**Comment by tustvold** [comment]
> I'll be happy to have any feedback

I'm very excited for a backend that even more faithfully behaves like S3, so a big fan of this :+1:. I maintain the Rust object_store crate, and its test suite seems to be very good at finding bugs/limitations of storage emulators :sweat_smile:, although primarily in the other non-localstack emulators.

I didn't get very far into running the test suite before running into this and #9428, but one thing I did notice was ListObjectsV2 startAfter appeared to be including the startAfter key, when it should be exclusive, could be a red-herring though, my testing methodology was a little haphazard :grin:

**Comment by bentsku** [comment]
Ah, that's really awesome! And great pointer for `startAfter`, I'll double check my tests as well against AWS to be sure we're right on that, it could very well be a bug on our side.

About #9428, I'll get right on that as soon as this issue is finished, I believe I've fixed it now, but yes, URL encoding changed lately with upgrades to our internal HTTP framework, Werkzeug. We've already have a lot of fixes around that, but it's highly possible there are still hidden issues like the one you've reported. Thanks again, and open as many issues your test suite can find, I'll be extremely grateful for that! 🙏

**Comment by bentsku** [comment]
And oh wow I didn't know this create was developed for InfluxDB IOx! Big fan of the project. Is there any way I would be able to run the test suite myself maybe to alleviate the need to open issues if there are still plenty? I'm not sure it is the same as in the `arrow-rs` repo.

**Comment by tustvold** [comment]
> Is there any way I would be able to run the test suite myself

If you speak Github CI - https://github.com/apache/arrow-rs/blob/master/.github/workflows/object_store.yml

Otherwise something like the following should work (not tested)

```
export AWS_ACCESS_KEY_ID=local
export AWS_SECRET_ACCESS_KEY=development
export AWS_BUCKET=<bucket_name>
export AWS_REGION=us-east-1
export AWS_ALLOW_HTTP=true
export AWS_ENDPOINT=http://localhost:4566
export TEST_INTEGRATION=1
export RUST_BACKTRACE=1

git clone https://github.com/apache/arrow-rs.git
cd arrow-rs/object_store
cargo test --features aws
```

**Comment by bentsku** [comment]
This is awesome, thank you so much. I'll give that a try!

Quick question, would you be interested in a smaller localstack image containing only S3? As I see you're also using it in CI.

**Comment by Bigcountry409** [comment]
Hey guys I know this ain't the topic I leaving this every where and I got a package here at the house and it's  brand new iPhone 14 pro max phones it says admirer and says from Qin SuSu does anybody know of such a woman or ever heard of here I am assuming it is a woman and the box had lips on it like she kissed it I am writing this on every platform so is there some way anybody could help me please thanks in advance

**Comment by tustvold** [comment]
> Quick question, would a smaller localstack image containing only S3 be of any interest to you

Potentially, although there is ongoing work to support conditional writes using DynamoDB, and so we would need that also. To be honest image size isn't a massive concern for us in CI, Rust compilation is so slow 😅

**Comment by bentsku** [comment]
Thanks for the answer! We're working on it for these kind of use cases as part of a prototype, but the DynamoDB use-case sounds interesting. Good to know for the image size 😄

I opened the PR and fixed the behaviour for the `v3` provider. The other issue (#9428) is only in the `v2` provider, so both of them have one kind of issue 😅 I'll try to validate the `startAfter` issue as well.

**Comment by bentsku** [comment]
The PR for the `EncodingType` has just been merged, but there are still ongoing PRs to fix all of your issues:
- #9430
- #9431 (to validate that it works with `v3`, ongoing work for `v2` has been merged upstream but will need a release of our own fork)

I've also ran the `object_store` test suite manually (thank you so much for that!) and I could find the last failing test, something related with preconditions headers, PR is here:
- #9448 

Once these are merged, I think I could maybe ping you in this issue so that you could maybe give it a try and see if that works for you? I'll also try to work on #6328 as I saw the comment in the code regarding the space encoding. I'll give it a try and see if I can fix that as well.

**Comment by bentsku** [comment]
Hello @tustvold, all issues should now be solved, you can give it a try again with the `v3` provider. Thank you again for the report and the test suite!

**Comment by tustvold** [comment]
Looks good locally, filed a draft PR https://github.com/apache/arrow-rs/pull/5028 to track, will look to update when the next tagged release is cut
