### ISSUE TITLE
bug: localstack pre-loaded with `kinesis-local` does not start the kinesis process

### ISSUE THREAD

**Issue by code4dc** [localstack/localstack#9525]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I create an image with the following Dockerfile:
```
FROM dtr.mapsandbox.net/ckm/localstack:2.3.0
RUN npm install --prefix /var/lib/localstack/lib/kinesis-local/0.4.2 kinesis-local@0.4.2
```
and start it using the localstack helm chart. I'm pre-loading `kinesis-local` since my corp policy won't let me do the `npm install` in upper environments. The install appears to work even though the logs show that `localstack` attempts to install `kinesis-local` again. 

```
localstack.packages.api    : Starting installation of kinesis-local...
localstack.utils.run       : Executing command: ['npm', 'install', '--prefix', '/var/lib/localstack/lib/kinesis-local/0.4.2', 'kinesis-local@0.4.2']
```
But the kinesis-local is never run and the kinesis service does not start. 

### Expected Behavior

I expect that `localstack` will see that `kinesis-local` is pre-installed and will run it w/o attempting to install it again. 

### How are you starting LocalStack?

Custom (please describe below)

### Steps To Reproduce

Official localstack helm chart: https://github.com/localstack/helm-charts

### Environment

```markdown
- OS:
- LocalStack:2.3.0
```

**Comment by bentsku** [comment]
Hello @code4dc and thanks for your report!

To install packages that LocalStack needs, we have a CLI util available inside the Docker image: `lpm`
You can read more about it here: https://docs.localstack.cloud/contributing/concepts/#lpm-commands

I believe this might simplify the task to get `kinesis-local` inside your image. 

The API of LPM is not stable yet, which is why this isn't advertised. See https://github.com/localstack/localstack/issues/7924#issuecomment-1573292277

More informations about LPM usage: https://github.com/localstack/localstack/pull/8194#issuecomment-1522025328
