### ISSUE TITLE
enhancement request: stable docker image

### ISSUE THREAD

**Issue by sha1n** [localstack/localstack#9612]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Enhancement description

Our team uses the `localstack/localstask:latest` image for testing a large number of services. Over the past few weeks we had several issues caused by what appears to a bug in the latest image which caused CI failures around the dynamodb service in this case. I looked around for a different tag which is not a fixed version number with `stable` semantics and it doesn't seem to exist.

In order to help teams stay up to date without the need to constantly update image versions, it would be very helpful if you could provide a `stable` tag we can count on to be functional, or make sure the `latest` tag is stable.

### 🧑‍💻 Implementation

You could add a small step to the image release process, which adds a `stable` tag to the released image and pushes it, similar to `latest`.

**Comment by alexrashed** [comment]
Hi there!
Thanks for the input and the contribution!
I am pretty confident that we can bring this over the line today, with `3.0` being the first release with a `stable` tag.

However, I just wanted to mention this here, since it's pretty related: With https://github.com/localstack/localstack/issues/9488 and https://github.com/localstack/localstack/pull/9490, we will also be pushing major version tags starting with `3.0`.
This tag can be useful if you want to explicitly and manually upgrade major versions.

**Comment by sha1n** [comment]
Thank you very much @alexrashed! I appreciate the quick response 🚀
