### ISSUE TITLE
bug: VTL $util.time not working

### ISSUE THREAD

**Issue by simonrw** [localstack/localstack#9691]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

_This issue was originally reported in https://github.com/localstack/localstack/issues/9589 and has been extracted into this ticket for better tracking._

---

We use Localstack Pro and in our VTL template, we use the $util.time package to convert time to a long timestamp number.
But it returns empty

```
#set($seconds = $util.time.epochMilliSecondsToSeconds($milliSeconds)) ==> failed, $seconds is empty or undefined
#set($milliSeconds = $util.time.parseISO8601ToEpochMilliSeconds($date)) ==> failed, $milliSeconds is empty or undefined
```

Also, we use `$util.escapeJavaScript` and it failed. The result is empty or undefined

References:

* Util time [helpers](https://docs.aws.amazon.com/appsync/latest/devguide/time-helpers-in-util-time.html)

### Expected Behavior

We expect that

*  All functionalities in package `$util.time` that work perfectly without errors

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

docker-compose up

### Environment

```markdown
- OS: MacOs Monterey
- LocalStack: Pro latest
```

### Anything else?

No

cc @lqtruong

**Comment by macnev2013** [comment]
Hi @simonrw, functions related to `$util.time` were added in the following pull request: https://github.com/localstack/localstack-ext/pull/2392.

Here are the newly supported functions:

- `"nowEpochSeconds"`
- `"nowEpochMilliSeconds"`
- `"parseISO8601ToEpochMilliSeconds"`
- `"epochMilliSecondsToSeconds"`
- `"epochMilliSecondsToISO8601"`

Note: we have not implemented functions that parse time based on a formatting string. Because the formatting string used has different formatting pattern than what is supported in Python.
