### ISSUE TITLE
S3 PutObjectRequest fails if the body is JSON (or any non XML).

### ISSUE THREAD

**Issue by bcsgh** [localstack/localstack#9951]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When trying to put data into an s3 bucket, the request only works if the data is XML and fails if it's JSON.

On the server side I'm getting:
```
2023-12-27T22:12:56.512  INFO --- [   asgi_gw_1] localstack.request.http    : PUT /1703715176 => 500
2023-12-27T22:12:56.722 ERROR --- [   asgi_gw_0] l.aws.handlers.logging     : exception during call chain: Unable to parse request (not well-formed (invalid token): line 1, column 0), invalid XML received:
```

On the client side I'm seeing:
```
W1227 14:12:56.515219 2015469 AWS:-1] AWSErrorMarshaller: Encountered AWSError 'InternalError': exception while calling s3 with unknown operation: Unable to parse request (not well-formed (invalid token): line 1, column 0), invalid XML received:&#xA;b'{"x":"MY FAKE DATA"}'
E1227 14:12:56.515294 2015469 AWS:-1] AWSXmlClient: HTTP response code: 500
Resolved remote host IP address: 
Request ID: 13de44dd-e334-4674-8e03-4d5c07151728
Exception name: InternalError
Error message: exception while calling s3 with unknown operation: Unable to parse request (not well-formed (invalid token): line 1, column 0), invalid XML received:&#xA;b'{"x":"MY FAKE DATA"}'
7 response headers:
connection : close
content-length : 331
content-type : application/xml
date : Wed, 27 Dec 2023 22:12:56 GMT
server : hypercorn-h11
x-amz-id-2 : s9lzHYrFp76ZVxRcpX9+5cjAnEH2ROuNkd2BHfIa6UkFVdtjf5mKR3/eTPFvsiP/XV/VLi31234=
x-amz-request-id : 13de44dd-e334-4674-8e03-4d5c07151728
```

### Expected Behavior

The service should act the same regardless of the format of the data blob being uploaded.

### How are you starting LocalStack?

With the `localstack` script

### Steps To Reproduce

```
#include "aws/s3/S3Client.h"
#include "aws/s3/model/PutObjectRequest.h"

...

  Aws::S3::Model::PutObjectRequest s3req;
  s3req.SetBucket(Aws::String{bucket});
  s3req.SetKey(Aws::String{path});
  s3req.SetContentDisposition("application/octet-stream");
  s3req.SetBody(std::make_shared<std::stringstream>(Aws::String{R"JSON({})JSON"}));

  s3_client_->PutObject(s3req);
```

Changing to this woks:
```
s3req.SetBody(std::make_shared<std::stringstream>(Aws::String{R"XML(<a/>)XML"}));
```

### Environment

```markdown
- OS:


$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.6 LTS
Release:	20.04
Codename:	focal
```
- LocalStack:
```
$ curl http://localhost.localstack.cloud:4566/_localstack/health  | jq '[.version,.services.s3]'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   924  100   924    0     0   4914      0 --:--:-- --:--:-- --:--:--  4914
[
  "3.0.3.dev",
  "running"
]
```

### Anything else?

I kind of suspect the issue is here: https://github.com/localstack/localstack/blob/master/localstack/aws/protocol/parser.py#L968

```
class EC2RequestParser(QueryRequestParser):
...
class S3RequestParser(RestXMLRequestParser):     ## <<< Why XML?
...
class SQSQueryRequestParser(QueryRequestParser):
```

**Comment by bentsku** [comment]
Hello @bcsgh and thanks for your report!

This is not exactly an XML issue. S3 is a service using XML, to answer the question "why XML". All other operations that do not interact with objects are done with an XML body.

And that is the issue you are encountering: the request being sent is interpreted as a `CreateBucket` operation, if you check LocalStack logs.

This is because of the `virtual hosted` style request. You can read more about it here: https://docs.localstack.cloud/user-guide/aws/s3/#path-style-and-virtual-hosted-style-requests

If you want LocalStack to be able to parse the bucket out of the host, you need to use an host with a `s3.` prefix. Or, you can force your client to use `path style` requests.

We have some explanations for the S3 specific endpoint for other SDKs: https://docs.localstack.cloud/user-guide/integrations/sdks/ (for example, the JS SDK explains the difference pretty well https://docs.localstack.cloud/user-guide/integrations/sdks/javascript/) 

We could add an entry in the documentation to configure the S3 specific endpoint if you're not forcing path style. 
See this issue to force it in the cpp SDK (https://github.com/aws/aws-sdk-cpp/issues/587)

**Comment by bcsgh** [comment]
The utility of localstack degrades quickly the more that my usage of the official supported AWS SDK's need to conform to anything other than what AWS does.

Let me re-phrases the issue: In general (specifically when when the services, APIs and operations that will be done are **NOT** yet known) what single static value should be passed to [`Aws::Client::ClientConfiguration.endpointOverride`](https://sdk.amazonaws.com/cpp/api/LATEST/aws-cpp-sdk-core/html/struct_aws_1_1_client_1_1_client_configuration.html#a83b1e084eb22cebcc86e2a8f57b1954b) to make localstack work in all cases?

When  using AWS things seem to mostly just work the same everywhere, either work without setting `endpointOverride` or by at most setting `region`. Ideally,  using localstack should introduce a minimal change: just set one value everywhere and stuff just works.

**Comment by bentsku** [comment]
AWS bundles in their SDK the service specific endpoints they need to target each service. Sadly, we can't make use of that, which is why we need a little more configuration so that things "just works".
We still made pretty transparent for most services, but S3 is a bit special with its default use of the bucket in the host, which doesn't work with `localhost` or IP addresses. 

If you want a quick solution for this issue, the easiest is to set `useVirtualAddressing` when instantiating your S3 client: this will work with AWS and LocalStack, no need for different configurations between the two.

**Comment by bcsgh** [comment]
@bentsku "Update": for me, the tl;dr; of your answer is that localstack (at least for s3) is not compatible with my requirements.

Also, looking at the HTTP API documentation, it looks like localstack should be able to differentiate between a `CreateBucket` and a `PutObject` based on the path; for `CreateBucket` the path is exactly `/` where as for `PutObject` it is `/<KEY>` where (I think) `<KEY>` must not be empty. Given that passing random XML seems to work correctly it seems this path based logic is already in place somewhere, but is gated behind an XML syntax check. Resolving things should as simple as not forcing the body to be XML until *after* the inspection of the path. There is still the issue of how to figure out the correct bucket to operate on, but I suspect that's already an issue if what the user happens to PUT is valid XML, so that wouldn't be a regression (even if it's not correct).

**Comment by bentsku** [comment]
I'm not sure I follow your statement. 

The path will be different depending on the request being `virtual hosted` or `path` based.

For the 2 operations you mentioned, this is what the request to create a bucket looks like:
- `CreateBucket`
  - Virtual hosted: `PUT http://<bucket>.<domain>`, with an XML body. 
  - Path based: `PUT http://<domain>/<bucket>`, with an XML body. 

- `PutObject`
  - Virtual hosted: `PUT http://<bucket>.<domain>/<key>`, non specific body
  - Path based: `PUT http://<domain>/<bucket>/<key>`, non specific body

The issue here is that LocalStack will not recognize the request as being `virtual hosted` if the endpoint is not prefixed with `s3.` like so: `http://<bucket>.s3.<domain>`. LocalStack needs to be able to work with all AWS services, and without this prefix, we will end clashing with other service endpoints. 

So in your case, your request is being interpreted as the default `path` based request, `CreateBucket`, because the endpoint is not prefixed. Even if we didn't force the XML check, your request would still fail as we would be unable to parse the bucket from the request, so we would have no bucket name. 

So it is not possible for you to force the use of the path style request (`useVirtualAddressing`) ? Could I ask why?

The other solution was to set the endpoint when creating the specific S3 client to `s3.localhost.localstack.cloud:<port>`, which will allow LocalStack to understand request with the `virtual hosted` format.

**Comment by bcsgh** [comment]
I haven't dug into the code enough to know what's going on, but I ran the exact same binary twice, both time setting the endpoint to `http://localhost.localstack.cloud:4566`. When I set the body to `<a/>` I get a new object (not a new bucket) showing up in the existing bucket with that data in it. When I set the body to `{}` I get an error message. So empirically, localstack is able to correctly handle everything other than failing to parse the body as XML (which it subsequently, and correctly,  ignores the structure of).

Except that I have to much other stuff I need to be working on, I'm really tempted to try to figure out combinations of endpoints, buckets, keys and addressing modes that get miss interpreted by localstack. But it's looking like in order to run tests, stuff is starting to get far enough away from prod-AWS that "it works with localstack" isn't going to give me much confidence that it works in production. At that point, why bother; that's the entire point of using localstack!

---

As for why I'm not using `useVirtualAddressing`; because nothing I have interest in outside localstack benefits from that. 

---

### Side note:

 doing some more digging suggests that a better solution for pointing an AWS SDK client at localstack would be to use [environment variables](https://docs.aws.amazon.com/sdkref/latest/guide/settings-reference.html#EVarSettings) (in particular `AWS_ENDPOINT_URL_<SERVICE>`). Assuming the client code doesn't override anything, that would avoid needing to inject the fact that localstack is being used into the code. Any chance of getting a published "run with this environment" script that can be sourced in before running un-modified client code?

**Comment by bentsku** [comment]
I would need to see the code and how it's used, but if LocalStack tries to decode XML, it should not interpret the request as a `PutObject` operation: those 2 are linked, and if the request is `PutObject`, it does not try to decode the XML, we only pass a stream of binary data downstream.
LocalStack, in order, tries to assess what is the operation, and only then decodes the request. If you could start LocalStack with `LS_LOG=trace`, we could see what operations are recognized when you're running the binary with the 2 scenarios above.

Without the logs, I cannot correctly assess what is going on, maybe the issue is different than what I am thinking.

Regarding finding combinations that works, modifying endpoint/addressing mode in your tests should not have any influence on production (endpoint is mandatory anyway, and both addressing modes are supported by S3). Only setting `useVirtualAddressing` when running your tests locally can't break your setup in prod, as AWS supports both. If you'd rather not use it as you said, then having a flag to set the endpoint URL to `s3.localhost.localstack.cloud:4566` for your S3 client in your test is the only solution for now. I know it's not ideal to have a different one, but we are sadly limited here.

For the side note: 
It seems sadly that these environment variables are not supported yet by the C++ SDK: https://docs.aws.amazon.com/sdkref/latest/guide/feature-ss-endpoints.html#ss-endpoints-sdk-compat

Once `AWS_ENDPOINT_URL_<SERVICE>` would be supported by your SDK, I agree that everything would be way more transparent, you could use a default `AWS_ENDPOINT_URL=localhost.localstack.cloud` and then specifics like `AWS_ENDPOINT_URL_S3=s3.localhost.localstack.cloud`, which would greatly simplifies thing, even for us.

**Comment by bcsgh** [comment]
My client code is approximately this:

```
Aws::SDKOptions options;
options.loggingOptions.logLevel = Aws::Utils::Logging::LogLevel::Info;
options.loggingOptions.logger_create_fn = &std::make_shared<AbslLogger>;

Aws::InitAPI(options);

// ...

Aws::Client::ClientConfiguration cfg(false);

// Defaults to "" and goes un-set (which works just fine) in prod.
if (absl::GetFlag(FLAGS_aws_s3_sink_endpoint) != "") {
  cfg.endpointOverride = absl::GetFlag(FLAGS_aws_s3_sink_endpoint);
}

auto cred = GetAwsCredentials();
s3_client = std::make_unique<Aws::S3::S3Client>(cred, cfg,
    // values to get the same result as the cfg-only overload.
    // I'd really rather just use the cfg-only overload directly.
    /*signPayloads=*/Aws::Client::AWSAuthV4Signer::PayloadSigningPolicy::Never,
    /*useVirtualAddressing=*/false);

Aws::S3::Model::PutObjectRequest s3req;
s3req.SetBucket(bucket_);
s3req.SetKey(path);
s3req.SetContentDisposition("application/octet-stream");

s3req.SetBody(std::make_shared<std::stringstream>("{}"));
// s3req.SetBody(std::make_shared<std::stringstream>("<a/>"));

auto s3resp = s3_client->PutObject(s3req);
out << s3resp.IsSuccess() << ": " << 3resp.GetError().GetMessage();
```

Testing it with the endpoint flag unset is working just fine so `endpointOverride`, so as far as prod usage is concerned, is **not** mandatory.

**Comment by thrau** [comment]
hey @bcsgh, to briefly summarize:
* we unfortunately need workarounds to handle s3 requests. we realize this is not ideal but there's nothing we can do about that right now for reasons that @bentsku has explained.
* that said, we do appreciate your feedback and understand the points you are making. we're continuously improving localstack to make sure users have to change as little as possible in their code. s3 is just a difficult service.
* if you don't want to use `useVirtualAddressing`, the best way forward is to create a client for s3 and one for all other services. use `s3.localhost.localstack.cloud:4566` as endpoint URL for the s3 client, and `localhost.localstack.cloud:4566` for all other services. those are the options you have.

**Comment by bcsgh** [comment]
To summarize from my perspective:

- localstack is doing stuff that directly contradicts the way bentsku seems to claim it works leading me to think that either it isn't supposed to work the way they think it is or it doesn't work the way it's supposed to.
- localstack doesn't provide enough value to over testsing on dev resources in prod AWS to justify the added complexity.

I think I'm going to take option 3 and not use localstack.

**Comment by thrau** [comment]
that's very regrettable, but thanks for giving it a try! and thanks for the feedback, we'll continue to improve the s3 experience as best we can.

**Comment by bechampion** [comment]
For anyone out there , the main issue is with the path of the `PUT` request eg:
`PUT /bucket/key` works
`PUT /key` doesn't  you can tcpdump and check So using the aws sdk like this ```	input := &s3.PutObjectInput{
		Bucket:      aws.String("dada"),
		Key:         aws.String("dada/demokey"),
		Body:        strings.NewReader(string(jsonData)),
		ContentType: aws.String("application/json"),
	}
``` made it work for me

**Comment by m4rr0c0s** [comment]
I was struggling to figure out what I was doing wrong in order to save my terraform.tfstate file in a s3 bucket using localstack as backend and based on bechampion tip I managed to fix my issue. I just had to add `use_path_style = true` inside backend s3 block and it worked.

This was my issue:
```
Error: Failed to save state
│ 
│ Error saving state: failed to upload state: operation error S3: PutObject, exceeded maximum number of attempts, 5, https response error StatusCode: 500, RequestID:
│ 32c88b15-12b8-4ee2-8827-10380efe759e, HostID: s9lzHYrFp76ZVxRcpX9+5cjAnEH2ROuNkd2BHfIa6UkFVdtjf5mKR3/eTPFvsiP/XV/VLi31234=, api error InternalError: exception while calling s3 with unknown
│ operation: Unable to parse request (not well-formed (invalid token): line 1, column 0), invalid XML received:
```

This is my config:
````

terraform {
  backend "s3" {
    bucket         = "bucket_name"
    key            = "terraform.tfstate"
    region         = "us-east-1"
    dynamodb_table = "dynamoTable_name"
    use_path_style = true
    endpoints = {
      s3       = "http://localhost:4566"
      dynamodb = "http://localhost:4566"
    }
  }
}
````

I hope it'll be useful to someone in future 🤙

**Comment by luckydogxf** [comment]
> I was struggling to figure out what I was doing wrong in order to save my terraform.tfstate file in a s3 bucket using localstack as backend and based on bechampion tip I managed to fix my issue. I just had to add `use_path_style = true` inside backend s3 block and it worked.
> 
> This was my issue:
> 
> ```
> Error: Failed to save state
> │ 
> │ Error saving state: failed to upload state: operation error S3: PutObject, exceeded maximum number of attempts, 5, https response error StatusCode: 500, RequestID:
> │ 32c88b15-12b8-4ee2-8827-10380efe759e, HostID: s9lzHYrFp76ZVxRcpX9+5cjAnEH2ROuNkd2BHfIa6UkFVdtjf5mKR3/eTPFvsiP/XV/VLi31234=, api error InternalError: exception while calling s3 with unknown
> │ operation: Unable to parse request (not well-formed (invalid token): line 1, column 0), invalid XML received:
> ```
> 
> This is my config:
> 
> ```
> 
> terraform {
>   backend "s3" {
>     bucket         = "bucket_name"
>     key            = "terraform.tfstate"
>     region         = "us-east-1"
>     dynamodb_table = "dynamoTable_name"
>     use_path_style = true
>     endpoints = {
>       s3       = "http://localhost:4566"
>       dynamodb = "http://localhost:4566"
>     }
>   }
> }
> ```
> 
> I hope it'll be useful to someone in future 🤙

You definitely save my day. It works like a charm. Thanks.
